// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.1
// source: c_peer2peer_netmessages.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { CMsgVoiceAudio } from "./netmessages.js";
import { CMsgQAngle, CMsgVector } from "./networkbasetypes.js";

export const protobufPackage = "";

export const P2P_Messages = {
  p2p_TextMessage: 256,
  p2p_Voice: 257,
  p2p_Ping: 258,
  p2p_VRAvatarPosition: 259,
  p2p_WatchSynchronization: 260,
  p2p_FightingGame_GameData: 261,
  p2p_FightingGame_Connection: 262,
  UNRECOGNIZED: -1,
} as const;

export type P2P_Messages = typeof P2P_Messages[keyof typeof P2P_Messages];

export namespace P2P_Messages {
  export type p2p_TextMessage = typeof P2P_Messages.p2p_TextMessage;
  export type p2p_Voice = typeof P2P_Messages.p2p_Voice;
  export type p2p_Ping = typeof P2P_Messages.p2p_Ping;
  export type p2p_VRAvatarPosition = typeof P2P_Messages.p2p_VRAvatarPosition;
  export type p2p_WatchSynchronization = typeof P2P_Messages.p2p_WatchSynchronization;
  export type p2p_FightingGame_GameData = typeof P2P_Messages.p2p_FightingGame_GameData;
  export type p2p_FightingGame_Connection = typeof P2P_Messages.p2p_FightingGame_Connection;
  export type UNRECOGNIZED = typeof P2P_Messages.UNRECOGNIZED;
}

export function p2P_MessagesFromJSON(object: any): P2P_Messages {
  switch (object) {
    case 256:
    case "p2p_TextMessage":
      return P2P_Messages.p2p_TextMessage;
    case 257:
    case "p2p_Voice":
      return P2P_Messages.p2p_Voice;
    case 258:
    case "p2p_Ping":
      return P2P_Messages.p2p_Ping;
    case 259:
    case "p2p_VRAvatarPosition":
      return P2P_Messages.p2p_VRAvatarPosition;
    case 260:
    case "p2p_WatchSynchronization":
      return P2P_Messages.p2p_WatchSynchronization;
    case 261:
    case "p2p_FightingGame_GameData":
      return P2P_Messages.p2p_FightingGame_GameData;
    case 262:
    case "p2p_FightingGame_Connection":
      return P2P_Messages.p2p_FightingGame_Connection;
    case -1:
    case "UNRECOGNIZED":
    default:
      return P2P_Messages.UNRECOGNIZED;
  }
}

export function p2P_MessagesToJSON(object: P2P_Messages): string {
  switch (object) {
    case P2P_Messages.p2p_TextMessage:
      return "p2p_TextMessage";
    case P2P_Messages.p2p_Voice:
      return "p2p_Voice";
    case P2P_Messages.p2p_Ping:
      return "p2p_Ping";
    case P2P_Messages.p2p_VRAvatarPosition:
      return "p2p_VRAvatarPosition";
    case P2P_Messages.p2p_WatchSynchronization:
      return "p2p_WatchSynchronization";
    case P2P_Messages.p2p_FightingGame_GameData:
      return "p2p_FightingGame_GameData";
    case P2P_Messages.p2p_FightingGame_Connection:
      return "p2p_FightingGame_Connection";
    case P2P_Messages.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface CP2P_TextMessage {
  text?: Uint8Array | undefined;
}

export interface CSteam_Voice_Encoding {
  voice_data?: Uint8Array | undefined;
}

export interface CP2P_Voice {
  audio?: CMsgVoiceAudio | undefined;
  broadcast_group?: number | undefined;
}

export const CP2P_Voice_Handler_Flags = { Played_Audio: 1, UNRECOGNIZED: -1 } as const;

export type CP2P_Voice_Handler_Flags = typeof CP2P_Voice_Handler_Flags[keyof typeof CP2P_Voice_Handler_Flags];

export namespace CP2P_Voice_Handler_Flags {
  export type Played_Audio = typeof CP2P_Voice_Handler_Flags.Played_Audio;
  export type UNRECOGNIZED = typeof CP2P_Voice_Handler_Flags.UNRECOGNIZED;
}

export function cP2P_Voice_Handler_FlagsFromJSON(object: any): CP2P_Voice_Handler_Flags {
  switch (object) {
    case 1:
    case "Played_Audio":
      return CP2P_Voice_Handler_Flags.Played_Audio;
    case -1:
    case "UNRECOGNIZED":
    default:
      return CP2P_Voice_Handler_Flags.UNRECOGNIZED;
  }
}

export function cP2P_Voice_Handler_FlagsToJSON(object: CP2P_Voice_Handler_Flags): string {
  switch (object) {
    case CP2P_Voice_Handler_Flags.Played_Audio:
      return "Played_Audio";
    case CP2P_Voice_Handler_Flags.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface CP2P_Ping {
  send_time?: string | undefined;
  is_reply?: boolean | undefined;
}

export interface CP2P_VRAvatarPosition {
  body_parts: CP2P_VRAvatarPosition_COrientation[];
  hat_id?: number | undefined;
  scene_id?: number | undefined;
  world_scale?: number | undefined;
}

export interface CP2P_VRAvatarPosition_COrientation {
  pos?: CMsgVector | undefined;
  ang?: CMsgQAngle | undefined;
}

export interface CP2P_WatchSynchronization {
  demo_tick?: number | undefined;
  paused?: boolean | undefined;
  tv_listen_voice_indices?: string | undefined;
  dota_spectator_mode?: number | undefined;
  dota_spectator_watching_broadcaster?: boolean | undefined;
  dota_spectator_hero_index?: number | undefined;
  dota_spectator_autospeed?: number | undefined;
  dota_replay_speed?: number | undefined;
}

function createBaseCP2P_TextMessage(): CP2P_TextMessage {
  return { text: undefined };
}

export const CP2P_TextMessage: MessageFns<CP2P_TextMessage> = {
  encode(message: CP2P_TextMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.text !== undefined) {
      writer.uint32(10).bytes(message.text);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CP2P_TextMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCP2P_TextMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.text = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CP2P_TextMessage {
    return { text: isSet(object.text) ? bytesFromBase64(object.text) : undefined };
  },

  toJSON(message: CP2P_TextMessage): unknown {
    const obj: any = {};
    if (message.text !== undefined) {
      obj.text = base64FromBytes(message.text);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CP2P_TextMessage>, I>>(base?: I): CP2P_TextMessage {
    return CP2P_TextMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CP2P_TextMessage>, I>>(object: I): CP2P_TextMessage {
    const message = createBaseCP2P_TextMessage();
    message.text = object.text ?? undefined;
    return message;
  },
};

function createBaseCSteam_Voice_Encoding(): CSteam_Voice_Encoding {
  return { voice_data: undefined };
}

export const CSteam_Voice_Encoding: MessageFns<CSteam_Voice_Encoding> = {
  encode(message: CSteam_Voice_Encoding, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.voice_data !== undefined) {
      writer.uint32(10).bytes(message.voice_data);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CSteam_Voice_Encoding {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCSteam_Voice_Encoding();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.voice_data = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CSteam_Voice_Encoding {
    return {
      voice_data: isSet(object.voiceData)
        ? bytesFromBase64(object.voiceData)
        : isSet(object.voice_data)
        ? bytesFromBase64(object.voice_data)
        : undefined,
    };
  },

  toJSON(message: CSteam_Voice_Encoding): unknown {
    const obj: any = {};
    if (message.voice_data !== undefined) {
      obj.voiceData = base64FromBytes(message.voice_data);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CSteam_Voice_Encoding>, I>>(base?: I): CSteam_Voice_Encoding {
    return CSteam_Voice_Encoding.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CSteam_Voice_Encoding>, I>>(object: I): CSteam_Voice_Encoding {
    const message = createBaseCSteam_Voice_Encoding();
    message.voice_data = object.voice_data ?? undefined;
    return message;
  },
};

function createBaseCP2P_Voice(): CP2P_Voice {
  return { audio: undefined, broadcast_group: undefined };
}

export const CP2P_Voice: MessageFns<CP2P_Voice> = {
  encode(message: CP2P_Voice, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.audio !== undefined) {
      CMsgVoiceAudio.encode(message.audio, writer.uint32(10).fork()).join();
    }
    if (message.broadcast_group !== undefined) {
      writer.uint32(16).uint32(message.broadcast_group);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CP2P_Voice {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCP2P_Voice();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.audio = CMsgVoiceAudio.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.broadcast_group = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CP2P_Voice {
    return {
      audio: isSet(object.audio) ? CMsgVoiceAudio.fromJSON(object.audio) : undefined,
      broadcast_group: isSet(object.broadcastGroup)
        ? globalThis.Number(object.broadcastGroup)
        : isSet(object.broadcast_group)
        ? globalThis.Number(object.broadcast_group)
        : undefined,
    };
  },

  toJSON(message: CP2P_Voice): unknown {
    const obj: any = {};
    if (message.audio !== undefined) {
      obj.audio = CMsgVoiceAudio.toJSON(message.audio);
    }
    if (message.broadcast_group !== undefined) {
      obj.broadcastGroup = Math.round(message.broadcast_group);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CP2P_Voice>, I>>(base?: I): CP2P_Voice {
    return CP2P_Voice.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CP2P_Voice>, I>>(object: I): CP2P_Voice {
    const message = createBaseCP2P_Voice();
    message.audio = (object.audio !== undefined && object.audio !== null)
      ? CMsgVoiceAudio.fromPartial(object.audio)
      : undefined;
    message.broadcast_group = object.broadcast_group ?? undefined;
    return message;
  },
};

function createBaseCP2P_Ping(): CP2P_Ping {
  return { send_time: undefined, is_reply: undefined };
}

export const CP2P_Ping: MessageFns<CP2P_Ping> = {
  encode(message: CP2P_Ping, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.send_time !== undefined) {
      writer.uint32(8).uint64(message.send_time);
    }
    if (message.is_reply !== undefined) {
      writer.uint32(16).bool(message.is_reply);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CP2P_Ping {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCP2P_Ping();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.send_time = reader.uint64().toString();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.is_reply = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CP2P_Ping {
    return {
      send_time: isSet(object.sendTime)
        ? globalThis.String(object.sendTime)
        : isSet(object.send_time)
        ? globalThis.String(object.send_time)
        : undefined,
      is_reply: isSet(object.isReply)
        ? globalThis.Boolean(object.isReply)
        : isSet(object.is_reply)
        ? globalThis.Boolean(object.is_reply)
        : undefined,
    };
  },

  toJSON(message: CP2P_Ping): unknown {
    const obj: any = {};
    if (message.send_time !== undefined) {
      obj.sendTime = message.send_time;
    }
    if (message.is_reply !== undefined) {
      obj.isReply = message.is_reply;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CP2P_Ping>, I>>(base?: I): CP2P_Ping {
    return CP2P_Ping.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CP2P_Ping>, I>>(object: I): CP2P_Ping {
    const message = createBaseCP2P_Ping();
    message.send_time = object.send_time ?? undefined;
    message.is_reply = object.is_reply ?? undefined;
    return message;
  },
};

function createBaseCP2P_VRAvatarPosition(): CP2P_VRAvatarPosition {
  return { body_parts: [], hat_id: undefined, scene_id: undefined, world_scale: undefined };
}

export const CP2P_VRAvatarPosition: MessageFns<CP2P_VRAvatarPosition> = {
  encode(message: CP2P_VRAvatarPosition, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.body_parts) {
      CP2P_VRAvatarPosition_COrientation.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.hat_id !== undefined) {
      writer.uint32(16).int32(message.hat_id);
    }
    if (message.scene_id !== undefined) {
      writer.uint32(24).int32(message.scene_id);
    }
    if (message.world_scale !== undefined) {
      writer.uint32(32).int32(message.world_scale);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CP2P_VRAvatarPosition {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCP2P_VRAvatarPosition();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.body_parts.push(CP2P_VRAvatarPosition_COrientation.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.hat_id = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.scene_id = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.world_scale = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CP2P_VRAvatarPosition {
    return {
      body_parts: globalThis.Array.isArray(object?.bodyParts)
        ? object.bodyParts.map((e: any) => CP2P_VRAvatarPosition_COrientation.fromJSON(e))
        : globalThis.Array.isArray(object?.body_parts)
        ? object.body_parts.map((e: any) => CP2P_VRAvatarPosition_COrientation.fromJSON(e))
        : [],
      hat_id: isSet(object.hatId)
        ? globalThis.Number(object.hatId)
        : isSet(object.hat_id)
        ? globalThis.Number(object.hat_id)
        : undefined,
      scene_id: isSet(object.sceneId)
        ? globalThis.Number(object.sceneId)
        : isSet(object.scene_id)
        ? globalThis.Number(object.scene_id)
        : undefined,
      world_scale: isSet(object.worldScale)
        ? globalThis.Number(object.worldScale)
        : isSet(object.world_scale)
        ? globalThis.Number(object.world_scale)
        : undefined,
    };
  },

  toJSON(message: CP2P_VRAvatarPosition): unknown {
    const obj: any = {};
    if (message.body_parts?.length) {
      obj.bodyParts = message.body_parts.map((e) => CP2P_VRAvatarPosition_COrientation.toJSON(e));
    }
    if (message.hat_id !== undefined) {
      obj.hatId = Math.round(message.hat_id);
    }
    if (message.scene_id !== undefined) {
      obj.sceneId = Math.round(message.scene_id);
    }
    if (message.world_scale !== undefined) {
      obj.worldScale = Math.round(message.world_scale);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CP2P_VRAvatarPosition>, I>>(base?: I): CP2P_VRAvatarPosition {
    return CP2P_VRAvatarPosition.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CP2P_VRAvatarPosition>, I>>(object: I): CP2P_VRAvatarPosition {
    const message = createBaseCP2P_VRAvatarPosition();
    message.body_parts = object.body_parts?.map((e) => CP2P_VRAvatarPosition_COrientation.fromPartial(e)) || [];
    message.hat_id = object.hat_id ?? undefined;
    message.scene_id = object.scene_id ?? undefined;
    message.world_scale = object.world_scale ?? undefined;
    return message;
  },
};

function createBaseCP2P_VRAvatarPosition_COrientation(): CP2P_VRAvatarPosition_COrientation {
  return { pos: undefined, ang: undefined };
}

export const CP2P_VRAvatarPosition_COrientation: MessageFns<CP2P_VRAvatarPosition_COrientation> = {
  encode(message: CP2P_VRAvatarPosition_COrientation, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pos !== undefined) {
      CMsgVector.encode(message.pos, writer.uint32(10).fork()).join();
    }
    if (message.ang !== undefined) {
      CMsgQAngle.encode(message.ang, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CP2P_VRAvatarPosition_COrientation {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCP2P_VRAvatarPosition_COrientation();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.pos = CMsgVector.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.ang = CMsgQAngle.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CP2P_VRAvatarPosition_COrientation {
    return {
      pos: isSet(object.pos) ? CMsgVector.fromJSON(object.pos) : undefined,
      ang: isSet(object.ang) ? CMsgQAngle.fromJSON(object.ang) : undefined,
    };
  },

  toJSON(message: CP2P_VRAvatarPosition_COrientation): unknown {
    const obj: any = {};
    if (message.pos !== undefined) {
      obj.pos = CMsgVector.toJSON(message.pos);
    }
    if (message.ang !== undefined) {
      obj.ang = CMsgQAngle.toJSON(message.ang);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CP2P_VRAvatarPosition_COrientation>, I>>(
    base?: I,
  ): CP2P_VRAvatarPosition_COrientation {
    return CP2P_VRAvatarPosition_COrientation.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CP2P_VRAvatarPosition_COrientation>, I>>(
    object: I,
  ): CP2P_VRAvatarPosition_COrientation {
    const message = createBaseCP2P_VRAvatarPosition_COrientation();
    message.pos = (object.pos !== undefined && object.pos !== null) ? CMsgVector.fromPartial(object.pos) : undefined;
    message.ang = (object.ang !== undefined && object.ang !== null) ? CMsgQAngle.fromPartial(object.ang) : undefined;
    return message;
  },
};

function createBaseCP2P_WatchSynchronization(): CP2P_WatchSynchronization {
  return {
    demo_tick: undefined,
    paused: undefined,
    tv_listen_voice_indices: undefined,
    dota_spectator_mode: undefined,
    dota_spectator_watching_broadcaster: undefined,
    dota_spectator_hero_index: undefined,
    dota_spectator_autospeed: undefined,
    dota_replay_speed: undefined,
  };
}

export const CP2P_WatchSynchronization: MessageFns<CP2P_WatchSynchronization> = {
  encode(message: CP2P_WatchSynchronization, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.demo_tick !== undefined) {
      writer.uint32(8).int32(message.demo_tick);
    }
    if (message.paused !== undefined) {
      writer.uint32(16).bool(message.paused);
    }
    if (message.tv_listen_voice_indices !== undefined) {
      writer.uint32(24).uint64(message.tv_listen_voice_indices);
    }
    if (message.dota_spectator_mode !== undefined) {
      writer.uint32(32).int32(message.dota_spectator_mode);
    }
    if (message.dota_spectator_watching_broadcaster !== undefined) {
      writer.uint32(40).bool(message.dota_spectator_watching_broadcaster);
    }
    if (message.dota_spectator_hero_index !== undefined) {
      writer.uint32(48).int32(message.dota_spectator_hero_index);
    }
    if (message.dota_spectator_autospeed !== undefined) {
      writer.uint32(56).int32(message.dota_spectator_autospeed);
    }
    if (message.dota_replay_speed !== undefined) {
      writer.uint32(64).int32(message.dota_replay_speed);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CP2P_WatchSynchronization {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCP2P_WatchSynchronization();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.demo_tick = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.paused = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.tv_listen_voice_indices = reader.uint64().toString();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.dota_spectator_mode = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.dota_spectator_watching_broadcaster = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.dota_spectator_hero_index = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.dota_spectator_autospeed = reader.int32();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.dota_replay_speed = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CP2P_WatchSynchronization {
    return {
      demo_tick: isSet(object.demoTick)
        ? globalThis.Number(object.demoTick)
        : isSet(object.demo_tick)
        ? globalThis.Number(object.demo_tick)
        : undefined,
      paused: isSet(object.paused) ? globalThis.Boolean(object.paused) : undefined,
      tv_listen_voice_indices: isSet(object.tvListenVoiceIndices)
        ? globalThis.String(object.tvListenVoiceIndices)
        : isSet(object.tv_listen_voice_indices)
        ? globalThis.String(object.tv_listen_voice_indices)
        : undefined,
      dota_spectator_mode: isSet(object.dotaSpectatorMode)
        ? globalThis.Number(object.dotaSpectatorMode)
        : isSet(object.dota_spectator_mode)
        ? globalThis.Number(object.dota_spectator_mode)
        : undefined,
      dota_spectator_watching_broadcaster: isSet(object.dotaSpectatorWatchingBroadcaster)
        ? globalThis.Boolean(object.dotaSpectatorWatchingBroadcaster)
        : isSet(object.dota_spectator_watching_broadcaster)
        ? globalThis.Boolean(object.dota_spectator_watching_broadcaster)
        : undefined,
      dota_spectator_hero_index: isSet(object.dotaSpectatorHeroIndex)
        ? globalThis.Number(object.dotaSpectatorHeroIndex)
        : isSet(object.dota_spectator_hero_index)
        ? globalThis.Number(object.dota_spectator_hero_index)
        : undefined,
      dota_spectator_autospeed: isSet(object.dotaSpectatorAutospeed)
        ? globalThis.Number(object.dotaSpectatorAutospeed)
        : isSet(object.dota_spectator_autospeed)
        ? globalThis.Number(object.dota_spectator_autospeed)
        : undefined,
      dota_replay_speed: isSet(object.dotaReplaySpeed)
        ? globalThis.Number(object.dotaReplaySpeed)
        : isSet(object.dota_replay_speed)
        ? globalThis.Number(object.dota_replay_speed)
        : undefined,
    };
  },

  toJSON(message: CP2P_WatchSynchronization): unknown {
    const obj: any = {};
    if (message.demo_tick !== undefined) {
      obj.demoTick = Math.round(message.demo_tick);
    }
    if (message.paused !== undefined) {
      obj.paused = message.paused;
    }
    if (message.tv_listen_voice_indices !== undefined) {
      obj.tvListenVoiceIndices = message.tv_listen_voice_indices;
    }
    if (message.dota_spectator_mode !== undefined) {
      obj.dotaSpectatorMode = Math.round(message.dota_spectator_mode);
    }
    if (message.dota_spectator_watching_broadcaster !== undefined) {
      obj.dotaSpectatorWatchingBroadcaster = message.dota_spectator_watching_broadcaster;
    }
    if (message.dota_spectator_hero_index !== undefined) {
      obj.dotaSpectatorHeroIndex = Math.round(message.dota_spectator_hero_index);
    }
    if (message.dota_spectator_autospeed !== undefined) {
      obj.dotaSpectatorAutospeed = Math.round(message.dota_spectator_autospeed);
    }
    if (message.dota_replay_speed !== undefined) {
      obj.dotaReplaySpeed = Math.round(message.dota_replay_speed);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CP2P_WatchSynchronization>, I>>(base?: I): CP2P_WatchSynchronization {
    return CP2P_WatchSynchronization.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CP2P_WatchSynchronization>, I>>(object: I): CP2P_WatchSynchronization {
    const message = createBaseCP2P_WatchSynchronization();
    message.demo_tick = object.demo_tick ?? undefined;
    message.paused = object.paused ?? undefined;
    message.tv_listen_voice_indices = object.tv_listen_voice_indices ?? undefined;
    message.dota_spectator_mode = object.dota_spectator_mode ?? undefined;
    message.dota_spectator_watching_broadcaster = object.dota_spectator_watching_broadcaster ?? undefined;
    message.dota_spectator_hero_index = object.dota_spectator_hero_index ?? undefined;
    message.dota_spectator_autospeed = object.dota_spectator_autospeed ?? undefined;
    message.dota_replay_speed = object.dota_replay_speed ?? undefined;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from((globalThis as any).Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return (globalThis as any).Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
