// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.1
// source: clientmessages.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "";

export const EBaseClientMessages = {
  CM_CustomGameEvent: 280,
  CM_CustomGameEventBounce: 281,
  CM_ClientUIEvent: 282,
  CM_DevPaletteVisibilityChanged: 283,
  CM_WorldUIControllerHasPanelChanged: 284,
  CM_RotateAnchor: 285,
  CM_ListenForResponseFound: 286,
  CM_MAX_BASE: 300,
  UNRECOGNIZED: -1,
} as const;

export type EBaseClientMessages = typeof EBaseClientMessages[keyof typeof EBaseClientMessages];

export namespace EBaseClientMessages {
  export type CM_CustomGameEvent = typeof EBaseClientMessages.CM_CustomGameEvent;
  export type CM_CustomGameEventBounce = typeof EBaseClientMessages.CM_CustomGameEventBounce;
  export type CM_ClientUIEvent = typeof EBaseClientMessages.CM_ClientUIEvent;
  export type CM_DevPaletteVisibilityChanged = typeof EBaseClientMessages.CM_DevPaletteVisibilityChanged;
  export type CM_WorldUIControllerHasPanelChanged = typeof EBaseClientMessages.CM_WorldUIControllerHasPanelChanged;
  export type CM_RotateAnchor = typeof EBaseClientMessages.CM_RotateAnchor;
  export type CM_ListenForResponseFound = typeof EBaseClientMessages.CM_ListenForResponseFound;
  export type CM_MAX_BASE = typeof EBaseClientMessages.CM_MAX_BASE;
  export type UNRECOGNIZED = typeof EBaseClientMessages.UNRECOGNIZED;
}

export function eBaseClientMessagesFromJSON(object: any): EBaseClientMessages {
  switch (object) {
    case 280:
    case "CM_CustomGameEvent":
      return EBaseClientMessages.CM_CustomGameEvent;
    case 281:
    case "CM_CustomGameEventBounce":
      return EBaseClientMessages.CM_CustomGameEventBounce;
    case 282:
    case "CM_ClientUIEvent":
      return EBaseClientMessages.CM_ClientUIEvent;
    case 283:
    case "CM_DevPaletteVisibilityChanged":
      return EBaseClientMessages.CM_DevPaletteVisibilityChanged;
    case 284:
    case "CM_WorldUIControllerHasPanelChanged":
      return EBaseClientMessages.CM_WorldUIControllerHasPanelChanged;
    case 285:
    case "CM_RotateAnchor":
      return EBaseClientMessages.CM_RotateAnchor;
    case 286:
    case "CM_ListenForResponseFound":
      return EBaseClientMessages.CM_ListenForResponseFound;
    case 300:
    case "CM_MAX_BASE":
      return EBaseClientMessages.CM_MAX_BASE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return EBaseClientMessages.UNRECOGNIZED;
  }
}

export function eBaseClientMessagesToJSON(object: EBaseClientMessages): string {
  switch (object) {
    case EBaseClientMessages.CM_CustomGameEvent:
      return "CM_CustomGameEvent";
    case EBaseClientMessages.CM_CustomGameEventBounce:
      return "CM_CustomGameEventBounce";
    case EBaseClientMessages.CM_ClientUIEvent:
      return "CM_ClientUIEvent";
    case EBaseClientMessages.CM_DevPaletteVisibilityChanged:
      return "CM_DevPaletteVisibilityChanged";
    case EBaseClientMessages.CM_WorldUIControllerHasPanelChanged:
      return "CM_WorldUIControllerHasPanelChanged";
    case EBaseClientMessages.CM_RotateAnchor:
      return "CM_RotateAnchor";
    case EBaseClientMessages.CM_ListenForResponseFound:
      return "CM_ListenForResponseFound";
    case EBaseClientMessages.CM_MAX_BASE:
      return "CM_MAX_BASE";
    case EBaseClientMessages.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export const EClientUIEvent = {
  EClientUIEvent_Invalid: 0,
  EClientUIEvent_DialogFinished: 1,
  EClientUIEvent_FireOutput: 2,
  UNRECOGNIZED: -1,
} as const;

export type EClientUIEvent = typeof EClientUIEvent[keyof typeof EClientUIEvent];

export namespace EClientUIEvent {
  export type EClientUIEvent_Invalid = typeof EClientUIEvent.EClientUIEvent_Invalid;
  export type EClientUIEvent_DialogFinished = typeof EClientUIEvent.EClientUIEvent_DialogFinished;
  export type EClientUIEvent_FireOutput = typeof EClientUIEvent.EClientUIEvent_FireOutput;
  export type UNRECOGNIZED = typeof EClientUIEvent.UNRECOGNIZED;
}

export function eClientUIEventFromJSON(object: any): EClientUIEvent {
  switch (object) {
    case 0:
    case "EClientUIEvent_Invalid":
      return EClientUIEvent.EClientUIEvent_Invalid;
    case 1:
    case "EClientUIEvent_DialogFinished":
      return EClientUIEvent.EClientUIEvent_DialogFinished;
    case 2:
    case "EClientUIEvent_FireOutput":
      return EClientUIEvent.EClientUIEvent_FireOutput;
    case -1:
    case "UNRECOGNIZED":
    default:
      return EClientUIEvent.UNRECOGNIZED;
  }
}

export function eClientUIEventToJSON(object: EClientUIEvent): string {
  switch (object) {
    case EClientUIEvent.EClientUIEvent_Invalid:
      return "EClientUIEvent_Invalid";
    case EClientUIEvent.EClientUIEvent_DialogFinished:
      return "EClientUIEvent_DialogFinished";
    case EClientUIEvent.EClientUIEvent_FireOutput:
      return "EClientUIEvent_FireOutput";
    case EClientUIEvent.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface CClientMsg_CustomGameEvent {
  event_name?: string | undefined;
  data?: Uint8Array | undefined;
}

export interface CClientMsg_CustomGameEventBounce {
  event_name?: string | undefined;
  data?: Uint8Array | undefined;
  player_slot?: number | undefined;
}

export interface CClientMsg_ClientUIEvent {
  event?: EClientUIEvent | undefined;
  ent_ehandle?: number | undefined;
  client_ehandle?: number | undefined;
  data1?: string | undefined;
  data2?: string | undefined;
}

export interface CClientMsg_DevPaletteVisibilityChangedEvent {
  visible?: boolean | undefined;
}

export interface CClientMsg_WorldUIControllerHasPanelChangedEvent {
  has_panel?: boolean | undefined;
  client_ehandle?: number | undefined;
  literal_hand_type?: number | undefined;
}

export interface CClientMsg_RotateAnchor {
  angle?: number | undefined;
}

export interface CClientMsg_ListenForResponseFound {
  player_slot?: number | undefined;
}

function createBaseCClientMsg_CustomGameEvent(): CClientMsg_CustomGameEvent {
  return { event_name: undefined, data: undefined };
}

export const CClientMsg_CustomGameEvent: MessageFns<CClientMsg_CustomGameEvent> = {
  encode(message: CClientMsg_CustomGameEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.event_name !== undefined) {
      writer.uint32(10).string(message.event_name);
    }
    if (message.data !== undefined) {
      writer.uint32(18).bytes(message.data);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CClientMsg_CustomGameEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCClientMsg_CustomGameEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.event_name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.data = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CClientMsg_CustomGameEvent {
    return {
      event_name: isSet(object.eventName)
        ? globalThis.String(object.eventName)
        : isSet(object.event_name)
        ? globalThis.String(object.event_name)
        : undefined,
      data: isSet(object.data) ? bytesFromBase64(object.data) : undefined,
    };
  },

  toJSON(message: CClientMsg_CustomGameEvent): unknown {
    const obj: any = {};
    if (message.event_name !== undefined) {
      obj.eventName = message.event_name;
    }
    if (message.data !== undefined) {
      obj.data = base64FromBytes(message.data);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CClientMsg_CustomGameEvent>, I>>(base?: I): CClientMsg_CustomGameEvent {
    return CClientMsg_CustomGameEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CClientMsg_CustomGameEvent>, I>>(object: I): CClientMsg_CustomGameEvent {
    const message = createBaseCClientMsg_CustomGameEvent();
    message.event_name = object.event_name ?? undefined;
    message.data = object.data ?? undefined;
    return message;
  },
};

function createBaseCClientMsg_CustomGameEventBounce(): CClientMsg_CustomGameEventBounce {
  return { event_name: undefined, data: undefined, player_slot: undefined };
}

export const CClientMsg_CustomGameEventBounce: MessageFns<CClientMsg_CustomGameEventBounce> = {
  encode(message: CClientMsg_CustomGameEventBounce, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.event_name !== undefined) {
      writer.uint32(10).string(message.event_name);
    }
    if (message.data !== undefined) {
      writer.uint32(18).bytes(message.data);
    }
    if (message.player_slot !== undefined) {
      writer.uint32(24).int32(message.player_slot);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CClientMsg_CustomGameEventBounce {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCClientMsg_CustomGameEventBounce();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.event_name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.data = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.player_slot = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CClientMsg_CustomGameEventBounce {
    return {
      event_name: isSet(object.eventName)
        ? globalThis.String(object.eventName)
        : isSet(object.event_name)
        ? globalThis.String(object.event_name)
        : undefined,
      data: isSet(object.data) ? bytesFromBase64(object.data) : undefined,
      player_slot: isSet(object.playerSlot)
        ? globalThis.Number(object.playerSlot)
        : isSet(object.player_slot)
        ? globalThis.Number(object.player_slot)
        : undefined,
    };
  },

  toJSON(message: CClientMsg_CustomGameEventBounce): unknown {
    const obj: any = {};
    if (message.event_name !== undefined) {
      obj.eventName = message.event_name;
    }
    if (message.data !== undefined) {
      obj.data = base64FromBytes(message.data);
    }
    if (message.player_slot !== undefined) {
      obj.playerSlot = Math.round(message.player_slot);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CClientMsg_CustomGameEventBounce>, I>>(
    base?: I,
  ): CClientMsg_CustomGameEventBounce {
    return CClientMsg_CustomGameEventBounce.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CClientMsg_CustomGameEventBounce>, I>>(
    object: I,
  ): CClientMsg_CustomGameEventBounce {
    const message = createBaseCClientMsg_CustomGameEventBounce();
    message.event_name = object.event_name ?? undefined;
    message.data = object.data ?? undefined;
    message.player_slot = object.player_slot ?? undefined;
    return message;
  },
};

function createBaseCClientMsg_ClientUIEvent(): CClientMsg_ClientUIEvent {
  return { event: undefined, ent_ehandle: undefined, client_ehandle: undefined, data1: undefined, data2: undefined };
}

export const CClientMsg_ClientUIEvent: MessageFns<CClientMsg_ClientUIEvent> = {
  encode(message: CClientMsg_ClientUIEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.event !== undefined) {
      writer.uint32(8).int32(message.event);
    }
    if (message.ent_ehandle !== undefined) {
      writer.uint32(16).uint32(message.ent_ehandle);
    }
    if (message.client_ehandle !== undefined) {
      writer.uint32(24).uint32(message.client_ehandle);
    }
    if (message.data1 !== undefined) {
      writer.uint32(34).string(message.data1);
    }
    if (message.data2 !== undefined) {
      writer.uint32(42).string(message.data2);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CClientMsg_ClientUIEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCClientMsg_ClientUIEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.event = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.ent_ehandle = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.client_ehandle = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.data1 = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.data2 = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CClientMsg_ClientUIEvent {
    return {
      event: isSet(object.event) ? eClientUIEventFromJSON(object.event) : undefined,
      ent_ehandle: isSet(object.entEhandle)
        ? globalThis.Number(object.entEhandle)
        : isSet(object.ent_ehandle)
        ? globalThis.Number(object.ent_ehandle)
        : undefined,
      client_ehandle: isSet(object.clientEhandle)
        ? globalThis.Number(object.clientEhandle)
        : isSet(object.client_ehandle)
        ? globalThis.Number(object.client_ehandle)
        : undefined,
      data1: isSet(object.data1) ? globalThis.String(object.data1) : undefined,
      data2: isSet(object.data2) ? globalThis.String(object.data2) : undefined,
    };
  },

  toJSON(message: CClientMsg_ClientUIEvent): unknown {
    const obj: any = {};
    if (message.event !== undefined) {
      obj.event = eClientUIEventToJSON(message.event);
    }
    if (message.ent_ehandle !== undefined) {
      obj.entEhandle = Math.round(message.ent_ehandle);
    }
    if (message.client_ehandle !== undefined) {
      obj.clientEhandle = Math.round(message.client_ehandle);
    }
    if (message.data1 !== undefined) {
      obj.data1 = message.data1;
    }
    if (message.data2 !== undefined) {
      obj.data2 = message.data2;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CClientMsg_ClientUIEvent>, I>>(base?: I): CClientMsg_ClientUIEvent {
    return CClientMsg_ClientUIEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CClientMsg_ClientUIEvent>, I>>(object: I): CClientMsg_ClientUIEvent {
    const message = createBaseCClientMsg_ClientUIEvent();
    message.event = object.event ?? undefined;
    message.ent_ehandle = object.ent_ehandle ?? undefined;
    message.client_ehandle = object.client_ehandle ?? undefined;
    message.data1 = object.data1 ?? undefined;
    message.data2 = object.data2 ?? undefined;
    return message;
  },
};

function createBaseCClientMsg_DevPaletteVisibilityChangedEvent(): CClientMsg_DevPaletteVisibilityChangedEvent {
  return { visible: undefined };
}

export const CClientMsg_DevPaletteVisibilityChangedEvent: MessageFns<CClientMsg_DevPaletteVisibilityChangedEvent> = {
  encode(
    message: CClientMsg_DevPaletteVisibilityChangedEvent,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.visible !== undefined) {
      writer.uint32(8).bool(message.visible);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CClientMsg_DevPaletteVisibilityChangedEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCClientMsg_DevPaletteVisibilityChangedEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.visible = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CClientMsg_DevPaletteVisibilityChangedEvent {
    return { visible: isSet(object.visible) ? globalThis.Boolean(object.visible) : undefined };
  },

  toJSON(message: CClientMsg_DevPaletteVisibilityChangedEvent): unknown {
    const obj: any = {};
    if (message.visible !== undefined) {
      obj.visible = message.visible;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CClientMsg_DevPaletteVisibilityChangedEvent>, I>>(
    base?: I,
  ): CClientMsg_DevPaletteVisibilityChangedEvent {
    return CClientMsg_DevPaletteVisibilityChangedEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CClientMsg_DevPaletteVisibilityChangedEvent>, I>>(
    object: I,
  ): CClientMsg_DevPaletteVisibilityChangedEvent {
    const message = createBaseCClientMsg_DevPaletteVisibilityChangedEvent();
    message.visible = object.visible ?? undefined;
    return message;
  },
};

function createBaseCClientMsg_WorldUIControllerHasPanelChangedEvent(): CClientMsg_WorldUIControllerHasPanelChangedEvent {
  return { has_panel: undefined, client_ehandle: undefined, literal_hand_type: undefined };
}

export const CClientMsg_WorldUIControllerHasPanelChangedEvent: MessageFns<
  CClientMsg_WorldUIControllerHasPanelChangedEvent
> = {
  encode(
    message: CClientMsg_WorldUIControllerHasPanelChangedEvent,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.has_panel !== undefined) {
      writer.uint32(8).bool(message.has_panel);
    }
    if (message.client_ehandle !== undefined) {
      writer.uint32(16).uint32(message.client_ehandle);
    }
    if (message.literal_hand_type !== undefined) {
      writer.uint32(24).uint32(message.literal_hand_type);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CClientMsg_WorldUIControllerHasPanelChangedEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCClientMsg_WorldUIControllerHasPanelChangedEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.has_panel = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.client_ehandle = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.literal_hand_type = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CClientMsg_WorldUIControllerHasPanelChangedEvent {
    return {
      has_panel: isSet(object.hasPanel)
        ? globalThis.Boolean(object.hasPanel)
        : isSet(object.has_panel)
        ? globalThis.Boolean(object.has_panel)
        : undefined,
      client_ehandle: isSet(object.clientEhandle)
        ? globalThis.Number(object.clientEhandle)
        : isSet(object.client_ehandle)
        ? globalThis.Number(object.client_ehandle)
        : undefined,
      literal_hand_type: isSet(object.literalHandType)
        ? globalThis.Number(object.literalHandType)
        : isSet(object.literal_hand_type)
        ? globalThis.Number(object.literal_hand_type)
        : undefined,
    };
  },

  toJSON(message: CClientMsg_WorldUIControllerHasPanelChangedEvent): unknown {
    const obj: any = {};
    if (message.has_panel !== undefined) {
      obj.hasPanel = message.has_panel;
    }
    if (message.client_ehandle !== undefined) {
      obj.clientEhandle = Math.round(message.client_ehandle);
    }
    if (message.literal_hand_type !== undefined) {
      obj.literalHandType = Math.round(message.literal_hand_type);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CClientMsg_WorldUIControllerHasPanelChangedEvent>, I>>(
    base?: I,
  ): CClientMsg_WorldUIControllerHasPanelChangedEvent {
    return CClientMsg_WorldUIControllerHasPanelChangedEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CClientMsg_WorldUIControllerHasPanelChangedEvent>, I>>(
    object: I,
  ): CClientMsg_WorldUIControllerHasPanelChangedEvent {
    const message = createBaseCClientMsg_WorldUIControllerHasPanelChangedEvent();
    message.has_panel = object.has_panel ?? undefined;
    message.client_ehandle = object.client_ehandle ?? undefined;
    message.literal_hand_type = object.literal_hand_type ?? undefined;
    return message;
  },
};

function createBaseCClientMsg_RotateAnchor(): CClientMsg_RotateAnchor {
  return { angle: undefined };
}

export const CClientMsg_RotateAnchor: MessageFns<CClientMsg_RotateAnchor> = {
  encode(message: CClientMsg_RotateAnchor, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.angle !== undefined) {
      writer.uint32(13).float(message.angle);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CClientMsg_RotateAnchor {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCClientMsg_RotateAnchor();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 13) {
            break;
          }

          message.angle = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CClientMsg_RotateAnchor {
    return { angle: isSet(object.angle) ? globalThis.Number(object.angle) : undefined };
  },

  toJSON(message: CClientMsg_RotateAnchor): unknown {
    const obj: any = {};
    if (message.angle !== undefined) {
      obj.angle = message.angle;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CClientMsg_RotateAnchor>, I>>(base?: I): CClientMsg_RotateAnchor {
    return CClientMsg_RotateAnchor.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CClientMsg_RotateAnchor>, I>>(object: I): CClientMsg_RotateAnchor {
    const message = createBaseCClientMsg_RotateAnchor();
    message.angle = object.angle ?? undefined;
    return message;
  },
};

function createBaseCClientMsg_ListenForResponseFound(): CClientMsg_ListenForResponseFound {
  return { player_slot: undefined };
}

export const CClientMsg_ListenForResponseFound: MessageFns<CClientMsg_ListenForResponseFound> = {
  encode(message: CClientMsg_ListenForResponseFound, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.player_slot !== undefined) {
      writer.uint32(8).int32(message.player_slot);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CClientMsg_ListenForResponseFound {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCClientMsg_ListenForResponseFound();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.player_slot = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CClientMsg_ListenForResponseFound {
    return {
      player_slot: isSet(object.playerSlot)
        ? globalThis.Number(object.playerSlot)
        : isSet(object.player_slot)
        ? globalThis.Number(object.player_slot)
        : undefined,
    };
  },

  toJSON(message: CClientMsg_ListenForResponseFound): unknown {
    const obj: any = {};
    if (message.player_slot !== undefined) {
      obj.playerSlot = Math.round(message.player_slot);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CClientMsg_ListenForResponseFound>, I>>(
    base?: I,
  ): CClientMsg_ListenForResponseFound {
    return CClientMsg_ListenForResponseFound.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CClientMsg_ListenForResponseFound>, I>>(
    object: I,
  ): CClientMsg_ListenForResponseFound {
    const message = createBaseCClientMsg_ListenForResponseFound();
    message.player_slot = object.player_slot ?? undefined;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from((globalThis as any).Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return (globalThis as any).Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
