// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.1
//   protoc               v3.20.3
// source: cs_gameevents.proto

/* eslint-disable */
import * as _m0 from "protobufjs/minimal";
import { CMsgQAngle, CMsgVector } from "./networkbasetypes";

export const protobufPackage = "";

export enum ECsgoGameEvents {
  GE_PlayerAnimEventId = 450,
  GE_RadioIconEventId = 451,
  GE_FireBulletsId = 452,
  UNRECOGNIZED = -1,
}

export function eCsgoGameEventsFromJSON(object: any): ECsgoGameEvents {
  switch (object) {
    case 450:
    case "GE_PlayerAnimEventId":
      return ECsgoGameEvents.GE_PlayerAnimEventId;
    case 451:
    case "GE_RadioIconEventId":
      return ECsgoGameEvents.GE_RadioIconEventId;
    case 452:
    case "GE_FireBulletsId":
      return ECsgoGameEvents.GE_FireBulletsId;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ECsgoGameEvents.UNRECOGNIZED;
  }
}

export function eCsgoGameEventsToJSON(object: ECsgoGameEvents): string {
  switch (object) {
    case ECsgoGameEvents.GE_PlayerAnimEventId:
      return "GE_PlayerAnimEventId";
    case ECsgoGameEvents.GE_RadioIconEventId:
      return "GE_RadioIconEventId";
    case ECsgoGameEvents.GE_FireBulletsId:
      return "GE_FireBulletsId";
    case ECsgoGameEvents.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface CMsgTEPlayerAnimEvent {
  player?: number | undefined;
  event?: number | undefined;
  data?: number | undefined;
}

export interface CMsgTERadioIcon {
  player?: number | undefined;
}

export interface CMsgTEFireBullets {
  origin?: CMsgVector | undefined;
  angles?: CMsgQAngle | undefined;
  weaponId?: number | undefined;
  mode?: number | undefined;
  seed?: number | undefined;
  player?: number | undefined;
  inaccuracy?: number | undefined;
  recoilIndex?: number | undefined;
  spread?: number | undefined;
  soundType?: number | undefined;
  itemDefIndex?: number | undefined;
  soundDspEffect?: number | undefined;
  entOrigin?: CMsgVector | undefined;
  numBulletsRemaining?: number | undefined;
  attackType?: number | undefined;
}

function createBaseCMsgTEPlayerAnimEvent(): CMsgTEPlayerAnimEvent {
  return { player: 16777215, event: 0, data: 0 };
}

export const CMsgTEPlayerAnimEvent = {
  encode(message: CMsgTEPlayerAnimEvent, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.player !== undefined && message.player !== 16777215) {
      writer.uint32(13).fixed32(message.player);
    }
    if (message.event !== undefined && message.event !== 0) {
      writer.uint32(16).uint32(message.event);
    }
    if (message.data !== undefined && message.data !== 0) {
      writer.uint32(24).int32(message.data);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CMsgTEPlayerAnimEvent {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgTEPlayerAnimEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 13) {
            break;
          }

          message.player = reader.fixed32();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.event = reader.uint32();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.data = reader.int32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CMsgTEPlayerAnimEvent {
    return {
      player: isSet(object.player) ? globalThis.Number(object.player) : 16777215,
      event: isSet(object.event) ? globalThis.Number(object.event) : 0,
      data: isSet(object.data) ? globalThis.Number(object.data) : 0,
    };
  },

  toJSON(message: CMsgTEPlayerAnimEvent): unknown {
    const obj: any = {};
    if (message.player !== undefined && message.player !== 16777215) {
      obj.player = Math.round(message.player);
    }
    if (message.event !== undefined && message.event !== 0) {
      obj.event = Math.round(message.event);
    }
    if (message.data !== undefined && message.data !== 0) {
      obj.data = Math.round(message.data);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CMsgTEPlayerAnimEvent>, I>>(base?: I): CMsgTEPlayerAnimEvent {
    return CMsgTEPlayerAnimEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CMsgTEPlayerAnimEvent>, I>>(object: I): CMsgTEPlayerAnimEvent {
    const message = createBaseCMsgTEPlayerAnimEvent();
    message.player = object.player ?? 16777215;
    message.event = object.event ?? 0;
    message.data = object.data ?? 0;
    return message;
  },
};

function createBaseCMsgTERadioIcon(): CMsgTERadioIcon {
  return { player: 16777215 };
}

export const CMsgTERadioIcon = {
  encode(message: CMsgTERadioIcon, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.player !== undefined && message.player !== 16777215) {
      writer.uint32(13).fixed32(message.player);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CMsgTERadioIcon {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgTERadioIcon();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 13) {
            break;
          }

          message.player = reader.fixed32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CMsgTERadioIcon {
    return { player: isSet(object.player) ? globalThis.Number(object.player) : 16777215 };
  },

  toJSON(message: CMsgTERadioIcon): unknown {
    const obj: any = {};
    if (message.player !== undefined && message.player !== 16777215) {
      obj.player = Math.round(message.player);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CMsgTERadioIcon>, I>>(base?: I): CMsgTERadioIcon {
    return CMsgTERadioIcon.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CMsgTERadioIcon>, I>>(object: I): CMsgTERadioIcon {
    const message = createBaseCMsgTERadioIcon();
    message.player = object.player ?? 16777215;
    return message;
  },
};

function createBaseCMsgTEFireBullets(): CMsgTEFireBullets {
  return {
    origin: undefined,
    angles: undefined,
    weaponId: 16777215,
    mode: 0,
    seed: 0,
    player: 16777215,
    inaccuracy: 0,
    recoilIndex: 0,
    spread: 0,
    soundType: 0,
    itemDefIndex: 0,
    soundDspEffect: 0,
    entOrigin: undefined,
    numBulletsRemaining: 0,
    attackType: 0,
  };
}

export const CMsgTEFireBullets = {
  encode(message: CMsgTEFireBullets, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.origin !== undefined) {
      CMsgVector.encode(message.origin, writer.uint32(10).fork()).ldelim();
    }
    if (message.angles !== undefined) {
      CMsgQAngle.encode(message.angles, writer.uint32(18).fork()).ldelim();
    }
    if (message.weaponId !== undefined && message.weaponId !== 16777215) {
      writer.uint32(24).uint32(message.weaponId);
    }
    if (message.mode !== undefined && message.mode !== 0) {
      writer.uint32(32).uint32(message.mode);
    }
    if (message.seed !== undefined && message.seed !== 0) {
      writer.uint32(40).uint32(message.seed);
    }
    if (message.player !== undefined && message.player !== 16777215) {
      writer.uint32(53).fixed32(message.player);
    }
    if (message.inaccuracy !== undefined && message.inaccuracy !== 0) {
      writer.uint32(61).float(message.inaccuracy);
    }
    if (message.recoilIndex !== undefined && message.recoilIndex !== 0) {
      writer.uint32(69).float(message.recoilIndex);
    }
    if (message.spread !== undefined && message.spread !== 0) {
      writer.uint32(77).float(message.spread);
    }
    if (message.soundType !== undefined && message.soundType !== 0) {
      writer.uint32(80).int32(message.soundType);
    }
    if (message.itemDefIndex !== undefined && message.itemDefIndex !== 0) {
      writer.uint32(88).uint32(message.itemDefIndex);
    }
    if (message.soundDspEffect !== undefined && message.soundDspEffect !== 0) {
      writer.uint32(101).fixed32(message.soundDspEffect);
    }
    if (message.entOrigin !== undefined) {
      CMsgVector.encode(message.entOrigin, writer.uint32(106).fork()).ldelim();
    }
    if (message.numBulletsRemaining !== undefined && message.numBulletsRemaining !== 0) {
      writer.uint32(112).uint32(message.numBulletsRemaining);
    }
    if (message.attackType !== undefined && message.attackType !== 0) {
      writer.uint32(120).uint32(message.attackType);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CMsgTEFireBullets {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgTEFireBullets();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.origin = CMsgVector.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.angles = CMsgQAngle.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.weaponId = reader.uint32();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.mode = reader.uint32();
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.seed = reader.uint32();
          continue;
        case 6:
          if (tag !== 53) {
            break;
          }

          message.player = reader.fixed32();
          continue;
        case 7:
          if (tag !== 61) {
            break;
          }

          message.inaccuracy = reader.float();
          continue;
        case 8:
          if (tag !== 69) {
            break;
          }

          message.recoilIndex = reader.float();
          continue;
        case 9:
          if (tag !== 77) {
            break;
          }

          message.spread = reader.float();
          continue;
        case 10:
          if (tag !== 80) {
            break;
          }

          message.soundType = reader.int32();
          continue;
        case 11:
          if (tag !== 88) {
            break;
          }

          message.itemDefIndex = reader.uint32();
          continue;
        case 12:
          if (tag !== 101) {
            break;
          }

          message.soundDspEffect = reader.fixed32();
          continue;
        case 13:
          if (tag !== 106) {
            break;
          }

          message.entOrigin = CMsgVector.decode(reader, reader.uint32());
          continue;
        case 14:
          if (tag !== 112) {
            break;
          }

          message.numBulletsRemaining = reader.uint32();
          continue;
        case 15:
          if (tag !== 120) {
            break;
          }

          message.attackType = reader.uint32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CMsgTEFireBullets {
    return {
      origin: isSet(object.origin) ? CMsgVector.fromJSON(object.origin) : undefined,
      angles: isSet(object.angles) ? CMsgQAngle.fromJSON(object.angles) : undefined,
      weaponId: isSet(object.weaponId) ? globalThis.Number(object.weaponId) : 16777215,
      mode: isSet(object.mode) ? globalThis.Number(object.mode) : 0,
      seed: isSet(object.seed) ? globalThis.Number(object.seed) : 0,
      player: isSet(object.player) ? globalThis.Number(object.player) : 16777215,
      inaccuracy: isSet(object.inaccuracy) ? globalThis.Number(object.inaccuracy) : 0,
      recoilIndex: isSet(object.recoilIndex) ? globalThis.Number(object.recoilIndex) : 0,
      spread: isSet(object.spread) ? globalThis.Number(object.spread) : 0,
      soundType: isSet(object.soundType) ? globalThis.Number(object.soundType) : 0,
      itemDefIndex: isSet(object.itemDefIndex) ? globalThis.Number(object.itemDefIndex) : 0,
      soundDspEffect: isSet(object.soundDspEffect) ? globalThis.Number(object.soundDspEffect) : 0,
      entOrigin: isSet(object.entOrigin) ? CMsgVector.fromJSON(object.entOrigin) : undefined,
      numBulletsRemaining: isSet(object.numBulletsRemaining) ? globalThis.Number(object.numBulletsRemaining) : 0,
      attackType: isSet(object.attackType) ? globalThis.Number(object.attackType) : 0,
    };
  },

  toJSON(message: CMsgTEFireBullets): unknown {
    const obj: any = {};
    if (message.origin !== undefined) {
      obj.origin = CMsgVector.toJSON(message.origin);
    }
    if (message.angles !== undefined) {
      obj.angles = CMsgQAngle.toJSON(message.angles);
    }
    if (message.weaponId !== undefined && message.weaponId !== 16777215) {
      obj.weaponId = Math.round(message.weaponId);
    }
    if (message.mode !== undefined && message.mode !== 0) {
      obj.mode = Math.round(message.mode);
    }
    if (message.seed !== undefined && message.seed !== 0) {
      obj.seed = Math.round(message.seed);
    }
    if (message.player !== undefined && message.player !== 16777215) {
      obj.player = Math.round(message.player);
    }
    if (message.inaccuracy !== undefined && message.inaccuracy !== 0) {
      obj.inaccuracy = message.inaccuracy;
    }
    if (message.recoilIndex !== undefined && message.recoilIndex !== 0) {
      obj.recoilIndex = message.recoilIndex;
    }
    if (message.spread !== undefined && message.spread !== 0) {
      obj.spread = message.spread;
    }
    if (message.soundType !== undefined && message.soundType !== 0) {
      obj.soundType = Math.round(message.soundType);
    }
    if (message.itemDefIndex !== undefined && message.itemDefIndex !== 0) {
      obj.itemDefIndex = Math.round(message.itemDefIndex);
    }
    if (message.soundDspEffect !== undefined && message.soundDspEffect !== 0) {
      obj.soundDspEffect = Math.round(message.soundDspEffect);
    }
    if (message.entOrigin !== undefined) {
      obj.entOrigin = CMsgVector.toJSON(message.entOrigin);
    }
    if (message.numBulletsRemaining !== undefined && message.numBulletsRemaining !== 0) {
      obj.numBulletsRemaining = Math.round(message.numBulletsRemaining);
    }
    if (message.attackType !== undefined && message.attackType !== 0) {
      obj.attackType = Math.round(message.attackType);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CMsgTEFireBullets>, I>>(base?: I): CMsgTEFireBullets {
    return CMsgTEFireBullets.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CMsgTEFireBullets>, I>>(object: I): CMsgTEFireBullets {
    const message = createBaseCMsgTEFireBullets();
    message.origin = (object.origin !== undefined && object.origin !== null)
      ? CMsgVector.fromPartial(object.origin)
      : undefined;
    message.angles = (object.angles !== undefined && object.angles !== null)
      ? CMsgQAngle.fromPartial(object.angles)
      : undefined;
    message.weaponId = object.weaponId ?? 16777215;
    message.mode = object.mode ?? 0;
    message.seed = object.seed ?? 0;
    message.player = object.player ?? 16777215;
    message.inaccuracy = object.inaccuracy ?? 0;
    message.recoilIndex = object.recoilIndex ?? 0;
    message.spread = object.spread ?? 0;
    message.soundType = object.soundType ?? 0;
    message.itemDefIndex = object.itemDefIndex ?? 0;
    message.soundDspEffect = object.soundDspEffect ?? 0;
    message.entOrigin = (object.entOrigin !== undefined && object.entOrigin !== null)
      ? CMsgVector.fromPartial(object.entOrigin)
      : undefined;
    message.numBulletsRemaining = object.numBulletsRemaining ?? 0;
    message.attackType = object.attackType ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
