// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.1
// source: cs_usercmd.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { CMsgQAngle, CMsgVector } from "./networkbasetypes.js";
import { CBaseUserCmdPB } from "./usercmd.js";

export const protobufPackage = "";

export interface CSGOInterpolationInfoPB {
  src_tick?: number | undefined;
  dst_tick?: number | undefined;
  frac?: number | undefined;
}

export interface CSGOInterpolationInfoPB_CL {
  frac?: number | undefined;
}

export interface CSGOInputHistoryEntryPB {
  view_angles?: CMsgQAngle | undefined;
  render_tick_count?: number | undefined;
  render_tick_fraction?: number | undefined;
  player_tick_count?: number | undefined;
  player_tick_fraction?: number | undefined;
  cl_interp?: CSGOInterpolationInfoPB_CL | undefined;
  sv_interp0?: CSGOInterpolationInfoPB | undefined;
  sv_interp1?: CSGOInterpolationInfoPB | undefined;
  player_interp?: CSGOInterpolationInfoPB | undefined;
  frame_number?: number | undefined;
  target_ent_index?: number | undefined;
  shoot_position?: CMsgVector | undefined;
  target_head_pos_check?: CMsgVector | undefined;
  target_abs_pos_check?: CMsgVector | undefined;
  target_abs_ang_check?: CMsgQAngle | undefined;
}

export interface CSGOUserCmdPB {
  base?: CBaseUserCmdPB | undefined;
  input_history: CSGOInputHistoryEntryPB[];
  attack1_start_history_index?: number | undefined;
  attack2_start_history_index?: number | undefined;
  left_hand_desired?: boolean | undefined;
  is_predicting_body_shot_fx?: boolean | undefined;
  is_predicting_head_shot_fx?: boolean | undefined;
  is_predicting_kill_ragdolls?: boolean | undefined;
}

function createBaseCSGOInterpolationInfoPB(): CSGOInterpolationInfoPB {
  return { src_tick: undefined, dst_tick: undefined, frac: undefined };
}

export const CSGOInterpolationInfoPB: MessageFns<CSGOInterpolationInfoPB> = {
  encode(message: CSGOInterpolationInfoPB, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.src_tick !== undefined) {
      writer.uint32(8).int32(message.src_tick);
    }
    if (message.dst_tick !== undefined) {
      writer.uint32(16).int32(message.dst_tick);
    }
    if (message.frac !== undefined) {
      writer.uint32(29).float(message.frac);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CSGOInterpolationInfoPB {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCSGOInterpolationInfoPB();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.src_tick = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.dst_tick = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 29) {
            break;
          }

          message.frac = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CSGOInterpolationInfoPB {
    return {
      src_tick: isSet(object.srcTick)
        ? globalThis.Number(object.srcTick)
        : isSet(object.src_tick)
        ? globalThis.Number(object.src_tick)
        : undefined,
      dst_tick: isSet(object.dstTick)
        ? globalThis.Number(object.dstTick)
        : isSet(object.dst_tick)
        ? globalThis.Number(object.dst_tick)
        : undefined,
      frac: isSet(object.frac) ? globalThis.Number(object.frac) : undefined,
    };
  },

  toJSON(message: CSGOInterpolationInfoPB): unknown {
    const obj: any = {};
    if (message.src_tick !== undefined) {
      obj.srcTick = Math.round(message.src_tick);
    }
    if (message.dst_tick !== undefined) {
      obj.dstTick = Math.round(message.dst_tick);
    }
    if (message.frac !== undefined) {
      obj.frac = message.frac;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CSGOInterpolationInfoPB>, I>>(base?: I): CSGOInterpolationInfoPB {
    return CSGOInterpolationInfoPB.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CSGOInterpolationInfoPB>, I>>(object: I): CSGOInterpolationInfoPB {
    const message = createBaseCSGOInterpolationInfoPB();
    message.src_tick = object.src_tick ?? undefined;
    message.dst_tick = object.dst_tick ?? undefined;
    message.frac = object.frac ?? undefined;
    return message;
  },
};

function createBaseCSGOInterpolationInfoPB_CL(): CSGOInterpolationInfoPB_CL {
  return { frac: undefined };
}

export const CSGOInterpolationInfoPB_CL: MessageFns<CSGOInterpolationInfoPB_CL> = {
  encode(message: CSGOInterpolationInfoPB_CL, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.frac !== undefined) {
      writer.uint32(29).float(message.frac);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CSGOInterpolationInfoPB_CL {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCSGOInterpolationInfoPB_CL();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 3: {
          if (tag !== 29) {
            break;
          }

          message.frac = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CSGOInterpolationInfoPB_CL {
    return { frac: isSet(object.frac) ? globalThis.Number(object.frac) : undefined };
  },

  toJSON(message: CSGOInterpolationInfoPB_CL): unknown {
    const obj: any = {};
    if (message.frac !== undefined) {
      obj.frac = message.frac;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CSGOInterpolationInfoPB_CL>, I>>(base?: I): CSGOInterpolationInfoPB_CL {
    return CSGOInterpolationInfoPB_CL.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CSGOInterpolationInfoPB_CL>, I>>(object: I): CSGOInterpolationInfoPB_CL {
    const message = createBaseCSGOInterpolationInfoPB_CL();
    message.frac = object.frac ?? undefined;
    return message;
  },
};

function createBaseCSGOInputHistoryEntryPB(): CSGOInputHistoryEntryPB {
  return {
    view_angles: undefined,
    render_tick_count: undefined,
    render_tick_fraction: undefined,
    player_tick_count: undefined,
    player_tick_fraction: undefined,
    cl_interp: undefined,
    sv_interp0: undefined,
    sv_interp1: undefined,
    player_interp: undefined,
    frame_number: undefined,
    target_ent_index: undefined,
    shoot_position: undefined,
    target_head_pos_check: undefined,
    target_abs_pos_check: undefined,
    target_abs_ang_check: undefined,
  };
}

export const CSGOInputHistoryEntryPB: MessageFns<CSGOInputHistoryEntryPB> = {
  encode(message: CSGOInputHistoryEntryPB, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.view_angles !== undefined) {
      CMsgQAngle.encode(message.view_angles, writer.uint32(18).fork()).join();
    }
    if (message.render_tick_count !== undefined) {
      writer.uint32(32).int32(message.render_tick_count);
    }
    if (message.render_tick_fraction !== undefined) {
      writer.uint32(45).float(message.render_tick_fraction);
    }
    if (message.player_tick_count !== undefined) {
      writer.uint32(48).int32(message.player_tick_count);
    }
    if (message.player_tick_fraction !== undefined) {
      writer.uint32(61).float(message.player_tick_fraction);
    }
    if (message.cl_interp !== undefined) {
      CSGOInterpolationInfoPB_CL.encode(message.cl_interp, writer.uint32(98).fork()).join();
    }
    if (message.sv_interp0 !== undefined) {
      CSGOInterpolationInfoPB.encode(message.sv_interp0, writer.uint32(106).fork()).join();
    }
    if (message.sv_interp1 !== undefined) {
      CSGOInterpolationInfoPB.encode(message.sv_interp1, writer.uint32(114).fork()).join();
    }
    if (message.player_interp !== undefined) {
      CSGOInterpolationInfoPB.encode(message.player_interp, writer.uint32(122).fork()).join();
    }
    if (message.frame_number !== undefined) {
      writer.uint32(512).int32(message.frame_number);
    }
    if (message.target_ent_index !== undefined) {
      writer.uint32(520).int32(message.target_ent_index);
    }
    if (message.shoot_position !== undefined) {
      CMsgVector.encode(message.shoot_position, writer.uint32(530).fork()).join();
    }
    if (message.target_head_pos_check !== undefined) {
      CMsgVector.encode(message.target_head_pos_check, writer.uint32(538).fork()).join();
    }
    if (message.target_abs_pos_check !== undefined) {
      CMsgVector.encode(message.target_abs_pos_check, writer.uint32(546).fork()).join();
    }
    if (message.target_abs_ang_check !== undefined) {
      CMsgQAngle.encode(message.target_abs_ang_check, writer.uint32(554).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CSGOInputHistoryEntryPB {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCSGOInputHistoryEntryPB();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.view_angles = CMsgQAngle.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.render_tick_count = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 45) {
            break;
          }

          message.render_tick_fraction = reader.float();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.player_tick_count = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 61) {
            break;
          }

          message.player_tick_fraction = reader.float();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.cl_interp = CSGOInterpolationInfoPB_CL.decode(reader, reader.uint32());
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.sv_interp0 = CSGOInterpolationInfoPB.decode(reader, reader.uint32());
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.sv_interp1 = CSGOInterpolationInfoPB.decode(reader, reader.uint32());
          continue;
        }
        case 15: {
          if (tag !== 122) {
            break;
          }

          message.player_interp = CSGOInterpolationInfoPB.decode(reader, reader.uint32());
          continue;
        }
        case 64: {
          if (tag !== 512) {
            break;
          }

          message.frame_number = reader.int32();
          continue;
        }
        case 65: {
          if (tag !== 520) {
            break;
          }

          message.target_ent_index = reader.int32();
          continue;
        }
        case 66: {
          if (tag !== 530) {
            break;
          }

          message.shoot_position = CMsgVector.decode(reader, reader.uint32());
          continue;
        }
        case 67: {
          if (tag !== 538) {
            break;
          }

          message.target_head_pos_check = CMsgVector.decode(reader, reader.uint32());
          continue;
        }
        case 68: {
          if (tag !== 546) {
            break;
          }

          message.target_abs_pos_check = CMsgVector.decode(reader, reader.uint32());
          continue;
        }
        case 69: {
          if (tag !== 554) {
            break;
          }

          message.target_abs_ang_check = CMsgQAngle.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CSGOInputHistoryEntryPB {
    return {
      view_angles: isSet(object.viewAngles)
        ? CMsgQAngle.fromJSON(object.viewAngles)
        : isSet(object.view_angles)
        ? CMsgQAngle.fromJSON(object.view_angles)
        : undefined,
      render_tick_count: isSet(object.renderTickCount)
        ? globalThis.Number(object.renderTickCount)
        : isSet(object.render_tick_count)
        ? globalThis.Number(object.render_tick_count)
        : undefined,
      render_tick_fraction: isSet(object.renderTickFraction)
        ? globalThis.Number(object.renderTickFraction)
        : isSet(object.render_tick_fraction)
        ? globalThis.Number(object.render_tick_fraction)
        : undefined,
      player_tick_count: isSet(object.playerTickCount)
        ? globalThis.Number(object.playerTickCount)
        : isSet(object.player_tick_count)
        ? globalThis.Number(object.player_tick_count)
        : undefined,
      player_tick_fraction: isSet(object.playerTickFraction)
        ? globalThis.Number(object.playerTickFraction)
        : isSet(object.player_tick_fraction)
        ? globalThis.Number(object.player_tick_fraction)
        : undefined,
      cl_interp: isSet(object.clInterp)
        ? CSGOInterpolationInfoPB_CL.fromJSON(object.clInterp)
        : isSet(object.cl_interp)
        ? CSGOInterpolationInfoPB_CL.fromJSON(object.cl_interp)
        : undefined,
      sv_interp0: isSet(object.svInterp0)
        ? CSGOInterpolationInfoPB.fromJSON(object.svInterp0)
        : isSet(object.sv_interp0)
        ? CSGOInterpolationInfoPB.fromJSON(object.sv_interp0)
        : undefined,
      sv_interp1: isSet(object.svInterp1)
        ? CSGOInterpolationInfoPB.fromJSON(object.svInterp1)
        : isSet(object.sv_interp1)
        ? CSGOInterpolationInfoPB.fromJSON(object.sv_interp1)
        : undefined,
      player_interp: isSet(object.playerInterp)
        ? CSGOInterpolationInfoPB.fromJSON(object.playerInterp)
        : isSet(object.player_interp)
        ? CSGOInterpolationInfoPB.fromJSON(object.player_interp)
        : undefined,
      frame_number: isSet(object.frameNumber)
        ? globalThis.Number(object.frameNumber)
        : isSet(object.frame_number)
        ? globalThis.Number(object.frame_number)
        : undefined,
      target_ent_index: isSet(object.targetEntIndex)
        ? globalThis.Number(object.targetEntIndex)
        : isSet(object.target_ent_index)
        ? globalThis.Number(object.target_ent_index)
        : undefined,
      shoot_position: isSet(object.shootPosition)
        ? CMsgVector.fromJSON(object.shootPosition)
        : isSet(object.shoot_position)
        ? CMsgVector.fromJSON(object.shoot_position)
        : undefined,
      target_head_pos_check: isSet(object.targetHeadPosCheck)
        ? CMsgVector.fromJSON(object.targetHeadPosCheck)
        : isSet(object.target_head_pos_check)
        ? CMsgVector.fromJSON(object.target_head_pos_check)
        : undefined,
      target_abs_pos_check: isSet(object.targetAbsPosCheck)
        ? CMsgVector.fromJSON(object.targetAbsPosCheck)
        : isSet(object.target_abs_pos_check)
        ? CMsgVector.fromJSON(object.target_abs_pos_check)
        : undefined,
      target_abs_ang_check: isSet(object.targetAbsAngCheck)
        ? CMsgQAngle.fromJSON(object.targetAbsAngCheck)
        : isSet(object.target_abs_ang_check)
        ? CMsgQAngle.fromJSON(object.target_abs_ang_check)
        : undefined,
    };
  },

  toJSON(message: CSGOInputHistoryEntryPB): unknown {
    const obj: any = {};
    if (message.view_angles !== undefined) {
      obj.viewAngles = CMsgQAngle.toJSON(message.view_angles);
    }
    if (message.render_tick_count !== undefined) {
      obj.renderTickCount = Math.round(message.render_tick_count);
    }
    if (message.render_tick_fraction !== undefined) {
      obj.renderTickFraction = message.render_tick_fraction;
    }
    if (message.player_tick_count !== undefined) {
      obj.playerTickCount = Math.round(message.player_tick_count);
    }
    if (message.player_tick_fraction !== undefined) {
      obj.playerTickFraction = message.player_tick_fraction;
    }
    if (message.cl_interp !== undefined) {
      obj.clInterp = CSGOInterpolationInfoPB_CL.toJSON(message.cl_interp);
    }
    if (message.sv_interp0 !== undefined) {
      obj.svInterp0 = CSGOInterpolationInfoPB.toJSON(message.sv_interp0);
    }
    if (message.sv_interp1 !== undefined) {
      obj.svInterp1 = CSGOInterpolationInfoPB.toJSON(message.sv_interp1);
    }
    if (message.player_interp !== undefined) {
      obj.playerInterp = CSGOInterpolationInfoPB.toJSON(message.player_interp);
    }
    if (message.frame_number !== undefined) {
      obj.frameNumber = Math.round(message.frame_number);
    }
    if (message.target_ent_index !== undefined) {
      obj.targetEntIndex = Math.round(message.target_ent_index);
    }
    if (message.shoot_position !== undefined) {
      obj.shootPosition = CMsgVector.toJSON(message.shoot_position);
    }
    if (message.target_head_pos_check !== undefined) {
      obj.targetHeadPosCheck = CMsgVector.toJSON(message.target_head_pos_check);
    }
    if (message.target_abs_pos_check !== undefined) {
      obj.targetAbsPosCheck = CMsgVector.toJSON(message.target_abs_pos_check);
    }
    if (message.target_abs_ang_check !== undefined) {
      obj.targetAbsAngCheck = CMsgQAngle.toJSON(message.target_abs_ang_check);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CSGOInputHistoryEntryPB>, I>>(base?: I): CSGOInputHistoryEntryPB {
    return CSGOInputHistoryEntryPB.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CSGOInputHistoryEntryPB>, I>>(object: I): CSGOInputHistoryEntryPB {
    const message = createBaseCSGOInputHistoryEntryPB();
    message.view_angles = (object.view_angles !== undefined && object.view_angles !== null)
      ? CMsgQAngle.fromPartial(object.view_angles)
      : undefined;
    message.render_tick_count = object.render_tick_count ?? undefined;
    message.render_tick_fraction = object.render_tick_fraction ?? undefined;
    message.player_tick_count = object.player_tick_count ?? undefined;
    message.player_tick_fraction = object.player_tick_fraction ?? undefined;
    message.cl_interp = (object.cl_interp !== undefined && object.cl_interp !== null)
      ? CSGOInterpolationInfoPB_CL.fromPartial(object.cl_interp)
      : undefined;
    message.sv_interp0 = (object.sv_interp0 !== undefined && object.sv_interp0 !== null)
      ? CSGOInterpolationInfoPB.fromPartial(object.sv_interp0)
      : undefined;
    message.sv_interp1 = (object.sv_interp1 !== undefined && object.sv_interp1 !== null)
      ? CSGOInterpolationInfoPB.fromPartial(object.sv_interp1)
      : undefined;
    message.player_interp = (object.player_interp !== undefined && object.player_interp !== null)
      ? CSGOInterpolationInfoPB.fromPartial(object.player_interp)
      : undefined;
    message.frame_number = object.frame_number ?? undefined;
    message.target_ent_index = object.target_ent_index ?? undefined;
    message.shoot_position = (object.shoot_position !== undefined && object.shoot_position !== null)
      ? CMsgVector.fromPartial(object.shoot_position)
      : undefined;
    message.target_head_pos_check =
      (object.target_head_pos_check !== undefined && object.target_head_pos_check !== null)
        ? CMsgVector.fromPartial(object.target_head_pos_check)
        : undefined;
    message.target_abs_pos_check = (object.target_abs_pos_check !== undefined && object.target_abs_pos_check !== null)
      ? CMsgVector.fromPartial(object.target_abs_pos_check)
      : undefined;
    message.target_abs_ang_check = (object.target_abs_ang_check !== undefined && object.target_abs_ang_check !== null)
      ? CMsgQAngle.fromPartial(object.target_abs_ang_check)
      : undefined;
    return message;
  },
};

function createBaseCSGOUserCmdPB(): CSGOUserCmdPB {
  return {
    base: undefined,
    input_history: [],
    attack1_start_history_index: undefined,
    attack2_start_history_index: undefined,
    left_hand_desired: undefined,
    is_predicting_body_shot_fx: undefined,
    is_predicting_head_shot_fx: undefined,
    is_predicting_kill_ragdolls: undefined,
  };
}

export const CSGOUserCmdPB: MessageFns<CSGOUserCmdPB> = {
  encode(message: CSGOUserCmdPB, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.base !== undefined) {
      CBaseUserCmdPB.encode(message.base, writer.uint32(10).fork()).join();
    }
    for (const v of message.input_history) {
      CSGOInputHistoryEntryPB.encode(v!, writer.uint32(18).fork()).join();
    }
    if (message.attack1_start_history_index !== undefined) {
      writer.uint32(48).int32(message.attack1_start_history_index);
    }
    if (message.attack2_start_history_index !== undefined) {
      writer.uint32(56).int32(message.attack2_start_history_index);
    }
    if (message.left_hand_desired !== undefined) {
      writer.uint32(72).bool(message.left_hand_desired);
    }
    if (message.is_predicting_body_shot_fx !== undefined) {
      writer.uint32(88).bool(message.is_predicting_body_shot_fx);
    }
    if (message.is_predicting_head_shot_fx !== undefined) {
      writer.uint32(96).bool(message.is_predicting_head_shot_fx);
    }
    if (message.is_predicting_kill_ragdolls !== undefined) {
      writer.uint32(104).bool(message.is_predicting_kill_ragdolls);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CSGOUserCmdPB {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCSGOUserCmdPB();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.base = CBaseUserCmdPB.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.input_history.push(CSGOInputHistoryEntryPB.decode(reader, reader.uint32()));
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.attack1_start_history_index = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.attack2_start_history_index = reader.int32();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.left_hand_desired = reader.bool();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.is_predicting_body_shot_fx = reader.bool();
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.is_predicting_head_shot_fx = reader.bool();
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.is_predicting_kill_ragdolls = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CSGOUserCmdPB {
    return {
      base: isSet(object.base) ? CBaseUserCmdPB.fromJSON(object.base) : undefined,
      input_history: globalThis.Array.isArray(object?.inputHistory)
        ? object.inputHistory.map((e: any) => CSGOInputHistoryEntryPB.fromJSON(e))
        : globalThis.Array.isArray(object?.input_history)
        ? object.input_history.map((e: any) => CSGOInputHistoryEntryPB.fromJSON(e))
        : [],
      attack1_start_history_index: isSet(object.attack1StartHistoryIndex)
        ? globalThis.Number(object.attack1StartHistoryIndex)
        : isSet(object.attack1_start_history_index)
        ? globalThis.Number(object.attack1_start_history_index)
        : undefined,
      attack2_start_history_index: isSet(object.attack2StartHistoryIndex)
        ? globalThis.Number(object.attack2StartHistoryIndex)
        : isSet(object.attack2_start_history_index)
        ? globalThis.Number(object.attack2_start_history_index)
        : undefined,
      left_hand_desired: isSet(object.leftHandDesired)
        ? globalThis.Boolean(object.leftHandDesired)
        : isSet(object.left_hand_desired)
        ? globalThis.Boolean(object.left_hand_desired)
        : undefined,
      is_predicting_body_shot_fx: isSet(object.isPredictingBodyShotFx)
        ? globalThis.Boolean(object.isPredictingBodyShotFx)
        : isSet(object.is_predicting_body_shot_fx)
        ? globalThis.Boolean(object.is_predicting_body_shot_fx)
        : undefined,
      is_predicting_head_shot_fx: isSet(object.isPredictingHeadShotFx)
        ? globalThis.Boolean(object.isPredictingHeadShotFx)
        : isSet(object.is_predicting_head_shot_fx)
        ? globalThis.Boolean(object.is_predicting_head_shot_fx)
        : undefined,
      is_predicting_kill_ragdolls: isSet(object.isPredictingKillRagdolls)
        ? globalThis.Boolean(object.isPredictingKillRagdolls)
        : isSet(object.is_predicting_kill_ragdolls)
        ? globalThis.Boolean(object.is_predicting_kill_ragdolls)
        : undefined,
    };
  },

  toJSON(message: CSGOUserCmdPB): unknown {
    const obj: any = {};
    if (message.base !== undefined) {
      obj.base = CBaseUserCmdPB.toJSON(message.base);
    }
    if (message.input_history?.length) {
      obj.inputHistory = message.input_history.map((e) => CSGOInputHistoryEntryPB.toJSON(e));
    }
    if (message.attack1_start_history_index !== undefined) {
      obj.attack1StartHistoryIndex = Math.round(message.attack1_start_history_index);
    }
    if (message.attack2_start_history_index !== undefined) {
      obj.attack2StartHistoryIndex = Math.round(message.attack2_start_history_index);
    }
    if (message.left_hand_desired !== undefined) {
      obj.leftHandDesired = message.left_hand_desired;
    }
    if (message.is_predicting_body_shot_fx !== undefined) {
      obj.isPredictingBodyShotFx = message.is_predicting_body_shot_fx;
    }
    if (message.is_predicting_head_shot_fx !== undefined) {
      obj.isPredictingHeadShotFx = message.is_predicting_head_shot_fx;
    }
    if (message.is_predicting_kill_ragdolls !== undefined) {
      obj.isPredictingKillRagdolls = message.is_predicting_kill_ragdolls;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CSGOUserCmdPB>, I>>(base?: I): CSGOUserCmdPB {
    return CSGOUserCmdPB.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CSGOUserCmdPB>, I>>(object: I): CSGOUserCmdPB {
    const message = createBaseCSGOUserCmdPB();
    message.base = (object.base !== undefined && object.base !== null)
      ? CBaseUserCmdPB.fromPartial(object.base)
      : undefined;
    message.input_history = object.input_history?.map((e) => CSGOInputHistoryEntryPB.fromPartial(e)) || [];
    message.attack1_start_history_index = object.attack1_start_history_index ?? undefined;
    message.attack2_start_history_index = object.attack2_start_history_index ?? undefined;
    message.left_hand_desired = object.left_hand_desired ?? undefined;
    message.is_predicting_body_shot_fx = object.is_predicting_body_shot_fx ?? undefined;
    message.is_predicting_head_shot_fx = object.is_predicting_head_shot_fx ?? undefined;
    message.is_predicting_kill_ragdolls = object.is_predicting_kill_ragdolls ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
