// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.1
//   protoc               v3.20.3
// source: cs_usercmd.proto

/* eslint-disable */
import * as _m0 from "protobufjs/minimal";
import { CMsgQAngle, CMsgVector } from "./networkbasetypes";
import { CBaseUserCmdPB } from "./usercmd";

export const protobufPackage = "";

export interface CSGOInterpolationInfoPB {
  srcTick?: number | undefined;
  dstTick?: number | undefined;
  frac?: number | undefined;
}

export interface CSGOInputHistoryEntryPB {
  viewAngles?: CMsgQAngle | undefined;
  renderTickCount?: number | undefined;
  renderTickFraction?: number | undefined;
  playerTickCount?: number | undefined;
  playerTickFraction?: number | undefined;
  clInterp?: CSGOInterpolationInfoPB | undefined;
  svInterp0?: CSGOInterpolationInfoPB | undefined;
  svInterp1?: CSGOInterpolationInfoPB | undefined;
  playerInterp?: CSGOInterpolationInfoPB | undefined;
  frameNumber?: number | undefined;
  targetEntIndex?: number | undefined;
  shootPosition?: CMsgVector | undefined;
  targetHeadPosCheck?: CMsgVector | undefined;
  targetAbsPosCheck?: CMsgVector | undefined;
  targetAbsAngCheck?: CMsgQAngle | undefined;
}

export interface CSGOUserCmdPB {
  base?: CBaseUserCmdPB | undefined;
  inputHistory: CSGOInputHistoryEntryPB[];
  attack1StartHistoryIndex?: number | undefined;
  attack2StartHistoryIndex?: number | undefined;
  attack3StartHistoryIndex?: number | undefined;
  leftHandDesired?: boolean | undefined;
}

function createBaseCSGOInterpolationInfoPB(): CSGOInterpolationInfoPB {
  return { srcTick: -1, dstTick: -1, frac: 0 };
}

export const CSGOInterpolationInfoPB = {
  encode(message: CSGOInterpolationInfoPB, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.srcTick !== undefined && message.srcTick !== -1) {
      writer.uint32(8).int32(message.srcTick);
    }
    if (message.dstTick !== undefined && message.dstTick !== -1) {
      writer.uint32(16).int32(message.dstTick);
    }
    if (message.frac !== undefined && message.frac !== 0) {
      writer.uint32(29).float(message.frac);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CSGOInterpolationInfoPB {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCSGOInterpolationInfoPB();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.srcTick = reader.int32();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.dstTick = reader.int32();
          continue;
        case 3:
          if (tag !== 29) {
            break;
          }

          message.frac = reader.float();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CSGOInterpolationInfoPB {
    return {
      srcTick: isSet(object.srcTick) ? globalThis.Number(object.srcTick) : -1,
      dstTick: isSet(object.dstTick) ? globalThis.Number(object.dstTick) : -1,
      frac: isSet(object.frac) ? globalThis.Number(object.frac) : 0,
    };
  },

  toJSON(message: CSGOInterpolationInfoPB): unknown {
    const obj: any = {};
    if (message.srcTick !== undefined && message.srcTick !== -1) {
      obj.srcTick = Math.round(message.srcTick);
    }
    if (message.dstTick !== undefined && message.dstTick !== -1) {
      obj.dstTick = Math.round(message.dstTick);
    }
    if (message.frac !== undefined && message.frac !== 0) {
      obj.frac = message.frac;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CSGOInterpolationInfoPB>, I>>(base?: I): CSGOInterpolationInfoPB {
    return CSGOInterpolationInfoPB.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CSGOInterpolationInfoPB>, I>>(object: I): CSGOInterpolationInfoPB {
    const message = createBaseCSGOInterpolationInfoPB();
    message.srcTick = object.srcTick ?? -1;
    message.dstTick = object.dstTick ?? -1;
    message.frac = object.frac ?? 0;
    return message;
  },
};

function createBaseCSGOInputHistoryEntryPB(): CSGOInputHistoryEntryPB {
  return {
    viewAngles: undefined,
    renderTickCount: 0,
    renderTickFraction: 0,
    playerTickCount: 0,
    playerTickFraction: 0,
    clInterp: undefined,
    svInterp0: undefined,
    svInterp1: undefined,
    playerInterp: undefined,
    frameNumber: 0,
    targetEntIndex: -1,
    shootPosition: undefined,
    targetHeadPosCheck: undefined,
    targetAbsPosCheck: undefined,
    targetAbsAngCheck: undefined,
  };
}

export const CSGOInputHistoryEntryPB = {
  encode(message: CSGOInputHistoryEntryPB, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.viewAngles !== undefined) {
      CMsgQAngle.encode(message.viewAngles, writer.uint32(18).fork()).ldelim();
    }
    if (message.renderTickCount !== undefined && message.renderTickCount !== 0) {
      writer.uint32(32).int32(message.renderTickCount);
    }
    if (message.renderTickFraction !== undefined && message.renderTickFraction !== 0) {
      writer.uint32(45).float(message.renderTickFraction);
    }
    if (message.playerTickCount !== undefined && message.playerTickCount !== 0) {
      writer.uint32(48).int32(message.playerTickCount);
    }
    if (message.playerTickFraction !== undefined && message.playerTickFraction !== 0) {
      writer.uint32(61).float(message.playerTickFraction);
    }
    if (message.clInterp !== undefined) {
      CSGOInterpolationInfoPB.encode(message.clInterp, writer.uint32(98).fork()).ldelim();
    }
    if (message.svInterp0 !== undefined) {
      CSGOInterpolationInfoPB.encode(message.svInterp0, writer.uint32(106).fork()).ldelim();
    }
    if (message.svInterp1 !== undefined) {
      CSGOInterpolationInfoPB.encode(message.svInterp1, writer.uint32(114).fork()).ldelim();
    }
    if (message.playerInterp !== undefined) {
      CSGOInterpolationInfoPB.encode(message.playerInterp, writer.uint32(122).fork()).ldelim();
    }
    if (message.frameNumber !== undefined && message.frameNumber !== 0) {
      writer.uint32(160).int32(message.frameNumber);
    }
    if (message.targetEntIndex !== undefined && message.targetEntIndex !== -1) {
      writer.uint32(64).int32(message.targetEntIndex);
    }
    if (message.shootPosition !== undefined) {
      CMsgVector.encode(message.shootPosition, writer.uint32(26).fork()).ldelim();
    }
    if (message.targetHeadPosCheck !== undefined) {
      CMsgVector.encode(message.targetHeadPosCheck, writer.uint32(74).fork()).ldelim();
    }
    if (message.targetAbsPosCheck !== undefined) {
      CMsgVector.encode(message.targetAbsPosCheck, writer.uint32(82).fork()).ldelim();
    }
    if (message.targetAbsAngCheck !== undefined) {
      CMsgQAngle.encode(message.targetAbsAngCheck, writer.uint32(90).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CSGOInputHistoryEntryPB {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCSGOInputHistoryEntryPB();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2:
          if (tag !== 18) {
            break;
          }

          message.viewAngles = CMsgQAngle.decode(reader, reader.uint32());
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.renderTickCount = reader.int32();
          continue;
        case 5:
          if (tag !== 45) {
            break;
          }

          message.renderTickFraction = reader.float();
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.playerTickCount = reader.int32();
          continue;
        case 7:
          if (tag !== 61) {
            break;
          }

          message.playerTickFraction = reader.float();
          continue;
        case 12:
          if (tag !== 98) {
            break;
          }

          message.clInterp = CSGOInterpolationInfoPB.decode(reader, reader.uint32());
          continue;
        case 13:
          if (tag !== 106) {
            break;
          }

          message.svInterp0 = CSGOInterpolationInfoPB.decode(reader, reader.uint32());
          continue;
        case 14:
          if (tag !== 114) {
            break;
          }

          message.svInterp1 = CSGOInterpolationInfoPB.decode(reader, reader.uint32());
          continue;
        case 15:
          if (tag !== 122) {
            break;
          }

          message.playerInterp = CSGOInterpolationInfoPB.decode(reader, reader.uint32());
          continue;
        case 20:
          if (tag !== 160) {
            break;
          }

          message.frameNumber = reader.int32();
          continue;
        case 8:
          if (tag !== 64) {
            break;
          }

          message.targetEntIndex = reader.int32();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.shootPosition = CMsgVector.decode(reader, reader.uint32());
          continue;
        case 9:
          if (tag !== 74) {
            break;
          }

          message.targetHeadPosCheck = CMsgVector.decode(reader, reader.uint32());
          continue;
        case 10:
          if (tag !== 82) {
            break;
          }

          message.targetAbsPosCheck = CMsgVector.decode(reader, reader.uint32());
          continue;
        case 11:
          if (tag !== 90) {
            break;
          }

          message.targetAbsAngCheck = CMsgQAngle.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CSGOInputHistoryEntryPB {
    return {
      viewAngles: isSet(object.viewAngles) ? CMsgQAngle.fromJSON(object.viewAngles) : undefined,
      renderTickCount: isSet(object.renderTickCount) ? globalThis.Number(object.renderTickCount) : 0,
      renderTickFraction: isSet(object.renderTickFraction) ? globalThis.Number(object.renderTickFraction) : 0,
      playerTickCount: isSet(object.playerTickCount) ? globalThis.Number(object.playerTickCount) : 0,
      playerTickFraction: isSet(object.playerTickFraction) ? globalThis.Number(object.playerTickFraction) : 0,
      clInterp: isSet(object.clInterp) ? CSGOInterpolationInfoPB.fromJSON(object.clInterp) : undefined,
      svInterp0: isSet(object.svInterp0) ? CSGOInterpolationInfoPB.fromJSON(object.svInterp0) : undefined,
      svInterp1: isSet(object.svInterp1) ? CSGOInterpolationInfoPB.fromJSON(object.svInterp1) : undefined,
      playerInterp: isSet(object.playerInterp) ? CSGOInterpolationInfoPB.fromJSON(object.playerInterp) : undefined,
      frameNumber: isSet(object.frameNumber) ? globalThis.Number(object.frameNumber) : 0,
      targetEntIndex: isSet(object.targetEntIndex) ? globalThis.Number(object.targetEntIndex) : -1,
      shootPosition: isSet(object.shootPosition) ? CMsgVector.fromJSON(object.shootPosition) : undefined,
      targetHeadPosCheck: isSet(object.targetHeadPosCheck) ? CMsgVector.fromJSON(object.targetHeadPosCheck) : undefined,
      targetAbsPosCheck: isSet(object.targetAbsPosCheck) ? CMsgVector.fromJSON(object.targetAbsPosCheck) : undefined,
      targetAbsAngCheck: isSet(object.targetAbsAngCheck) ? CMsgQAngle.fromJSON(object.targetAbsAngCheck) : undefined,
    };
  },

  toJSON(message: CSGOInputHistoryEntryPB): unknown {
    const obj: any = {};
    if (message.viewAngles !== undefined) {
      obj.viewAngles = CMsgQAngle.toJSON(message.viewAngles);
    }
    if (message.renderTickCount !== undefined && message.renderTickCount !== 0) {
      obj.renderTickCount = Math.round(message.renderTickCount);
    }
    if (message.renderTickFraction !== undefined && message.renderTickFraction !== 0) {
      obj.renderTickFraction = message.renderTickFraction;
    }
    if (message.playerTickCount !== undefined && message.playerTickCount !== 0) {
      obj.playerTickCount = Math.round(message.playerTickCount);
    }
    if (message.playerTickFraction !== undefined && message.playerTickFraction !== 0) {
      obj.playerTickFraction = message.playerTickFraction;
    }
    if (message.clInterp !== undefined) {
      obj.clInterp = CSGOInterpolationInfoPB.toJSON(message.clInterp);
    }
    if (message.svInterp0 !== undefined) {
      obj.svInterp0 = CSGOInterpolationInfoPB.toJSON(message.svInterp0);
    }
    if (message.svInterp1 !== undefined) {
      obj.svInterp1 = CSGOInterpolationInfoPB.toJSON(message.svInterp1);
    }
    if (message.playerInterp !== undefined) {
      obj.playerInterp = CSGOInterpolationInfoPB.toJSON(message.playerInterp);
    }
    if (message.frameNumber !== undefined && message.frameNumber !== 0) {
      obj.frameNumber = Math.round(message.frameNumber);
    }
    if (message.targetEntIndex !== undefined && message.targetEntIndex !== -1) {
      obj.targetEntIndex = Math.round(message.targetEntIndex);
    }
    if (message.shootPosition !== undefined) {
      obj.shootPosition = CMsgVector.toJSON(message.shootPosition);
    }
    if (message.targetHeadPosCheck !== undefined) {
      obj.targetHeadPosCheck = CMsgVector.toJSON(message.targetHeadPosCheck);
    }
    if (message.targetAbsPosCheck !== undefined) {
      obj.targetAbsPosCheck = CMsgVector.toJSON(message.targetAbsPosCheck);
    }
    if (message.targetAbsAngCheck !== undefined) {
      obj.targetAbsAngCheck = CMsgQAngle.toJSON(message.targetAbsAngCheck);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CSGOInputHistoryEntryPB>, I>>(base?: I): CSGOInputHistoryEntryPB {
    return CSGOInputHistoryEntryPB.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CSGOInputHistoryEntryPB>, I>>(object: I): CSGOInputHistoryEntryPB {
    const message = createBaseCSGOInputHistoryEntryPB();
    message.viewAngles = (object.viewAngles !== undefined && object.viewAngles !== null)
      ? CMsgQAngle.fromPartial(object.viewAngles)
      : undefined;
    message.renderTickCount = object.renderTickCount ?? 0;
    message.renderTickFraction = object.renderTickFraction ?? 0;
    message.playerTickCount = object.playerTickCount ?? 0;
    message.playerTickFraction = object.playerTickFraction ?? 0;
    message.clInterp = (object.clInterp !== undefined && object.clInterp !== null)
      ? CSGOInterpolationInfoPB.fromPartial(object.clInterp)
      : undefined;
    message.svInterp0 = (object.svInterp0 !== undefined && object.svInterp0 !== null)
      ? CSGOInterpolationInfoPB.fromPartial(object.svInterp0)
      : undefined;
    message.svInterp1 = (object.svInterp1 !== undefined && object.svInterp1 !== null)
      ? CSGOInterpolationInfoPB.fromPartial(object.svInterp1)
      : undefined;
    message.playerInterp = (object.playerInterp !== undefined && object.playerInterp !== null)
      ? CSGOInterpolationInfoPB.fromPartial(object.playerInterp)
      : undefined;
    message.frameNumber = object.frameNumber ?? 0;
    message.targetEntIndex = object.targetEntIndex ?? -1;
    message.shootPosition = (object.shootPosition !== undefined && object.shootPosition !== null)
      ? CMsgVector.fromPartial(object.shootPosition)
      : undefined;
    message.targetHeadPosCheck = (object.targetHeadPosCheck !== undefined && object.targetHeadPosCheck !== null)
      ? CMsgVector.fromPartial(object.targetHeadPosCheck)
      : undefined;
    message.targetAbsPosCheck = (object.targetAbsPosCheck !== undefined && object.targetAbsPosCheck !== null)
      ? CMsgVector.fromPartial(object.targetAbsPosCheck)
      : undefined;
    message.targetAbsAngCheck = (object.targetAbsAngCheck !== undefined && object.targetAbsAngCheck !== null)
      ? CMsgQAngle.fromPartial(object.targetAbsAngCheck)
      : undefined;
    return message;
  },
};

function createBaseCSGOUserCmdPB(): CSGOUserCmdPB {
  return {
    base: undefined,
    inputHistory: [],
    attack1StartHistoryIndex: -1,
    attack2StartHistoryIndex: -1,
    attack3StartHistoryIndex: -1,
    leftHandDesired: false,
  };
}

export const CSGOUserCmdPB = {
  encode(message: CSGOUserCmdPB, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.base !== undefined) {
      CBaseUserCmdPB.encode(message.base, writer.uint32(10).fork()).ldelim();
    }
    for (const v of message.inputHistory) {
      CSGOInputHistoryEntryPB.encode(v!, writer.uint32(18).fork()).ldelim();
    }
    if (message.attack1StartHistoryIndex !== undefined && message.attack1StartHistoryIndex !== -1) {
      writer.uint32(48).int32(message.attack1StartHistoryIndex);
    }
    if (message.attack2StartHistoryIndex !== undefined && message.attack2StartHistoryIndex !== -1) {
      writer.uint32(56).int32(message.attack2StartHistoryIndex);
    }
    if (message.attack3StartHistoryIndex !== undefined && message.attack3StartHistoryIndex !== -1) {
      writer.uint32(64).int32(message.attack3StartHistoryIndex);
    }
    if (message.leftHandDesired !== undefined && message.leftHandDesired !== false) {
      writer.uint32(72).bool(message.leftHandDesired);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CSGOUserCmdPB {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCSGOUserCmdPB();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.base = CBaseUserCmdPB.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.inputHistory.push(CSGOInputHistoryEntryPB.decode(reader, reader.uint32()));
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.attack1StartHistoryIndex = reader.int32();
          continue;
        case 7:
          if (tag !== 56) {
            break;
          }

          message.attack2StartHistoryIndex = reader.int32();
          continue;
        case 8:
          if (tag !== 64) {
            break;
          }

          message.attack3StartHistoryIndex = reader.int32();
          continue;
        case 9:
          if (tag !== 72) {
            break;
          }

          message.leftHandDesired = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CSGOUserCmdPB {
    return {
      base: isSet(object.base) ? CBaseUserCmdPB.fromJSON(object.base) : undefined,
      inputHistory: globalThis.Array.isArray(object?.inputHistory)
        ? object.inputHistory.map((e: any) => CSGOInputHistoryEntryPB.fromJSON(e))
        : [],
      attack1StartHistoryIndex: isSet(object.attack1StartHistoryIndex)
        ? globalThis.Number(object.attack1StartHistoryIndex)
        : -1,
      attack2StartHistoryIndex: isSet(object.attack2StartHistoryIndex)
        ? globalThis.Number(object.attack2StartHistoryIndex)
        : -1,
      attack3StartHistoryIndex: isSet(object.attack3StartHistoryIndex)
        ? globalThis.Number(object.attack3StartHistoryIndex)
        : -1,
      leftHandDesired: isSet(object.leftHandDesired) ? globalThis.Boolean(object.leftHandDesired) : false,
    };
  },

  toJSON(message: CSGOUserCmdPB): unknown {
    const obj: any = {};
    if (message.base !== undefined) {
      obj.base = CBaseUserCmdPB.toJSON(message.base);
    }
    if (message.inputHistory?.length) {
      obj.inputHistory = message.inputHistory.map((e) => CSGOInputHistoryEntryPB.toJSON(e));
    }
    if (message.attack1StartHistoryIndex !== undefined && message.attack1StartHistoryIndex !== -1) {
      obj.attack1StartHistoryIndex = Math.round(message.attack1StartHistoryIndex);
    }
    if (message.attack2StartHistoryIndex !== undefined && message.attack2StartHistoryIndex !== -1) {
      obj.attack2StartHistoryIndex = Math.round(message.attack2StartHistoryIndex);
    }
    if (message.attack3StartHistoryIndex !== undefined && message.attack3StartHistoryIndex !== -1) {
      obj.attack3StartHistoryIndex = Math.round(message.attack3StartHistoryIndex);
    }
    if (message.leftHandDesired !== undefined && message.leftHandDesired !== false) {
      obj.leftHandDesired = message.leftHandDesired;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CSGOUserCmdPB>, I>>(base?: I): CSGOUserCmdPB {
    return CSGOUserCmdPB.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CSGOUserCmdPB>, I>>(object: I): CSGOUserCmdPB {
    const message = createBaseCSGOUserCmdPB();
    message.base = (object.base !== undefined && object.base !== null)
      ? CBaseUserCmdPB.fromPartial(object.base)
      : undefined;
    message.inputHistory = object.inputHistory?.map((e) => CSGOInputHistoryEntryPB.fromPartial(e)) || [];
    message.attack1StartHistoryIndex = object.attack1StartHistoryIndex ?? -1;
    message.attack2StartHistoryIndex = object.attack2StartHistoryIndex ?? -1;
    message.attack3StartHistoryIndex = object.attack3StartHistoryIndex ?? -1;
    message.leftHandDesired = object.leftHandDesired ?? false;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
