// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.1
// source: engine_gcmessages.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "";

export interface CEngineGotvSyncPacket {
  match_id?: string | undefined;
  instance_id?: number | undefined;
  signupfragment?: number | undefined;
  currentfragment?: number | undefined;
  tickrate?: number | undefined;
  tick?: number | undefined;
  rtdelay?: number | undefined;
  rcvage?: number | undefined;
  keyframe_interval?: number | undefined;
  cdndelay?: number | undefined;
}

function createBaseCEngineGotvSyncPacket(): CEngineGotvSyncPacket {
  return {
    match_id: undefined,
    instance_id: undefined,
    signupfragment: undefined,
    currentfragment: undefined,
    tickrate: undefined,
    tick: undefined,
    rtdelay: undefined,
    rcvage: undefined,
    keyframe_interval: undefined,
    cdndelay: undefined,
  };
}

export const CEngineGotvSyncPacket: MessageFns<CEngineGotvSyncPacket> = {
  encode(message: CEngineGotvSyncPacket, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.match_id !== undefined) {
      writer.uint32(8).uint64(message.match_id);
    }
    if (message.instance_id !== undefined) {
      writer.uint32(16).uint32(message.instance_id);
    }
    if (message.signupfragment !== undefined) {
      writer.uint32(24).uint32(message.signupfragment);
    }
    if (message.currentfragment !== undefined) {
      writer.uint32(32).uint32(message.currentfragment);
    }
    if (message.tickrate !== undefined) {
      writer.uint32(45).float(message.tickrate);
    }
    if (message.tick !== undefined) {
      writer.uint32(48).uint32(message.tick);
    }
    if (message.rtdelay !== undefined) {
      writer.uint32(69).float(message.rtdelay);
    }
    if (message.rcvage !== undefined) {
      writer.uint32(77).float(message.rcvage);
    }
    if (message.keyframe_interval !== undefined) {
      writer.uint32(85).float(message.keyframe_interval);
    }
    if (message.cdndelay !== undefined) {
      writer.uint32(88).uint32(message.cdndelay);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CEngineGotvSyncPacket {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCEngineGotvSyncPacket();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.match_id = reader.uint64().toString();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.instance_id = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.signupfragment = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.currentfragment = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 45) {
            break;
          }

          message.tickrate = reader.float();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.tick = reader.uint32();
          continue;
        }
        case 8: {
          if (tag !== 69) {
            break;
          }

          message.rtdelay = reader.float();
          continue;
        }
        case 9: {
          if (tag !== 77) {
            break;
          }

          message.rcvage = reader.float();
          continue;
        }
        case 10: {
          if (tag !== 85) {
            break;
          }

          message.keyframe_interval = reader.float();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.cdndelay = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CEngineGotvSyncPacket {
    return {
      match_id: isSet(object.matchId)
        ? globalThis.String(object.matchId)
        : isSet(object.match_id)
        ? globalThis.String(object.match_id)
        : undefined,
      instance_id: isSet(object.instanceId)
        ? globalThis.Number(object.instanceId)
        : isSet(object.instance_id)
        ? globalThis.Number(object.instance_id)
        : undefined,
      signupfragment: isSet(object.signupfragment) ? globalThis.Number(object.signupfragment) : undefined,
      currentfragment: isSet(object.currentfragment) ? globalThis.Number(object.currentfragment) : undefined,
      tickrate: isSet(object.tickrate) ? globalThis.Number(object.tickrate) : undefined,
      tick: isSet(object.tick) ? globalThis.Number(object.tick) : undefined,
      rtdelay: isSet(object.rtdelay) ? globalThis.Number(object.rtdelay) : undefined,
      rcvage: isSet(object.rcvage) ? globalThis.Number(object.rcvage) : undefined,
      keyframe_interval: isSet(object.keyframeInterval)
        ? globalThis.Number(object.keyframeInterval)
        : isSet(object.keyframe_interval)
        ? globalThis.Number(object.keyframe_interval)
        : undefined,
      cdndelay: isSet(object.cdndelay) ? globalThis.Number(object.cdndelay) : undefined,
    };
  },

  toJSON(message: CEngineGotvSyncPacket): unknown {
    const obj: any = {};
    if (message.match_id !== undefined) {
      obj.matchId = message.match_id;
    }
    if (message.instance_id !== undefined) {
      obj.instanceId = Math.round(message.instance_id);
    }
    if (message.signupfragment !== undefined) {
      obj.signupfragment = Math.round(message.signupfragment);
    }
    if (message.currentfragment !== undefined) {
      obj.currentfragment = Math.round(message.currentfragment);
    }
    if (message.tickrate !== undefined) {
      obj.tickrate = message.tickrate;
    }
    if (message.tick !== undefined) {
      obj.tick = Math.round(message.tick);
    }
    if (message.rtdelay !== undefined) {
      obj.rtdelay = message.rtdelay;
    }
    if (message.rcvage !== undefined) {
      obj.rcvage = message.rcvage;
    }
    if (message.keyframe_interval !== undefined) {
      obj.keyframeInterval = message.keyframe_interval;
    }
    if (message.cdndelay !== undefined) {
      obj.cdndelay = Math.round(message.cdndelay);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CEngineGotvSyncPacket>, I>>(base?: I): CEngineGotvSyncPacket {
    return CEngineGotvSyncPacket.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CEngineGotvSyncPacket>, I>>(object: I): CEngineGotvSyncPacket {
    const message = createBaseCEngineGotvSyncPacket();
    message.match_id = object.match_id ?? undefined;
    message.instance_id = object.instance_id ?? undefined;
    message.signupfragment = object.signupfragment ?? undefined;
    message.currentfragment = object.currentfragment ?? undefined;
    message.tickrate = object.tickrate ?? undefined;
    message.tick = object.tick ?? undefined;
    message.rtdelay = object.rtdelay ?? undefined;
    message.rcvage = object.rcvage ?? undefined;
    message.keyframe_interval = object.keyframe_interval ?? undefined;
    message.cdndelay = object.cdndelay ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
