// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.1
// source: fatdemo.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { CMsgQAngle, CMsgVector } from "./networkbasetypes.js";

export const protobufPackage = "";

export const EHitGroup = {
  EHG_Generic: 0,
  EHG_Head: 1,
  EHG_Chest: 2,
  EHG_Stomach: 3,
  EHG_LeftArm: 4,
  EHG_RightArm: 5,
  EHG_LeftLeg: 6,
  EHG_RightLeg: 7,
  EHG_Gear: 8,
  EHG_Miss: 9,
  UNRECOGNIZED: -1,
} as const;

export type EHitGroup = typeof EHitGroup[keyof typeof EHitGroup];

export namespace EHitGroup {
  export type EHG_Generic = typeof EHitGroup.EHG_Generic;
  export type EHG_Head = typeof EHitGroup.EHG_Head;
  export type EHG_Chest = typeof EHitGroup.EHG_Chest;
  export type EHG_Stomach = typeof EHitGroup.EHG_Stomach;
  export type EHG_LeftArm = typeof EHitGroup.EHG_LeftArm;
  export type EHG_RightArm = typeof EHitGroup.EHG_RightArm;
  export type EHG_LeftLeg = typeof EHitGroup.EHG_LeftLeg;
  export type EHG_RightLeg = typeof EHitGroup.EHG_RightLeg;
  export type EHG_Gear = typeof EHitGroup.EHG_Gear;
  export type EHG_Miss = typeof EHitGroup.EHG_Miss;
  export type UNRECOGNIZED = typeof EHitGroup.UNRECOGNIZED;
}

export function eHitGroupFromJSON(object: any): EHitGroup {
  switch (object) {
    case 0:
    case "EHG_Generic":
      return EHitGroup.EHG_Generic;
    case 1:
    case "EHG_Head":
      return EHitGroup.EHG_Head;
    case 2:
    case "EHG_Chest":
      return EHitGroup.EHG_Chest;
    case 3:
    case "EHG_Stomach":
      return EHitGroup.EHG_Stomach;
    case 4:
    case "EHG_LeftArm":
      return EHitGroup.EHG_LeftArm;
    case 5:
    case "EHG_RightArm":
      return EHitGroup.EHG_RightArm;
    case 6:
    case "EHG_LeftLeg":
      return EHitGroup.EHG_LeftLeg;
    case 7:
    case "EHG_RightLeg":
      return EHitGroup.EHG_RightLeg;
    case 8:
    case "EHG_Gear":
      return EHitGroup.EHG_Gear;
    case 9:
    case "EHG_Miss":
      return EHitGroup.EHG_Miss;
    case -1:
    case "UNRECOGNIZED":
    default:
      return EHitGroup.UNRECOGNIZED;
  }
}

export function eHitGroupToJSON(object: EHitGroup): string {
  switch (object) {
    case EHitGroup.EHG_Generic:
      return "EHG_Generic";
    case EHitGroup.EHG_Head:
      return "EHG_Head";
    case EHitGroup.EHG_Chest:
      return "EHG_Chest";
    case EHitGroup.EHG_Stomach:
      return "EHG_Stomach";
    case EHitGroup.EHG_LeftArm:
      return "EHG_LeftArm";
    case EHitGroup.EHG_RightArm:
      return "EHG_RightArm";
    case EHitGroup.EHG_LeftLeg:
      return "EHG_LeftLeg";
    case EHitGroup.EHG_RightLeg:
      return "EHG_RightLeg";
    case EHitGroup.EHG_Gear:
      return "EHG_Gear";
    case EHitGroup.EHG_Miss:
      return "EHG_Miss";
    case EHitGroup.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export const ETeam = { ET_Unknown: 0, ET_Spectator: 1, ET_Terrorist: 2, ET_CT: 3, UNRECOGNIZED: -1 } as const;

export type ETeam = typeof ETeam[keyof typeof ETeam];

export namespace ETeam {
  export type ET_Unknown = typeof ETeam.ET_Unknown;
  export type ET_Spectator = typeof ETeam.ET_Spectator;
  export type ET_Terrorist = typeof ETeam.ET_Terrorist;
  export type ET_CT = typeof ETeam.ET_CT;
  export type UNRECOGNIZED = typeof ETeam.UNRECOGNIZED;
}

export function eTeamFromJSON(object: any): ETeam {
  switch (object) {
    case 0:
    case "ET_Unknown":
      return ETeam.ET_Unknown;
    case 1:
    case "ET_Spectator":
      return ETeam.ET_Spectator;
    case 2:
    case "ET_Terrorist":
      return ETeam.ET_Terrorist;
    case 3:
    case "ET_CT":
      return ETeam.ET_CT;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ETeam.UNRECOGNIZED;
  }
}

export function eTeamToJSON(object: ETeam): string {
  switch (object) {
    case ETeam.ET_Unknown:
      return "ET_Unknown";
    case ETeam.ET_Spectator:
      return "ET_Spectator";
    case ETeam.ET_Terrorist:
      return "ET_Terrorist";
    case ETeam.ET_CT:
      return "ET_CT";
    case ETeam.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export const EWeaponType = {
  EWT_Knife: 0,
  EWT_Pistol: 1,
  EWT_SubMachineGun: 2,
  EWT_Rifle: 3,
  EWT_Shotgun: 4,
  EWT_SniperRifle: 5,
  EWT_MachineGun: 6,
  EWT_C4: 7,
  EWT_Grenade: 8,
  EWT_Equipment: 9,
  EWT_StackableItem: 10,
  EWT_Unknown: 11,
  UNRECOGNIZED: -1,
} as const;

export type EWeaponType = typeof EWeaponType[keyof typeof EWeaponType];

export namespace EWeaponType {
  export type EWT_Knife = typeof EWeaponType.EWT_Knife;
  export type EWT_Pistol = typeof EWeaponType.EWT_Pistol;
  export type EWT_SubMachineGun = typeof EWeaponType.EWT_SubMachineGun;
  export type EWT_Rifle = typeof EWeaponType.EWT_Rifle;
  export type EWT_Shotgun = typeof EWeaponType.EWT_Shotgun;
  export type EWT_SniperRifle = typeof EWeaponType.EWT_SniperRifle;
  export type EWT_MachineGun = typeof EWeaponType.EWT_MachineGun;
  export type EWT_C4 = typeof EWeaponType.EWT_C4;
  export type EWT_Grenade = typeof EWeaponType.EWT_Grenade;
  export type EWT_Equipment = typeof EWeaponType.EWT_Equipment;
  export type EWT_StackableItem = typeof EWeaponType.EWT_StackableItem;
  export type EWT_Unknown = typeof EWeaponType.EWT_Unknown;
  export type UNRECOGNIZED = typeof EWeaponType.UNRECOGNIZED;
}

export function eWeaponTypeFromJSON(object: any): EWeaponType {
  switch (object) {
    case 0:
    case "EWT_Knife":
      return EWeaponType.EWT_Knife;
    case 1:
    case "EWT_Pistol":
      return EWeaponType.EWT_Pistol;
    case 2:
    case "EWT_SubMachineGun":
      return EWeaponType.EWT_SubMachineGun;
    case 3:
    case "EWT_Rifle":
      return EWeaponType.EWT_Rifle;
    case 4:
    case "EWT_Shotgun":
      return EWeaponType.EWT_Shotgun;
    case 5:
    case "EWT_SniperRifle":
      return EWeaponType.EWT_SniperRifle;
    case 6:
    case "EWT_MachineGun":
      return EWeaponType.EWT_MachineGun;
    case 7:
    case "EWT_C4":
      return EWeaponType.EWT_C4;
    case 8:
    case "EWT_Grenade":
      return EWeaponType.EWT_Grenade;
    case 9:
    case "EWT_Equipment":
      return EWeaponType.EWT_Equipment;
    case 10:
    case "EWT_StackableItem":
      return EWeaponType.EWT_StackableItem;
    case 11:
    case "EWT_Unknown":
      return EWeaponType.EWT_Unknown;
    case -1:
    case "UNRECOGNIZED":
    default:
      return EWeaponType.UNRECOGNIZED;
  }
}

export function eWeaponTypeToJSON(object: EWeaponType): string {
  switch (object) {
    case EWeaponType.EWT_Knife:
      return "EWT_Knife";
    case EWeaponType.EWT_Pistol:
      return "EWT_Pistol";
    case EWeaponType.EWT_SubMachineGun:
      return "EWT_SubMachineGun";
    case EWeaponType.EWT_Rifle:
      return "EWT_Rifle";
    case EWeaponType.EWT_Shotgun:
      return "EWT_Shotgun";
    case EWeaponType.EWT_SniperRifle:
      return "EWT_SniperRifle";
    case EWeaponType.EWT_MachineGun:
      return "EWT_MachineGun";
    case EWeaponType.EWT_C4:
      return "EWT_C4";
    case EWeaponType.EWT_Grenade:
      return "EWT_Grenade";
    case EWeaponType.EWT_Equipment:
      return "EWT_Equipment";
    case EWeaponType.EWT_StackableItem:
      return "EWT_StackableItem";
    case EWeaponType.EWT_Unknown:
      return "EWT_Unknown";
    case EWeaponType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface MLDict {
  key?: string | undefined;
  val_string?: string | undefined;
  val_int?: number | undefined;
  val_float?: number | undefined;
}

export interface MLEvent {
  event_name?: string | undefined;
  data: MLDict[];
}

export interface MLMatchState {
  game_mode?: string | undefined;
  phase?: string | undefined;
  round?: number | undefined;
  score_ct?: number | undefined;
  score_t?: number | undefined;
}

export interface MLRoundState {
  phase?: string | undefined;
  win_team?: ETeam | undefined;
  bomb_state?: string | undefined;
}

export interface MLWeaponState {
  index?: number | undefined;
  name?: string | undefined;
  type?: EWeaponType | undefined;
  ammo_clip?: number | undefined;
  ammo_clip_max?: number | undefined;
  ammo_reserve?: number | undefined;
  state?: string | undefined;
  recoil_index?: number | undefined;
}

export interface MLPlayerState {
  account_id?: number | undefined;
  player_slot?: number | undefined;
  entindex?: number | undefined;
  name?: string | undefined;
  clan?: string | undefined;
  team?: ETeam | undefined;
  abspos?: CMsgVector | undefined;
  eyeangle?: CMsgQAngle | undefined;
  eyeangle_fwd?: CMsgVector | undefined;
  health?: number | undefined;
  armor?: number | undefined;
  flashed?: number | undefined;
  smoked?: number | undefined;
  money?: number | undefined;
  round_kills?: number | undefined;
  round_killhs?: number | undefined;
  burning?: number | undefined;
  helmet?: boolean | undefined;
  defuse_kit?: boolean | undefined;
  weapons: MLWeaponState[];
}

export interface MLGameState {
  match?: MLMatchState | undefined;
  round?: MLRoundState | undefined;
  players: MLPlayerState[];
}

export interface MLDemoHeader {
  map_name?: string | undefined;
  tick_rate?: number | undefined;
  version?: number | undefined;
  steam_universe?: number | undefined;
}

export interface MLTick {
  tick_count?: number | undefined;
  state?: MLGameState | undefined;
  events: MLEvent[];
}

export interface VacNetShot {
  steamid_player?: string | undefined;
  round_number?: number | undefined;
  hit_type?: number | undefined;
  weapon_type?: number | undefined;
  distance_to_hurt_target?: number | undefined;
  delta_yaw_window: number[];
  delta_pitch_window: number[];
}

function createBaseMLDict(): MLDict {
  return { key: undefined, val_string: undefined, val_int: undefined, val_float: undefined };
}

export const MLDict: MessageFns<MLDict> = {
  encode(message: MLDict, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== undefined) {
      writer.uint32(10).string(message.key);
    }
    if (message.val_string !== undefined) {
      writer.uint32(18).string(message.val_string);
    }
    if (message.val_int !== undefined) {
      writer.uint32(24).int32(message.val_int);
    }
    if (message.val_float !== undefined) {
      writer.uint32(37).float(message.val_float);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MLDict {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMLDict();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.val_string = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.val_int = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 37) {
            break;
          }

          message.val_float = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MLDict {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : undefined,
      val_string: isSet(object.valString)
        ? globalThis.String(object.valString)
        : isSet(object.val_string)
        ? globalThis.String(object.val_string)
        : undefined,
      val_int: isSet(object.valInt)
        ? globalThis.Number(object.valInt)
        : isSet(object.val_int)
        ? globalThis.Number(object.val_int)
        : undefined,
      val_float: isSet(object.valFloat)
        ? globalThis.Number(object.valFloat)
        : isSet(object.val_float)
        ? globalThis.Number(object.val_float)
        : undefined,
    };
  },

  toJSON(message: MLDict): unknown {
    const obj: any = {};
    if (message.key !== undefined) {
      obj.key = message.key;
    }
    if (message.val_string !== undefined) {
      obj.valString = message.val_string;
    }
    if (message.val_int !== undefined) {
      obj.valInt = Math.round(message.val_int);
    }
    if (message.val_float !== undefined) {
      obj.valFloat = message.val_float;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MLDict>, I>>(base?: I): MLDict {
    return MLDict.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MLDict>, I>>(object: I): MLDict {
    const message = createBaseMLDict();
    message.key = object.key ?? undefined;
    message.val_string = object.val_string ?? undefined;
    message.val_int = object.val_int ?? undefined;
    message.val_float = object.val_float ?? undefined;
    return message;
  },
};

function createBaseMLEvent(): MLEvent {
  return { event_name: undefined, data: [] };
}

export const MLEvent: MessageFns<MLEvent> = {
  encode(message: MLEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.event_name !== undefined) {
      writer.uint32(10).string(message.event_name);
    }
    for (const v of message.data) {
      MLDict.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MLEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMLEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.event_name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.data.push(MLDict.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MLEvent {
    return {
      event_name: isSet(object.eventName)
        ? globalThis.String(object.eventName)
        : isSet(object.event_name)
        ? globalThis.String(object.event_name)
        : undefined,
      data: globalThis.Array.isArray(object?.data) ? object.data.map((e: any) => MLDict.fromJSON(e)) : [],
    };
  },

  toJSON(message: MLEvent): unknown {
    const obj: any = {};
    if (message.event_name !== undefined) {
      obj.eventName = message.event_name;
    }
    if (message.data?.length) {
      obj.data = message.data.map((e) => MLDict.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MLEvent>, I>>(base?: I): MLEvent {
    return MLEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MLEvent>, I>>(object: I): MLEvent {
    const message = createBaseMLEvent();
    message.event_name = object.event_name ?? undefined;
    message.data = object.data?.map((e) => MLDict.fromPartial(e)) || [];
    return message;
  },
};

function createBaseMLMatchState(): MLMatchState {
  return { game_mode: undefined, phase: undefined, round: undefined, score_ct: undefined, score_t: undefined };
}

export const MLMatchState: MessageFns<MLMatchState> = {
  encode(message: MLMatchState, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.game_mode !== undefined) {
      writer.uint32(10).string(message.game_mode);
    }
    if (message.phase !== undefined) {
      writer.uint32(18).string(message.phase);
    }
    if (message.round !== undefined) {
      writer.uint32(24).int32(message.round);
    }
    if (message.score_ct !== undefined) {
      writer.uint32(32).int32(message.score_ct);
    }
    if (message.score_t !== undefined) {
      writer.uint32(40).int32(message.score_t);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MLMatchState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMLMatchState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.game_mode = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.phase = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.round = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.score_ct = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.score_t = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MLMatchState {
    return {
      game_mode: isSet(object.gameMode)
        ? globalThis.String(object.gameMode)
        : isSet(object.game_mode)
        ? globalThis.String(object.game_mode)
        : undefined,
      phase: isSet(object.phase) ? globalThis.String(object.phase) : undefined,
      round: isSet(object.round) ? globalThis.Number(object.round) : undefined,
      score_ct: isSet(object.scoreCt)
        ? globalThis.Number(object.scoreCt)
        : isSet(object.score_ct)
        ? globalThis.Number(object.score_ct)
        : undefined,
      score_t: isSet(object.scoreT)
        ? globalThis.Number(object.scoreT)
        : isSet(object.score_t)
        ? globalThis.Number(object.score_t)
        : undefined,
    };
  },

  toJSON(message: MLMatchState): unknown {
    const obj: any = {};
    if (message.game_mode !== undefined) {
      obj.gameMode = message.game_mode;
    }
    if (message.phase !== undefined) {
      obj.phase = message.phase;
    }
    if (message.round !== undefined) {
      obj.round = Math.round(message.round);
    }
    if (message.score_ct !== undefined) {
      obj.scoreCt = Math.round(message.score_ct);
    }
    if (message.score_t !== undefined) {
      obj.scoreT = Math.round(message.score_t);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MLMatchState>, I>>(base?: I): MLMatchState {
    return MLMatchState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MLMatchState>, I>>(object: I): MLMatchState {
    const message = createBaseMLMatchState();
    message.game_mode = object.game_mode ?? undefined;
    message.phase = object.phase ?? undefined;
    message.round = object.round ?? undefined;
    message.score_ct = object.score_ct ?? undefined;
    message.score_t = object.score_t ?? undefined;
    return message;
  },
};

function createBaseMLRoundState(): MLRoundState {
  return { phase: undefined, win_team: undefined, bomb_state: undefined };
}

export const MLRoundState: MessageFns<MLRoundState> = {
  encode(message: MLRoundState, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.phase !== undefined) {
      writer.uint32(10).string(message.phase);
    }
    if (message.win_team !== undefined) {
      writer.uint32(16).int32(message.win_team);
    }
    if (message.bomb_state !== undefined) {
      writer.uint32(26).string(message.bomb_state);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MLRoundState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMLRoundState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.phase = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.win_team = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.bomb_state = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MLRoundState {
    return {
      phase: isSet(object.phase) ? globalThis.String(object.phase) : undefined,
      win_team: isSet(object.winTeam)
        ? eTeamFromJSON(object.winTeam)
        : isSet(object.win_team)
        ? eTeamFromJSON(object.win_team)
        : undefined,
      bomb_state: isSet(object.bombState)
        ? globalThis.String(object.bombState)
        : isSet(object.bomb_state)
        ? globalThis.String(object.bomb_state)
        : undefined,
    };
  },

  toJSON(message: MLRoundState): unknown {
    const obj: any = {};
    if (message.phase !== undefined) {
      obj.phase = message.phase;
    }
    if (message.win_team !== undefined) {
      obj.winTeam = eTeamToJSON(message.win_team);
    }
    if (message.bomb_state !== undefined) {
      obj.bombState = message.bomb_state;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MLRoundState>, I>>(base?: I): MLRoundState {
    return MLRoundState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MLRoundState>, I>>(object: I): MLRoundState {
    const message = createBaseMLRoundState();
    message.phase = object.phase ?? undefined;
    message.win_team = object.win_team ?? undefined;
    message.bomb_state = object.bomb_state ?? undefined;
    return message;
  },
};

function createBaseMLWeaponState(): MLWeaponState {
  return {
    index: undefined,
    name: undefined,
    type: undefined,
    ammo_clip: undefined,
    ammo_clip_max: undefined,
    ammo_reserve: undefined,
    state: undefined,
    recoil_index: undefined,
  };
}

export const MLWeaponState: MessageFns<MLWeaponState> = {
  encode(message: MLWeaponState, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.index !== undefined) {
      writer.uint32(8).int32(message.index);
    }
    if (message.name !== undefined) {
      writer.uint32(18).string(message.name);
    }
    if (message.type !== undefined) {
      writer.uint32(24).int32(message.type);
    }
    if (message.ammo_clip !== undefined) {
      writer.uint32(32).int32(message.ammo_clip);
    }
    if (message.ammo_clip_max !== undefined) {
      writer.uint32(40).int32(message.ammo_clip_max);
    }
    if (message.ammo_reserve !== undefined) {
      writer.uint32(48).int32(message.ammo_reserve);
    }
    if (message.state !== undefined) {
      writer.uint32(58).string(message.state);
    }
    if (message.recoil_index !== undefined) {
      writer.uint32(69).float(message.recoil_index);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MLWeaponState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMLWeaponState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.index = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.ammo_clip = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.ammo_clip_max = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.ammo_reserve = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.state = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 69) {
            break;
          }

          message.recoil_index = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MLWeaponState {
    return {
      index: isSet(object.index) ? globalThis.Number(object.index) : undefined,
      name: isSet(object.name) ? globalThis.String(object.name) : undefined,
      type: isSet(object.type) ? eWeaponTypeFromJSON(object.type) : undefined,
      ammo_clip: isSet(object.ammoClip)
        ? globalThis.Number(object.ammoClip)
        : isSet(object.ammo_clip)
        ? globalThis.Number(object.ammo_clip)
        : undefined,
      ammo_clip_max: isSet(object.ammoClipMax)
        ? globalThis.Number(object.ammoClipMax)
        : isSet(object.ammo_clip_max)
        ? globalThis.Number(object.ammo_clip_max)
        : undefined,
      ammo_reserve: isSet(object.ammoReserve)
        ? globalThis.Number(object.ammoReserve)
        : isSet(object.ammo_reserve)
        ? globalThis.Number(object.ammo_reserve)
        : undefined,
      state: isSet(object.state) ? globalThis.String(object.state) : undefined,
      recoil_index: isSet(object.recoilIndex)
        ? globalThis.Number(object.recoilIndex)
        : isSet(object.recoil_index)
        ? globalThis.Number(object.recoil_index)
        : undefined,
    };
  },

  toJSON(message: MLWeaponState): unknown {
    const obj: any = {};
    if (message.index !== undefined) {
      obj.index = Math.round(message.index);
    }
    if (message.name !== undefined) {
      obj.name = message.name;
    }
    if (message.type !== undefined) {
      obj.type = eWeaponTypeToJSON(message.type);
    }
    if (message.ammo_clip !== undefined) {
      obj.ammoClip = Math.round(message.ammo_clip);
    }
    if (message.ammo_clip_max !== undefined) {
      obj.ammoClipMax = Math.round(message.ammo_clip_max);
    }
    if (message.ammo_reserve !== undefined) {
      obj.ammoReserve = Math.round(message.ammo_reserve);
    }
    if (message.state !== undefined) {
      obj.state = message.state;
    }
    if (message.recoil_index !== undefined) {
      obj.recoilIndex = message.recoil_index;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MLWeaponState>, I>>(base?: I): MLWeaponState {
    return MLWeaponState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MLWeaponState>, I>>(object: I): MLWeaponState {
    const message = createBaseMLWeaponState();
    message.index = object.index ?? undefined;
    message.name = object.name ?? undefined;
    message.type = object.type ?? undefined;
    message.ammo_clip = object.ammo_clip ?? undefined;
    message.ammo_clip_max = object.ammo_clip_max ?? undefined;
    message.ammo_reserve = object.ammo_reserve ?? undefined;
    message.state = object.state ?? undefined;
    message.recoil_index = object.recoil_index ?? undefined;
    return message;
  },
};

function createBaseMLPlayerState(): MLPlayerState {
  return {
    account_id: undefined,
    player_slot: undefined,
    entindex: undefined,
    name: undefined,
    clan: undefined,
    team: undefined,
    abspos: undefined,
    eyeangle: undefined,
    eyeangle_fwd: undefined,
    health: undefined,
    armor: undefined,
    flashed: undefined,
    smoked: undefined,
    money: undefined,
    round_kills: undefined,
    round_killhs: undefined,
    burning: undefined,
    helmet: undefined,
    defuse_kit: undefined,
    weapons: [],
  };
}

export const MLPlayerState: MessageFns<MLPlayerState> = {
  encode(message: MLPlayerState, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.account_id !== undefined) {
      writer.uint32(8).int32(message.account_id);
    }
    if (message.player_slot !== undefined) {
      writer.uint32(16).int32(message.player_slot);
    }
    if (message.entindex !== undefined) {
      writer.uint32(24).int32(message.entindex);
    }
    if (message.name !== undefined) {
      writer.uint32(34).string(message.name);
    }
    if (message.clan !== undefined) {
      writer.uint32(42).string(message.clan);
    }
    if (message.team !== undefined) {
      writer.uint32(48).int32(message.team);
    }
    if (message.abspos !== undefined) {
      CMsgVector.encode(message.abspos, writer.uint32(58).fork()).join();
    }
    if (message.eyeangle !== undefined) {
      CMsgQAngle.encode(message.eyeangle, writer.uint32(66).fork()).join();
    }
    if (message.eyeangle_fwd !== undefined) {
      CMsgVector.encode(message.eyeangle_fwd, writer.uint32(74).fork()).join();
    }
    if (message.health !== undefined) {
      writer.uint32(80).int32(message.health);
    }
    if (message.armor !== undefined) {
      writer.uint32(88).int32(message.armor);
    }
    if (message.flashed !== undefined) {
      writer.uint32(101).float(message.flashed);
    }
    if (message.smoked !== undefined) {
      writer.uint32(109).float(message.smoked);
    }
    if (message.money !== undefined) {
      writer.uint32(112).int32(message.money);
    }
    if (message.round_kills !== undefined) {
      writer.uint32(120).int32(message.round_kills);
    }
    if (message.round_killhs !== undefined) {
      writer.uint32(128).int32(message.round_killhs);
    }
    if (message.burning !== undefined) {
      writer.uint32(141).float(message.burning);
    }
    if (message.helmet !== undefined) {
      writer.uint32(144).bool(message.helmet);
    }
    if (message.defuse_kit !== undefined) {
      writer.uint32(152).bool(message.defuse_kit);
    }
    for (const v of message.weapons) {
      MLWeaponState.encode(v!, writer.uint32(162).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MLPlayerState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMLPlayerState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.account_id = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.player_slot = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.entindex = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.clan = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.team = reader.int32() as any;
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.abspos = CMsgVector.decode(reader, reader.uint32());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.eyeangle = CMsgQAngle.decode(reader, reader.uint32());
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.eyeangle_fwd = CMsgVector.decode(reader, reader.uint32());
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.health = reader.int32();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.armor = reader.int32();
          continue;
        }
        case 12: {
          if (tag !== 101) {
            break;
          }

          message.flashed = reader.float();
          continue;
        }
        case 13: {
          if (tag !== 109) {
            break;
          }

          message.smoked = reader.float();
          continue;
        }
        case 14: {
          if (tag !== 112) {
            break;
          }

          message.money = reader.int32();
          continue;
        }
        case 15: {
          if (tag !== 120) {
            break;
          }

          message.round_kills = reader.int32();
          continue;
        }
        case 16: {
          if (tag !== 128) {
            break;
          }

          message.round_killhs = reader.int32();
          continue;
        }
        case 17: {
          if (tag !== 141) {
            break;
          }

          message.burning = reader.float();
          continue;
        }
        case 18: {
          if (tag !== 144) {
            break;
          }

          message.helmet = reader.bool();
          continue;
        }
        case 19: {
          if (tag !== 152) {
            break;
          }

          message.defuse_kit = reader.bool();
          continue;
        }
        case 20: {
          if (tag !== 162) {
            break;
          }

          message.weapons.push(MLWeaponState.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MLPlayerState {
    return {
      account_id: isSet(object.accountId)
        ? globalThis.Number(object.accountId)
        : isSet(object.account_id)
        ? globalThis.Number(object.account_id)
        : undefined,
      player_slot: isSet(object.playerSlot)
        ? globalThis.Number(object.playerSlot)
        : isSet(object.player_slot)
        ? globalThis.Number(object.player_slot)
        : undefined,
      entindex: isSet(object.entindex) ? globalThis.Number(object.entindex) : undefined,
      name: isSet(object.name) ? globalThis.String(object.name) : undefined,
      clan: isSet(object.clan) ? globalThis.String(object.clan) : undefined,
      team: isSet(object.team) ? eTeamFromJSON(object.team) : undefined,
      abspos: isSet(object.abspos) ? CMsgVector.fromJSON(object.abspos) : undefined,
      eyeangle: isSet(object.eyeangle) ? CMsgQAngle.fromJSON(object.eyeangle) : undefined,
      eyeangle_fwd: isSet(object.eyeangleFwd)
        ? CMsgVector.fromJSON(object.eyeangleFwd)
        : isSet(object.eyeangle_fwd)
        ? CMsgVector.fromJSON(object.eyeangle_fwd)
        : undefined,
      health: isSet(object.health) ? globalThis.Number(object.health) : undefined,
      armor: isSet(object.armor) ? globalThis.Number(object.armor) : undefined,
      flashed: isSet(object.flashed) ? globalThis.Number(object.flashed) : undefined,
      smoked: isSet(object.smoked) ? globalThis.Number(object.smoked) : undefined,
      money: isSet(object.money) ? globalThis.Number(object.money) : undefined,
      round_kills: isSet(object.roundKills)
        ? globalThis.Number(object.roundKills)
        : isSet(object.round_kills)
        ? globalThis.Number(object.round_kills)
        : undefined,
      round_killhs: isSet(object.roundKillhs)
        ? globalThis.Number(object.roundKillhs)
        : isSet(object.round_killhs)
        ? globalThis.Number(object.round_killhs)
        : undefined,
      burning: isSet(object.burning) ? globalThis.Number(object.burning) : undefined,
      helmet: isSet(object.helmet) ? globalThis.Boolean(object.helmet) : undefined,
      defuse_kit: isSet(object.defuseKit)
        ? globalThis.Boolean(object.defuseKit)
        : isSet(object.defuse_kit)
        ? globalThis.Boolean(object.defuse_kit)
        : undefined,
      weapons: globalThis.Array.isArray(object?.weapons)
        ? object.weapons.map((e: any) => MLWeaponState.fromJSON(e))
        : [],
    };
  },

  toJSON(message: MLPlayerState): unknown {
    const obj: any = {};
    if (message.account_id !== undefined) {
      obj.accountId = Math.round(message.account_id);
    }
    if (message.player_slot !== undefined) {
      obj.playerSlot = Math.round(message.player_slot);
    }
    if (message.entindex !== undefined) {
      obj.entindex = Math.round(message.entindex);
    }
    if (message.name !== undefined) {
      obj.name = message.name;
    }
    if (message.clan !== undefined) {
      obj.clan = message.clan;
    }
    if (message.team !== undefined) {
      obj.team = eTeamToJSON(message.team);
    }
    if (message.abspos !== undefined) {
      obj.abspos = CMsgVector.toJSON(message.abspos);
    }
    if (message.eyeangle !== undefined) {
      obj.eyeangle = CMsgQAngle.toJSON(message.eyeangle);
    }
    if (message.eyeangle_fwd !== undefined) {
      obj.eyeangleFwd = CMsgVector.toJSON(message.eyeangle_fwd);
    }
    if (message.health !== undefined) {
      obj.health = Math.round(message.health);
    }
    if (message.armor !== undefined) {
      obj.armor = Math.round(message.armor);
    }
    if (message.flashed !== undefined) {
      obj.flashed = message.flashed;
    }
    if (message.smoked !== undefined) {
      obj.smoked = message.smoked;
    }
    if (message.money !== undefined) {
      obj.money = Math.round(message.money);
    }
    if (message.round_kills !== undefined) {
      obj.roundKills = Math.round(message.round_kills);
    }
    if (message.round_killhs !== undefined) {
      obj.roundKillhs = Math.round(message.round_killhs);
    }
    if (message.burning !== undefined) {
      obj.burning = message.burning;
    }
    if (message.helmet !== undefined) {
      obj.helmet = message.helmet;
    }
    if (message.defuse_kit !== undefined) {
      obj.defuseKit = message.defuse_kit;
    }
    if (message.weapons?.length) {
      obj.weapons = message.weapons.map((e) => MLWeaponState.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MLPlayerState>, I>>(base?: I): MLPlayerState {
    return MLPlayerState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MLPlayerState>, I>>(object: I): MLPlayerState {
    const message = createBaseMLPlayerState();
    message.account_id = object.account_id ?? undefined;
    message.player_slot = object.player_slot ?? undefined;
    message.entindex = object.entindex ?? undefined;
    message.name = object.name ?? undefined;
    message.clan = object.clan ?? undefined;
    message.team = object.team ?? undefined;
    message.abspos = (object.abspos !== undefined && object.abspos !== null)
      ? CMsgVector.fromPartial(object.abspos)
      : undefined;
    message.eyeangle = (object.eyeangle !== undefined && object.eyeangle !== null)
      ? CMsgQAngle.fromPartial(object.eyeangle)
      : undefined;
    message.eyeangle_fwd = (object.eyeangle_fwd !== undefined && object.eyeangle_fwd !== null)
      ? CMsgVector.fromPartial(object.eyeangle_fwd)
      : undefined;
    message.health = object.health ?? undefined;
    message.armor = object.armor ?? undefined;
    message.flashed = object.flashed ?? undefined;
    message.smoked = object.smoked ?? undefined;
    message.money = object.money ?? undefined;
    message.round_kills = object.round_kills ?? undefined;
    message.round_killhs = object.round_killhs ?? undefined;
    message.burning = object.burning ?? undefined;
    message.helmet = object.helmet ?? undefined;
    message.defuse_kit = object.defuse_kit ?? undefined;
    message.weapons = object.weapons?.map((e) => MLWeaponState.fromPartial(e)) || [];
    return message;
  },
};

function createBaseMLGameState(): MLGameState {
  return { match: undefined, round: undefined, players: [] };
}

export const MLGameState: MessageFns<MLGameState> = {
  encode(message: MLGameState, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.match !== undefined) {
      MLMatchState.encode(message.match, writer.uint32(10).fork()).join();
    }
    if (message.round !== undefined) {
      MLRoundState.encode(message.round, writer.uint32(18).fork()).join();
    }
    for (const v of message.players) {
      MLPlayerState.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MLGameState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMLGameState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.match = MLMatchState.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.round = MLRoundState.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.players.push(MLPlayerState.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MLGameState {
    return {
      match: isSet(object.match) ? MLMatchState.fromJSON(object.match) : undefined,
      round: isSet(object.round) ? MLRoundState.fromJSON(object.round) : undefined,
      players: globalThis.Array.isArray(object?.players)
        ? object.players.map((e: any) => MLPlayerState.fromJSON(e))
        : [],
    };
  },

  toJSON(message: MLGameState): unknown {
    const obj: any = {};
    if (message.match !== undefined) {
      obj.match = MLMatchState.toJSON(message.match);
    }
    if (message.round !== undefined) {
      obj.round = MLRoundState.toJSON(message.round);
    }
    if (message.players?.length) {
      obj.players = message.players.map((e) => MLPlayerState.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MLGameState>, I>>(base?: I): MLGameState {
    return MLGameState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MLGameState>, I>>(object: I): MLGameState {
    const message = createBaseMLGameState();
    message.match = (object.match !== undefined && object.match !== null)
      ? MLMatchState.fromPartial(object.match)
      : undefined;
    message.round = (object.round !== undefined && object.round !== null)
      ? MLRoundState.fromPartial(object.round)
      : undefined;
    message.players = object.players?.map((e) => MLPlayerState.fromPartial(e)) || [];
    return message;
  },
};

function createBaseMLDemoHeader(): MLDemoHeader {
  return { map_name: undefined, tick_rate: undefined, version: undefined, steam_universe: undefined };
}

export const MLDemoHeader: MessageFns<MLDemoHeader> = {
  encode(message: MLDemoHeader, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.map_name !== undefined) {
      writer.uint32(10).string(message.map_name);
    }
    if (message.tick_rate !== undefined) {
      writer.uint32(16).int32(message.tick_rate);
    }
    if (message.version !== undefined) {
      writer.uint32(24).uint32(message.version);
    }
    if (message.steam_universe !== undefined) {
      writer.uint32(32).uint32(message.steam_universe);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MLDemoHeader {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMLDemoHeader();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.map_name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.tick_rate = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.version = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.steam_universe = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MLDemoHeader {
    return {
      map_name: isSet(object.mapName)
        ? globalThis.String(object.mapName)
        : isSet(object.map_name)
        ? globalThis.String(object.map_name)
        : undefined,
      tick_rate: isSet(object.tickRate)
        ? globalThis.Number(object.tickRate)
        : isSet(object.tick_rate)
        ? globalThis.Number(object.tick_rate)
        : undefined,
      version: isSet(object.version) ? globalThis.Number(object.version) : undefined,
      steam_universe: isSet(object.steamUniverse)
        ? globalThis.Number(object.steamUniverse)
        : isSet(object.steam_universe)
        ? globalThis.Number(object.steam_universe)
        : undefined,
    };
  },

  toJSON(message: MLDemoHeader): unknown {
    const obj: any = {};
    if (message.map_name !== undefined) {
      obj.mapName = message.map_name;
    }
    if (message.tick_rate !== undefined) {
      obj.tickRate = Math.round(message.tick_rate);
    }
    if (message.version !== undefined) {
      obj.version = Math.round(message.version);
    }
    if (message.steam_universe !== undefined) {
      obj.steamUniverse = Math.round(message.steam_universe);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MLDemoHeader>, I>>(base?: I): MLDemoHeader {
    return MLDemoHeader.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MLDemoHeader>, I>>(object: I): MLDemoHeader {
    const message = createBaseMLDemoHeader();
    message.map_name = object.map_name ?? undefined;
    message.tick_rate = object.tick_rate ?? undefined;
    message.version = object.version ?? undefined;
    message.steam_universe = object.steam_universe ?? undefined;
    return message;
  },
};

function createBaseMLTick(): MLTick {
  return { tick_count: undefined, state: undefined, events: [] };
}

export const MLTick: MessageFns<MLTick> = {
  encode(message: MLTick, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tick_count !== undefined) {
      writer.uint32(8).int32(message.tick_count);
    }
    if (message.state !== undefined) {
      MLGameState.encode(message.state, writer.uint32(18).fork()).join();
    }
    for (const v of message.events) {
      MLEvent.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MLTick {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMLTick();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.tick_count = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.state = MLGameState.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.events.push(MLEvent.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MLTick {
    return {
      tick_count: isSet(object.tickCount)
        ? globalThis.Number(object.tickCount)
        : isSet(object.tick_count)
        ? globalThis.Number(object.tick_count)
        : undefined,
      state: isSet(object.state) ? MLGameState.fromJSON(object.state) : undefined,
      events: globalThis.Array.isArray(object?.events) ? object.events.map((e: any) => MLEvent.fromJSON(e)) : [],
    };
  },

  toJSON(message: MLTick): unknown {
    const obj: any = {};
    if (message.tick_count !== undefined) {
      obj.tickCount = Math.round(message.tick_count);
    }
    if (message.state !== undefined) {
      obj.state = MLGameState.toJSON(message.state);
    }
    if (message.events?.length) {
      obj.events = message.events.map((e) => MLEvent.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MLTick>, I>>(base?: I): MLTick {
    return MLTick.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MLTick>, I>>(object: I): MLTick {
    const message = createBaseMLTick();
    message.tick_count = object.tick_count ?? undefined;
    message.state = (object.state !== undefined && object.state !== null)
      ? MLGameState.fromPartial(object.state)
      : undefined;
    message.events = object.events?.map((e) => MLEvent.fromPartial(e)) || [];
    return message;
  },
};

function createBaseVacNetShot(): VacNetShot {
  return {
    steamid_player: undefined,
    round_number: undefined,
    hit_type: undefined,
    weapon_type: undefined,
    distance_to_hurt_target: undefined,
    delta_yaw_window: [],
    delta_pitch_window: [],
  };
}

export const VacNetShot: MessageFns<VacNetShot> = {
  encode(message: VacNetShot, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.steamid_player !== undefined) {
      writer.uint32(9).fixed64(message.steamid_player);
    }
    if (message.round_number !== undefined) {
      writer.uint32(16).int32(message.round_number);
    }
    if (message.hit_type !== undefined) {
      writer.uint32(24).int32(message.hit_type);
    }
    if (message.weapon_type !== undefined) {
      writer.uint32(32).int32(message.weapon_type);
    }
    if (message.distance_to_hurt_target !== undefined) {
      writer.uint32(45).float(message.distance_to_hurt_target);
    }
    for (const v of message.delta_yaw_window) {
      writer.uint32(53).float(v!);
    }
    for (const v of message.delta_pitch_window) {
      writer.uint32(61).float(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VacNetShot {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVacNetShot();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 9) {
            break;
          }

          message.steamid_player = reader.fixed64().toString();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.round_number = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.hit_type = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.weapon_type = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 45) {
            break;
          }

          message.distance_to_hurt_target = reader.float();
          continue;
        }
        case 6: {
          if (tag === 53) {
            message.delta_yaw_window.push(reader.float());

            continue;
          }

          if (tag === 50) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.delta_yaw_window.push(reader.float());
            }

            continue;
          }

          break;
        }
        case 7: {
          if (tag === 61) {
            message.delta_pitch_window.push(reader.float());

            continue;
          }

          if (tag === 58) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.delta_pitch_window.push(reader.float());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VacNetShot {
    return {
      steamid_player: isSet(object.steamidPlayer)
        ? globalThis.String(object.steamidPlayer)
        : isSet(object.steamid_player)
        ? globalThis.String(object.steamid_player)
        : undefined,
      round_number: isSet(object.roundNumber)
        ? globalThis.Number(object.roundNumber)
        : isSet(object.round_number)
        ? globalThis.Number(object.round_number)
        : undefined,
      hit_type: isSet(object.hitType)
        ? globalThis.Number(object.hitType)
        : isSet(object.hit_type)
        ? globalThis.Number(object.hit_type)
        : undefined,
      weapon_type: isSet(object.weaponType)
        ? globalThis.Number(object.weaponType)
        : isSet(object.weapon_type)
        ? globalThis.Number(object.weapon_type)
        : undefined,
      distance_to_hurt_target: isSet(object.distanceToHurtTarget)
        ? globalThis.Number(object.distanceToHurtTarget)
        : isSet(object.distance_to_hurt_target)
        ? globalThis.Number(object.distance_to_hurt_target)
        : undefined,
      delta_yaw_window: globalThis.Array.isArray(object?.deltaYawWindow)
        ? object.deltaYawWindow.map((e: any) => globalThis.Number(e))
        : globalThis.Array.isArray(object?.delta_yaw_window)
        ? object.delta_yaw_window.map((e: any) => globalThis.Number(e))
        : [],
      delta_pitch_window: globalThis.Array.isArray(object?.deltaPitchWindow)
        ? object.deltaPitchWindow.map((e: any) => globalThis.Number(e))
        : globalThis.Array.isArray(object?.delta_pitch_window)
        ? object.delta_pitch_window.map((e: any) => globalThis.Number(e))
        : [],
    };
  },

  toJSON(message: VacNetShot): unknown {
    const obj: any = {};
    if (message.steamid_player !== undefined) {
      obj.steamidPlayer = message.steamid_player;
    }
    if (message.round_number !== undefined) {
      obj.roundNumber = Math.round(message.round_number);
    }
    if (message.hit_type !== undefined) {
      obj.hitType = Math.round(message.hit_type);
    }
    if (message.weapon_type !== undefined) {
      obj.weaponType = Math.round(message.weapon_type);
    }
    if (message.distance_to_hurt_target !== undefined) {
      obj.distanceToHurtTarget = message.distance_to_hurt_target;
    }
    if (message.delta_yaw_window?.length) {
      obj.deltaYawWindow = message.delta_yaw_window;
    }
    if (message.delta_pitch_window?.length) {
      obj.deltaPitchWindow = message.delta_pitch_window;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VacNetShot>, I>>(base?: I): VacNetShot {
    return VacNetShot.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VacNetShot>, I>>(object: I): VacNetShot {
    const message = createBaseVacNetShot();
    message.steamid_player = object.steamid_player ?? undefined;
    message.round_number = object.round_number ?? undefined;
    message.hit_type = object.hit_type ?? undefined;
    message.weapon_type = object.weapon_type ?? undefined;
    message.distance_to_hurt_target = object.distance_to_hurt_target ?? undefined;
    message.delta_yaw_window = object.delta_yaw_window?.map((e) => e) || [];
    message.delta_pitch_window = object.delta_pitch_window?.map((e) => e) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
