// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.1
//   protoc               v3.20.3
// source: fatdemo.proto

/* eslint-disable */
import * as _m0 from "protobufjs/minimal";
import { CMsgQAngle, CMsgVector } from "./networkbasetypes";
import Long = require("long");

export const protobufPackage = "";

export enum EHitGroup {
  EHG_Generic = 0,
  EHG_Head = 1,
  EHG_Chest = 2,
  EHG_Stomach = 3,
  EHG_LeftArm = 4,
  EHG_RightArm = 5,
  EHG_LeftLeg = 6,
  EHG_RightLeg = 7,
  EHG_Gear = 8,
  EHG_Miss = 9,
  UNRECOGNIZED = -1,
}

export function eHitGroupFromJSON(object: any): EHitGroup {
  switch (object) {
    case 0:
    case "EHG_Generic":
      return EHitGroup.EHG_Generic;
    case 1:
    case "EHG_Head":
      return EHitGroup.EHG_Head;
    case 2:
    case "EHG_Chest":
      return EHitGroup.EHG_Chest;
    case 3:
    case "EHG_Stomach":
      return EHitGroup.EHG_Stomach;
    case 4:
    case "EHG_LeftArm":
      return EHitGroup.EHG_LeftArm;
    case 5:
    case "EHG_RightArm":
      return EHitGroup.EHG_RightArm;
    case 6:
    case "EHG_LeftLeg":
      return EHitGroup.EHG_LeftLeg;
    case 7:
    case "EHG_RightLeg":
      return EHitGroup.EHG_RightLeg;
    case 8:
    case "EHG_Gear":
      return EHitGroup.EHG_Gear;
    case 9:
    case "EHG_Miss":
      return EHitGroup.EHG_Miss;
    case -1:
    case "UNRECOGNIZED":
    default:
      return EHitGroup.UNRECOGNIZED;
  }
}

export function eHitGroupToJSON(object: EHitGroup): string {
  switch (object) {
    case EHitGroup.EHG_Generic:
      return "EHG_Generic";
    case EHitGroup.EHG_Head:
      return "EHG_Head";
    case EHitGroup.EHG_Chest:
      return "EHG_Chest";
    case EHitGroup.EHG_Stomach:
      return "EHG_Stomach";
    case EHitGroup.EHG_LeftArm:
      return "EHG_LeftArm";
    case EHitGroup.EHG_RightArm:
      return "EHG_RightArm";
    case EHitGroup.EHG_LeftLeg:
      return "EHG_LeftLeg";
    case EHitGroup.EHG_RightLeg:
      return "EHG_RightLeg";
    case EHitGroup.EHG_Gear:
      return "EHG_Gear";
    case EHitGroup.EHG_Miss:
      return "EHG_Miss";
    case EHitGroup.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum ETeam {
  ET_Unknown = 0,
  ET_Spectator = 1,
  ET_Terrorist = 2,
  ET_CT = 3,
  UNRECOGNIZED = -1,
}

export function eTeamFromJSON(object: any): ETeam {
  switch (object) {
    case 0:
    case "ET_Unknown":
      return ETeam.ET_Unknown;
    case 1:
    case "ET_Spectator":
      return ETeam.ET_Spectator;
    case 2:
    case "ET_Terrorist":
      return ETeam.ET_Terrorist;
    case 3:
    case "ET_CT":
      return ETeam.ET_CT;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ETeam.UNRECOGNIZED;
  }
}

export function eTeamToJSON(object: ETeam): string {
  switch (object) {
    case ETeam.ET_Unknown:
      return "ET_Unknown";
    case ETeam.ET_Spectator:
      return "ET_Spectator";
    case ETeam.ET_Terrorist:
      return "ET_Terrorist";
    case ETeam.ET_CT:
      return "ET_CT";
    case ETeam.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum EWeaponType {
  EWT_Knife = 0,
  EWT_Pistol = 1,
  EWT_SubMachineGun = 2,
  EWT_Rifle = 3,
  EWT_Shotgun = 4,
  EWT_SniperRifle = 5,
  EWT_MachineGun = 6,
  EWT_C4 = 7,
  EWT_Grenade = 8,
  EWT_Equipment = 9,
  EWT_StackableItem = 10,
  EWT_Unknown = 11,
  UNRECOGNIZED = -1,
}

export function eWeaponTypeFromJSON(object: any): EWeaponType {
  switch (object) {
    case 0:
    case "EWT_Knife":
      return EWeaponType.EWT_Knife;
    case 1:
    case "EWT_Pistol":
      return EWeaponType.EWT_Pistol;
    case 2:
    case "EWT_SubMachineGun":
      return EWeaponType.EWT_SubMachineGun;
    case 3:
    case "EWT_Rifle":
      return EWeaponType.EWT_Rifle;
    case 4:
    case "EWT_Shotgun":
      return EWeaponType.EWT_Shotgun;
    case 5:
    case "EWT_SniperRifle":
      return EWeaponType.EWT_SniperRifle;
    case 6:
    case "EWT_MachineGun":
      return EWeaponType.EWT_MachineGun;
    case 7:
    case "EWT_C4":
      return EWeaponType.EWT_C4;
    case 8:
    case "EWT_Grenade":
      return EWeaponType.EWT_Grenade;
    case 9:
    case "EWT_Equipment":
      return EWeaponType.EWT_Equipment;
    case 10:
    case "EWT_StackableItem":
      return EWeaponType.EWT_StackableItem;
    case 11:
    case "EWT_Unknown":
      return EWeaponType.EWT_Unknown;
    case -1:
    case "UNRECOGNIZED":
    default:
      return EWeaponType.UNRECOGNIZED;
  }
}

export function eWeaponTypeToJSON(object: EWeaponType): string {
  switch (object) {
    case EWeaponType.EWT_Knife:
      return "EWT_Knife";
    case EWeaponType.EWT_Pistol:
      return "EWT_Pistol";
    case EWeaponType.EWT_SubMachineGun:
      return "EWT_SubMachineGun";
    case EWeaponType.EWT_Rifle:
      return "EWT_Rifle";
    case EWeaponType.EWT_Shotgun:
      return "EWT_Shotgun";
    case EWeaponType.EWT_SniperRifle:
      return "EWT_SniperRifle";
    case EWeaponType.EWT_MachineGun:
      return "EWT_MachineGun";
    case EWeaponType.EWT_C4:
      return "EWT_C4";
    case EWeaponType.EWT_Grenade:
      return "EWT_Grenade";
    case EWeaponType.EWT_Equipment:
      return "EWT_Equipment";
    case EWeaponType.EWT_StackableItem:
      return "EWT_StackableItem";
    case EWeaponType.EWT_Unknown:
      return "EWT_Unknown";
    case EWeaponType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface MLDict {
  key?: string | undefined;
  valString?: string | undefined;
  valInt?: number | undefined;
  valFloat?: number | undefined;
}

export interface MLEvent {
  eventName?: string | undefined;
  data: MLDict[];
}

export interface MLMatchState {
  gameMode?: string | undefined;
  phase?: string | undefined;
  round?: number | undefined;
  scoreCt?: number | undefined;
  scoreT?: number | undefined;
}

export interface MLRoundState {
  phase?: string | undefined;
  winTeam?: ETeam | undefined;
  bombState?: string | undefined;
}

export interface MLWeaponState {
  index?: number | undefined;
  name?: string | undefined;
  type?: EWeaponType | undefined;
  ammoClip?: number | undefined;
  ammoClipMax?: number | undefined;
  ammoReserve?: number | undefined;
  state?: string | undefined;
  recoilIndex?: number | undefined;
}

export interface MLPlayerState {
  accountId?: number | undefined;
  playerSlot?: number | undefined;
  entindex?: number | undefined;
  name?: string | undefined;
  clan?: string | undefined;
  team?: ETeam | undefined;
  abspos?: CMsgVector | undefined;
  eyeangle?: CMsgQAngle | undefined;
  eyeangleFwd?: CMsgVector | undefined;
  health?: number | undefined;
  armor?: number | undefined;
  flashed?: number | undefined;
  smoked?: number | undefined;
  money?: number | undefined;
  roundKills?: number | undefined;
  roundKillhs?: number | undefined;
  burning?: number | undefined;
  helmet?: boolean | undefined;
  defuseKit?: boolean | undefined;
  weapons: MLWeaponState[];
}

export interface MLGameState {
  match?: MLMatchState | undefined;
  round?: MLRoundState | undefined;
  players: MLPlayerState[];
}

export interface MLDemoHeader {
  mapName?: string | undefined;
  tickRate?: number | undefined;
  version?: number | undefined;
  steamUniverse?: number | undefined;
}

export interface MLTick {
  tickCount?: number | undefined;
  state?: MLGameState | undefined;
  events: MLEvent[];
}

export interface VacNetShot {
  steamidPlayer?: string | undefined;
  roundNumber?: number | undefined;
  hitType?: number | undefined;
  weaponType?: number | undefined;
  distanceToHurtTarget?: number | undefined;
  deltaYawWindow: number[];
  deltaPitchWindow: number[];
}

function createBaseMLDict(): MLDict {
  return { key: "", valString: "", valInt: 0, valFloat: 0 };
}

export const MLDict = {
  encode(message: MLDict, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.key !== undefined && message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.valString !== undefined && message.valString !== "") {
      writer.uint32(18).string(message.valString);
    }
    if (message.valInt !== undefined && message.valInt !== 0) {
      writer.uint32(24).int32(message.valInt);
    }
    if (message.valFloat !== undefined && message.valFloat !== 0) {
      writer.uint32(37).float(message.valFloat);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MLDict {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMLDict();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.valString = reader.string();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.valInt = reader.int32();
          continue;
        case 4:
          if (tag !== 37) {
            break;
          }

          message.valFloat = reader.float();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MLDict {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      valString: isSet(object.valString) ? globalThis.String(object.valString) : "",
      valInt: isSet(object.valInt) ? globalThis.Number(object.valInt) : 0,
      valFloat: isSet(object.valFloat) ? globalThis.Number(object.valFloat) : 0,
    };
  },

  toJSON(message: MLDict): unknown {
    const obj: any = {};
    if (message.key !== undefined && message.key !== "") {
      obj.key = message.key;
    }
    if (message.valString !== undefined && message.valString !== "") {
      obj.valString = message.valString;
    }
    if (message.valInt !== undefined && message.valInt !== 0) {
      obj.valInt = Math.round(message.valInt);
    }
    if (message.valFloat !== undefined && message.valFloat !== 0) {
      obj.valFloat = message.valFloat;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MLDict>, I>>(base?: I): MLDict {
    return MLDict.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MLDict>, I>>(object: I): MLDict {
    const message = createBaseMLDict();
    message.key = object.key ?? "";
    message.valString = object.valString ?? "";
    message.valInt = object.valInt ?? 0;
    message.valFloat = object.valFloat ?? 0;
    return message;
  },
};

function createBaseMLEvent(): MLEvent {
  return { eventName: "", data: [] };
}

export const MLEvent = {
  encode(message: MLEvent, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.eventName !== undefined && message.eventName !== "") {
      writer.uint32(10).string(message.eventName);
    }
    for (const v of message.data) {
      MLDict.encode(v!, writer.uint32(18).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MLEvent {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMLEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.eventName = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.data.push(MLDict.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MLEvent {
    return {
      eventName: isSet(object.eventName) ? globalThis.String(object.eventName) : "",
      data: globalThis.Array.isArray(object?.data) ? object.data.map((e: any) => MLDict.fromJSON(e)) : [],
    };
  },

  toJSON(message: MLEvent): unknown {
    const obj: any = {};
    if (message.eventName !== undefined && message.eventName !== "") {
      obj.eventName = message.eventName;
    }
    if (message.data?.length) {
      obj.data = message.data.map((e) => MLDict.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MLEvent>, I>>(base?: I): MLEvent {
    return MLEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MLEvent>, I>>(object: I): MLEvent {
    const message = createBaseMLEvent();
    message.eventName = object.eventName ?? "";
    message.data = object.data?.map((e) => MLDict.fromPartial(e)) || [];
    return message;
  },
};

function createBaseMLMatchState(): MLMatchState {
  return { gameMode: "", phase: "", round: 0, scoreCt: 0, scoreT: 0 };
}

export const MLMatchState = {
  encode(message: MLMatchState, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.gameMode !== undefined && message.gameMode !== "") {
      writer.uint32(10).string(message.gameMode);
    }
    if (message.phase !== undefined && message.phase !== "") {
      writer.uint32(18).string(message.phase);
    }
    if (message.round !== undefined && message.round !== 0) {
      writer.uint32(24).int32(message.round);
    }
    if (message.scoreCt !== undefined && message.scoreCt !== 0) {
      writer.uint32(32).int32(message.scoreCt);
    }
    if (message.scoreT !== undefined && message.scoreT !== 0) {
      writer.uint32(40).int32(message.scoreT);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MLMatchState {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMLMatchState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.gameMode = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.phase = reader.string();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.round = reader.int32();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.scoreCt = reader.int32();
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.scoreT = reader.int32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MLMatchState {
    return {
      gameMode: isSet(object.gameMode) ? globalThis.String(object.gameMode) : "",
      phase: isSet(object.phase) ? globalThis.String(object.phase) : "",
      round: isSet(object.round) ? globalThis.Number(object.round) : 0,
      scoreCt: isSet(object.scoreCt) ? globalThis.Number(object.scoreCt) : 0,
      scoreT: isSet(object.scoreT) ? globalThis.Number(object.scoreT) : 0,
    };
  },

  toJSON(message: MLMatchState): unknown {
    const obj: any = {};
    if (message.gameMode !== undefined && message.gameMode !== "") {
      obj.gameMode = message.gameMode;
    }
    if (message.phase !== undefined && message.phase !== "") {
      obj.phase = message.phase;
    }
    if (message.round !== undefined && message.round !== 0) {
      obj.round = Math.round(message.round);
    }
    if (message.scoreCt !== undefined && message.scoreCt !== 0) {
      obj.scoreCt = Math.round(message.scoreCt);
    }
    if (message.scoreT !== undefined && message.scoreT !== 0) {
      obj.scoreT = Math.round(message.scoreT);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MLMatchState>, I>>(base?: I): MLMatchState {
    return MLMatchState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MLMatchState>, I>>(object: I): MLMatchState {
    const message = createBaseMLMatchState();
    message.gameMode = object.gameMode ?? "";
    message.phase = object.phase ?? "";
    message.round = object.round ?? 0;
    message.scoreCt = object.scoreCt ?? 0;
    message.scoreT = object.scoreT ?? 0;
    return message;
  },
};

function createBaseMLRoundState(): MLRoundState {
  return { phase: "", winTeam: 0, bombState: "" };
}

export const MLRoundState = {
  encode(message: MLRoundState, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.phase !== undefined && message.phase !== "") {
      writer.uint32(10).string(message.phase);
    }
    if (message.winTeam !== undefined && message.winTeam !== 0) {
      writer.uint32(16).int32(message.winTeam);
    }
    if (message.bombState !== undefined && message.bombState !== "") {
      writer.uint32(26).string(message.bombState);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MLRoundState {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMLRoundState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.phase = reader.string();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.winTeam = reader.int32() as any;
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.bombState = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MLRoundState {
    return {
      phase: isSet(object.phase) ? globalThis.String(object.phase) : "",
      winTeam: isSet(object.winTeam) ? eTeamFromJSON(object.winTeam) : 0,
      bombState: isSet(object.bombState) ? globalThis.String(object.bombState) : "",
    };
  },

  toJSON(message: MLRoundState): unknown {
    const obj: any = {};
    if (message.phase !== undefined && message.phase !== "") {
      obj.phase = message.phase;
    }
    if (message.winTeam !== undefined && message.winTeam !== 0) {
      obj.winTeam = eTeamToJSON(message.winTeam);
    }
    if (message.bombState !== undefined && message.bombState !== "") {
      obj.bombState = message.bombState;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MLRoundState>, I>>(base?: I): MLRoundState {
    return MLRoundState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MLRoundState>, I>>(object: I): MLRoundState {
    const message = createBaseMLRoundState();
    message.phase = object.phase ?? "";
    message.winTeam = object.winTeam ?? 0;
    message.bombState = object.bombState ?? "";
    return message;
  },
};

function createBaseMLWeaponState(): MLWeaponState {
  return { index: 0, name: "", type: 0, ammoClip: 0, ammoClipMax: 0, ammoReserve: 0, state: "", recoilIndex: 0 };
}

export const MLWeaponState = {
  encode(message: MLWeaponState, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.index !== undefined && message.index !== 0) {
      writer.uint32(8).int32(message.index);
    }
    if (message.name !== undefined && message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.type !== undefined && message.type !== 0) {
      writer.uint32(24).int32(message.type);
    }
    if (message.ammoClip !== undefined && message.ammoClip !== 0) {
      writer.uint32(32).int32(message.ammoClip);
    }
    if (message.ammoClipMax !== undefined && message.ammoClipMax !== 0) {
      writer.uint32(40).int32(message.ammoClipMax);
    }
    if (message.ammoReserve !== undefined && message.ammoReserve !== 0) {
      writer.uint32(48).int32(message.ammoReserve);
    }
    if (message.state !== undefined && message.state !== "") {
      writer.uint32(58).string(message.state);
    }
    if (message.recoilIndex !== undefined && message.recoilIndex !== 0) {
      writer.uint32(69).float(message.recoilIndex);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MLWeaponState {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMLWeaponState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.index = reader.int32();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.ammoClip = reader.int32();
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.ammoClipMax = reader.int32();
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.ammoReserve = reader.int32();
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.state = reader.string();
          continue;
        case 8:
          if (tag !== 69) {
            break;
          }

          message.recoilIndex = reader.float();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MLWeaponState {
    return {
      index: isSet(object.index) ? globalThis.Number(object.index) : 0,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      type: isSet(object.type) ? eWeaponTypeFromJSON(object.type) : 0,
      ammoClip: isSet(object.ammoClip) ? globalThis.Number(object.ammoClip) : 0,
      ammoClipMax: isSet(object.ammoClipMax) ? globalThis.Number(object.ammoClipMax) : 0,
      ammoReserve: isSet(object.ammoReserve) ? globalThis.Number(object.ammoReserve) : 0,
      state: isSet(object.state) ? globalThis.String(object.state) : "",
      recoilIndex: isSet(object.recoilIndex) ? globalThis.Number(object.recoilIndex) : 0,
    };
  },

  toJSON(message: MLWeaponState): unknown {
    const obj: any = {};
    if (message.index !== undefined && message.index !== 0) {
      obj.index = Math.round(message.index);
    }
    if (message.name !== undefined && message.name !== "") {
      obj.name = message.name;
    }
    if (message.type !== undefined && message.type !== 0) {
      obj.type = eWeaponTypeToJSON(message.type);
    }
    if (message.ammoClip !== undefined && message.ammoClip !== 0) {
      obj.ammoClip = Math.round(message.ammoClip);
    }
    if (message.ammoClipMax !== undefined && message.ammoClipMax !== 0) {
      obj.ammoClipMax = Math.round(message.ammoClipMax);
    }
    if (message.ammoReserve !== undefined && message.ammoReserve !== 0) {
      obj.ammoReserve = Math.round(message.ammoReserve);
    }
    if (message.state !== undefined && message.state !== "") {
      obj.state = message.state;
    }
    if (message.recoilIndex !== undefined && message.recoilIndex !== 0) {
      obj.recoilIndex = message.recoilIndex;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MLWeaponState>, I>>(base?: I): MLWeaponState {
    return MLWeaponState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MLWeaponState>, I>>(object: I): MLWeaponState {
    const message = createBaseMLWeaponState();
    message.index = object.index ?? 0;
    message.name = object.name ?? "";
    message.type = object.type ?? 0;
    message.ammoClip = object.ammoClip ?? 0;
    message.ammoClipMax = object.ammoClipMax ?? 0;
    message.ammoReserve = object.ammoReserve ?? 0;
    message.state = object.state ?? "";
    message.recoilIndex = object.recoilIndex ?? 0;
    return message;
  },
};

function createBaseMLPlayerState(): MLPlayerState {
  return {
    accountId: 0,
    playerSlot: -1,
    entindex: 0,
    name: "",
    clan: "",
    team: 0,
    abspos: undefined,
    eyeangle: undefined,
    eyeangleFwd: undefined,
    health: 0,
    armor: 0,
    flashed: 0,
    smoked: 0,
    money: 0,
    roundKills: 0,
    roundKillhs: 0,
    burning: 0,
    helmet: false,
    defuseKit: false,
    weapons: [],
  };
}

export const MLPlayerState = {
  encode(message: MLPlayerState, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.accountId !== undefined && message.accountId !== 0) {
      writer.uint32(8).int32(message.accountId);
    }
    if (message.playerSlot !== undefined && message.playerSlot !== -1) {
      writer.uint32(16).int32(message.playerSlot);
    }
    if (message.entindex !== undefined && message.entindex !== 0) {
      writer.uint32(24).int32(message.entindex);
    }
    if (message.name !== undefined && message.name !== "") {
      writer.uint32(34).string(message.name);
    }
    if (message.clan !== undefined && message.clan !== "") {
      writer.uint32(42).string(message.clan);
    }
    if (message.team !== undefined && message.team !== 0) {
      writer.uint32(48).int32(message.team);
    }
    if (message.abspos !== undefined) {
      CMsgVector.encode(message.abspos, writer.uint32(58).fork()).ldelim();
    }
    if (message.eyeangle !== undefined) {
      CMsgQAngle.encode(message.eyeangle, writer.uint32(66).fork()).ldelim();
    }
    if (message.eyeangleFwd !== undefined) {
      CMsgVector.encode(message.eyeangleFwd, writer.uint32(74).fork()).ldelim();
    }
    if (message.health !== undefined && message.health !== 0) {
      writer.uint32(80).int32(message.health);
    }
    if (message.armor !== undefined && message.armor !== 0) {
      writer.uint32(88).int32(message.armor);
    }
    if (message.flashed !== undefined && message.flashed !== 0) {
      writer.uint32(101).float(message.flashed);
    }
    if (message.smoked !== undefined && message.smoked !== 0) {
      writer.uint32(109).float(message.smoked);
    }
    if (message.money !== undefined && message.money !== 0) {
      writer.uint32(112).int32(message.money);
    }
    if (message.roundKills !== undefined && message.roundKills !== 0) {
      writer.uint32(120).int32(message.roundKills);
    }
    if (message.roundKillhs !== undefined && message.roundKillhs !== 0) {
      writer.uint32(128).int32(message.roundKillhs);
    }
    if (message.burning !== undefined && message.burning !== 0) {
      writer.uint32(141).float(message.burning);
    }
    if (message.helmet !== undefined && message.helmet !== false) {
      writer.uint32(144).bool(message.helmet);
    }
    if (message.defuseKit !== undefined && message.defuseKit !== false) {
      writer.uint32(152).bool(message.defuseKit);
    }
    for (const v of message.weapons) {
      MLWeaponState.encode(v!, writer.uint32(162).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MLPlayerState {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMLPlayerState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.accountId = reader.int32();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.playerSlot = reader.int32();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.entindex = reader.int32();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.name = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.clan = reader.string();
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.team = reader.int32() as any;
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.abspos = CMsgVector.decode(reader, reader.uint32());
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.eyeangle = CMsgQAngle.decode(reader, reader.uint32());
          continue;
        case 9:
          if (tag !== 74) {
            break;
          }

          message.eyeangleFwd = CMsgVector.decode(reader, reader.uint32());
          continue;
        case 10:
          if (tag !== 80) {
            break;
          }

          message.health = reader.int32();
          continue;
        case 11:
          if (tag !== 88) {
            break;
          }

          message.armor = reader.int32();
          continue;
        case 12:
          if (tag !== 101) {
            break;
          }

          message.flashed = reader.float();
          continue;
        case 13:
          if (tag !== 109) {
            break;
          }

          message.smoked = reader.float();
          continue;
        case 14:
          if (tag !== 112) {
            break;
          }

          message.money = reader.int32();
          continue;
        case 15:
          if (tag !== 120) {
            break;
          }

          message.roundKills = reader.int32();
          continue;
        case 16:
          if (tag !== 128) {
            break;
          }

          message.roundKillhs = reader.int32();
          continue;
        case 17:
          if (tag !== 141) {
            break;
          }

          message.burning = reader.float();
          continue;
        case 18:
          if (tag !== 144) {
            break;
          }

          message.helmet = reader.bool();
          continue;
        case 19:
          if (tag !== 152) {
            break;
          }

          message.defuseKit = reader.bool();
          continue;
        case 20:
          if (tag !== 162) {
            break;
          }

          message.weapons.push(MLWeaponState.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MLPlayerState {
    return {
      accountId: isSet(object.accountId) ? globalThis.Number(object.accountId) : 0,
      playerSlot: isSet(object.playerSlot) ? globalThis.Number(object.playerSlot) : -1,
      entindex: isSet(object.entindex) ? globalThis.Number(object.entindex) : 0,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      clan: isSet(object.clan) ? globalThis.String(object.clan) : "",
      team: isSet(object.team) ? eTeamFromJSON(object.team) : 0,
      abspos: isSet(object.abspos) ? CMsgVector.fromJSON(object.abspos) : undefined,
      eyeangle: isSet(object.eyeangle) ? CMsgQAngle.fromJSON(object.eyeangle) : undefined,
      eyeangleFwd: isSet(object.eyeangleFwd) ? CMsgVector.fromJSON(object.eyeangleFwd) : undefined,
      health: isSet(object.health) ? globalThis.Number(object.health) : 0,
      armor: isSet(object.armor) ? globalThis.Number(object.armor) : 0,
      flashed: isSet(object.flashed) ? globalThis.Number(object.flashed) : 0,
      smoked: isSet(object.smoked) ? globalThis.Number(object.smoked) : 0,
      money: isSet(object.money) ? globalThis.Number(object.money) : 0,
      roundKills: isSet(object.roundKills) ? globalThis.Number(object.roundKills) : 0,
      roundKillhs: isSet(object.roundKillhs) ? globalThis.Number(object.roundKillhs) : 0,
      burning: isSet(object.burning) ? globalThis.Number(object.burning) : 0,
      helmet: isSet(object.helmet) ? globalThis.Boolean(object.helmet) : false,
      defuseKit: isSet(object.defuseKit) ? globalThis.Boolean(object.defuseKit) : false,
      weapons: globalThis.Array.isArray(object?.weapons)
        ? object.weapons.map((e: any) => MLWeaponState.fromJSON(e))
        : [],
    };
  },

  toJSON(message: MLPlayerState): unknown {
    const obj: any = {};
    if (message.accountId !== undefined && message.accountId !== 0) {
      obj.accountId = Math.round(message.accountId);
    }
    if (message.playerSlot !== undefined && message.playerSlot !== -1) {
      obj.playerSlot = Math.round(message.playerSlot);
    }
    if (message.entindex !== undefined && message.entindex !== 0) {
      obj.entindex = Math.round(message.entindex);
    }
    if (message.name !== undefined && message.name !== "") {
      obj.name = message.name;
    }
    if (message.clan !== undefined && message.clan !== "") {
      obj.clan = message.clan;
    }
    if (message.team !== undefined && message.team !== 0) {
      obj.team = eTeamToJSON(message.team);
    }
    if (message.abspos !== undefined) {
      obj.abspos = CMsgVector.toJSON(message.abspos);
    }
    if (message.eyeangle !== undefined) {
      obj.eyeangle = CMsgQAngle.toJSON(message.eyeangle);
    }
    if (message.eyeangleFwd !== undefined) {
      obj.eyeangleFwd = CMsgVector.toJSON(message.eyeangleFwd);
    }
    if (message.health !== undefined && message.health !== 0) {
      obj.health = Math.round(message.health);
    }
    if (message.armor !== undefined && message.armor !== 0) {
      obj.armor = Math.round(message.armor);
    }
    if (message.flashed !== undefined && message.flashed !== 0) {
      obj.flashed = message.flashed;
    }
    if (message.smoked !== undefined && message.smoked !== 0) {
      obj.smoked = message.smoked;
    }
    if (message.money !== undefined && message.money !== 0) {
      obj.money = Math.round(message.money);
    }
    if (message.roundKills !== undefined && message.roundKills !== 0) {
      obj.roundKills = Math.round(message.roundKills);
    }
    if (message.roundKillhs !== undefined && message.roundKillhs !== 0) {
      obj.roundKillhs = Math.round(message.roundKillhs);
    }
    if (message.burning !== undefined && message.burning !== 0) {
      obj.burning = message.burning;
    }
    if (message.helmet !== undefined && message.helmet !== false) {
      obj.helmet = message.helmet;
    }
    if (message.defuseKit !== undefined && message.defuseKit !== false) {
      obj.defuseKit = message.defuseKit;
    }
    if (message.weapons?.length) {
      obj.weapons = message.weapons.map((e) => MLWeaponState.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MLPlayerState>, I>>(base?: I): MLPlayerState {
    return MLPlayerState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MLPlayerState>, I>>(object: I): MLPlayerState {
    const message = createBaseMLPlayerState();
    message.accountId = object.accountId ?? 0;
    message.playerSlot = object.playerSlot ?? -1;
    message.entindex = object.entindex ?? 0;
    message.name = object.name ?? "";
    message.clan = object.clan ?? "";
    message.team = object.team ?? 0;
    message.abspos = (object.abspos !== undefined && object.abspos !== null)
      ? CMsgVector.fromPartial(object.abspos)
      : undefined;
    message.eyeangle = (object.eyeangle !== undefined && object.eyeangle !== null)
      ? CMsgQAngle.fromPartial(object.eyeangle)
      : undefined;
    message.eyeangleFwd = (object.eyeangleFwd !== undefined && object.eyeangleFwd !== null)
      ? CMsgVector.fromPartial(object.eyeangleFwd)
      : undefined;
    message.health = object.health ?? 0;
    message.armor = object.armor ?? 0;
    message.flashed = object.flashed ?? 0;
    message.smoked = object.smoked ?? 0;
    message.money = object.money ?? 0;
    message.roundKills = object.roundKills ?? 0;
    message.roundKillhs = object.roundKillhs ?? 0;
    message.burning = object.burning ?? 0;
    message.helmet = object.helmet ?? false;
    message.defuseKit = object.defuseKit ?? false;
    message.weapons = object.weapons?.map((e) => MLWeaponState.fromPartial(e)) || [];
    return message;
  },
};

function createBaseMLGameState(): MLGameState {
  return { match: undefined, round: undefined, players: [] };
}

export const MLGameState = {
  encode(message: MLGameState, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.match !== undefined) {
      MLMatchState.encode(message.match, writer.uint32(10).fork()).ldelim();
    }
    if (message.round !== undefined) {
      MLRoundState.encode(message.round, writer.uint32(18).fork()).ldelim();
    }
    for (const v of message.players) {
      MLPlayerState.encode(v!, writer.uint32(26).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MLGameState {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMLGameState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.match = MLMatchState.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.round = MLRoundState.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.players.push(MLPlayerState.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MLGameState {
    return {
      match: isSet(object.match) ? MLMatchState.fromJSON(object.match) : undefined,
      round: isSet(object.round) ? MLRoundState.fromJSON(object.round) : undefined,
      players: globalThis.Array.isArray(object?.players)
        ? object.players.map((e: any) => MLPlayerState.fromJSON(e))
        : [],
    };
  },

  toJSON(message: MLGameState): unknown {
    const obj: any = {};
    if (message.match !== undefined) {
      obj.match = MLMatchState.toJSON(message.match);
    }
    if (message.round !== undefined) {
      obj.round = MLRoundState.toJSON(message.round);
    }
    if (message.players?.length) {
      obj.players = message.players.map((e) => MLPlayerState.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MLGameState>, I>>(base?: I): MLGameState {
    return MLGameState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MLGameState>, I>>(object: I): MLGameState {
    const message = createBaseMLGameState();
    message.match = (object.match !== undefined && object.match !== null)
      ? MLMatchState.fromPartial(object.match)
      : undefined;
    message.round = (object.round !== undefined && object.round !== null)
      ? MLRoundState.fromPartial(object.round)
      : undefined;
    message.players = object.players?.map((e) => MLPlayerState.fromPartial(e)) || [];
    return message;
  },
};

function createBaseMLDemoHeader(): MLDemoHeader {
  return { mapName: "", tickRate: 0, version: 0, steamUniverse: 0 };
}

export const MLDemoHeader = {
  encode(message: MLDemoHeader, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.mapName !== undefined && message.mapName !== "") {
      writer.uint32(10).string(message.mapName);
    }
    if (message.tickRate !== undefined && message.tickRate !== 0) {
      writer.uint32(16).int32(message.tickRate);
    }
    if (message.version !== undefined && message.version !== 0) {
      writer.uint32(24).uint32(message.version);
    }
    if (message.steamUniverse !== undefined && message.steamUniverse !== 0) {
      writer.uint32(32).uint32(message.steamUniverse);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MLDemoHeader {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMLDemoHeader();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.mapName = reader.string();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.tickRate = reader.int32();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.version = reader.uint32();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.steamUniverse = reader.uint32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MLDemoHeader {
    return {
      mapName: isSet(object.mapName) ? globalThis.String(object.mapName) : "",
      tickRate: isSet(object.tickRate) ? globalThis.Number(object.tickRate) : 0,
      version: isSet(object.version) ? globalThis.Number(object.version) : 0,
      steamUniverse: isSet(object.steamUniverse) ? globalThis.Number(object.steamUniverse) : 0,
    };
  },

  toJSON(message: MLDemoHeader): unknown {
    const obj: any = {};
    if (message.mapName !== undefined && message.mapName !== "") {
      obj.mapName = message.mapName;
    }
    if (message.tickRate !== undefined && message.tickRate !== 0) {
      obj.tickRate = Math.round(message.tickRate);
    }
    if (message.version !== undefined && message.version !== 0) {
      obj.version = Math.round(message.version);
    }
    if (message.steamUniverse !== undefined && message.steamUniverse !== 0) {
      obj.steamUniverse = Math.round(message.steamUniverse);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MLDemoHeader>, I>>(base?: I): MLDemoHeader {
    return MLDemoHeader.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MLDemoHeader>, I>>(object: I): MLDemoHeader {
    const message = createBaseMLDemoHeader();
    message.mapName = object.mapName ?? "";
    message.tickRate = object.tickRate ?? 0;
    message.version = object.version ?? 0;
    message.steamUniverse = object.steamUniverse ?? 0;
    return message;
  },
};

function createBaseMLTick(): MLTick {
  return { tickCount: 0, state: undefined, events: [] };
}

export const MLTick = {
  encode(message: MLTick, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.tickCount !== undefined && message.tickCount !== 0) {
      writer.uint32(8).int32(message.tickCount);
    }
    if (message.state !== undefined) {
      MLGameState.encode(message.state, writer.uint32(18).fork()).ldelim();
    }
    for (const v of message.events) {
      MLEvent.encode(v!, writer.uint32(26).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MLTick {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMLTick();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.tickCount = reader.int32();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.state = MLGameState.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.events.push(MLEvent.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MLTick {
    return {
      tickCount: isSet(object.tickCount) ? globalThis.Number(object.tickCount) : 0,
      state: isSet(object.state) ? MLGameState.fromJSON(object.state) : undefined,
      events: globalThis.Array.isArray(object?.events) ? object.events.map((e: any) => MLEvent.fromJSON(e)) : [],
    };
  },

  toJSON(message: MLTick): unknown {
    const obj: any = {};
    if (message.tickCount !== undefined && message.tickCount !== 0) {
      obj.tickCount = Math.round(message.tickCount);
    }
    if (message.state !== undefined) {
      obj.state = MLGameState.toJSON(message.state);
    }
    if (message.events?.length) {
      obj.events = message.events.map((e) => MLEvent.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MLTick>, I>>(base?: I): MLTick {
    return MLTick.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MLTick>, I>>(object: I): MLTick {
    const message = createBaseMLTick();
    message.tickCount = object.tickCount ?? 0;
    message.state = (object.state !== undefined && object.state !== null)
      ? MLGameState.fromPartial(object.state)
      : undefined;
    message.events = object.events?.map((e) => MLEvent.fromPartial(e)) || [];
    return message;
  },
};

function createBaseVacNetShot(): VacNetShot {
  return {
    steamidPlayer: "0",
    roundNumber: 0,
    hitType: 0,
    weaponType: 0,
    distanceToHurtTarget: 0,
    deltaYawWindow: [],
    deltaPitchWindow: [],
  };
}

export const VacNetShot = {
  encode(message: VacNetShot, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.steamidPlayer !== undefined && message.steamidPlayer !== "0") {
      writer.uint32(9).fixed64(message.steamidPlayer);
    }
    if (message.roundNumber !== undefined && message.roundNumber !== 0) {
      writer.uint32(16).int32(message.roundNumber);
    }
    if (message.hitType !== undefined && message.hitType !== 0) {
      writer.uint32(24).int32(message.hitType);
    }
    if (message.weaponType !== undefined && message.weaponType !== 0) {
      writer.uint32(32).int32(message.weaponType);
    }
    if (message.distanceToHurtTarget !== undefined && message.distanceToHurtTarget !== 0) {
      writer.uint32(45).float(message.distanceToHurtTarget);
    }
    writer.uint32(50).fork();
    for (const v of message.deltaYawWindow) {
      writer.float(v);
    }
    writer.ldelim();
    writer.uint32(58).fork();
    for (const v of message.deltaPitchWindow) {
      writer.float(v);
    }
    writer.ldelim();
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): VacNetShot {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVacNetShot();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 9) {
            break;
          }

          message.steamidPlayer = longToString(reader.fixed64() as Long);
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.roundNumber = reader.int32();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.hitType = reader.int32();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.weaponType = reader.int32();
          continue;
        case 5:
          if (tag !== 45) {
            break;
          }

          message.distanceToHurtTarget = reader.float();
          continue;
        case 6:
          if (tag === 53) {
            message.deltaYawWindow.push(reader.float());

            continue;
          }

          if (tag === 50) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.deltaYawWindow.push(reader.float());
            }

            continue;
          }

          break;
        case 7:
          if (tag === 61) {
            message.deltaPitchWindow.push(reader.float());

            continue;
          }

          if (tag === 58) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.deltaPitchWindow.push(reader.float());
            }

            continue;
          }

          break;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VacNetShot {
    return {
      steamidPlayer: isSet(object.steamidPlayer) ? globalThis.String(object.steamidPlayer) : "0",
      roundNumber: isSet(object.roundNumber) ? globalThis.Number(object.roundNumber) : 0,
      hitType: isSet(object.hitType) ? globalThis.Number(object.hitType) : 0,
      weaponType: isSet(object.weaponType) ? globalThis.Number(object.weaponType) : 0,
      distanceToHurtTarget: isSet(object.distanceToHurtTarget) ? globalThis.Number(object.distanceToHurtTarget) : 0,
      deltaYawWindow: globalThis.Array.isArray(object?.deltaYawWindow)
        ? object.deltaYawWindow.map((e: any) => globalThis.Number(e))
        : [],
      deltaPitchWindow: globalThis.Array.isArray(object?.deltaPitchWindow)
        ? object.deltaPitchWindow.map((e: any) => globalThis.Number(e))
        : [],
    };
  },

  toJSON(message: VacNetShot): unknown {
    const obj: any = {};
    if (message.steamidPlayer !== undefined && message.steamidPlayer !== "0") {
      obj.steamidPlayer = message.steamidPlayer;
    }
    if (message.roundNumber !== undefined && message.roundNumber !== 0) {
      obj.roundNumber = Math.round(message.roundNumber);
    }
    if (message.hitType !== undefined && message.hitType !== 0) {
      obj.hitType = Math.round(message.hitType);
    }
    if (message.weaponType !== undefined && message.weaponType !== 0) {
      obj.weaponType = Math.round(message.weaponType);
    }
    if (message.distanceToHurtTarget !== undefined && message.distanceToHurtTarget !== 0) {
      obj.distanceToHurtTarget = message.distanceToHurtTarget;
    }
    if (message.deltaYawWindow?.length) {
      obj.deltaYawWindow = message.deltaYawWindow;
    }
    if (message.deltaPitchWindow?.length) {
      obj.deltaPitchWindow = message.deltaPitchWindow;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VacNetShot>, I>>(base?: I): VacNetShot {
    return VacNetShot.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VacNetShot>, I>>(object: I): VacNetShot {
    const message = createBaseVacNetShot();
    message.steamidPlayer = object.steamidPlayer ?? "0";
    message.roundNumber = object.roundNumber ?? 0;
    message.hitType = object.hitType ?? 0;
    message.weaponType = object.weaponType ?? 0;
    message.distanceToHurtTarget = object.distanceToHurtTarget ?? 0;
    message.deltaYawWindow = object.deltaYawWindow?.map((e) => e) || [];
    message.deltaPitchWindow = object.deltaPitchWindow?.map((e) => e) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToString(long: Long) {
  return long.toString();
}

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
