// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.1
// source: steammessages_unified_base.steamworkssdk.proto

/* eslint-disable */

export const protobufPackage = "";

export const EProtoExecutionSite = {
  k_EProtoExecutionSiteUnknown: 0,
  k_EProtoExecutionSiteSteamClient: 3,
  UNRECOGNIZED: -1,
} as const;

export type EProtoExecutionSite = typeof EProtoExecutionSite[keyof typeof EProtoExecutionSite];

export namespace EProtoExecutionSite {
  export type k_EProtoExecutionSiteUnknown = typeof EProtoExecutionSite.k_EProtoExecutionSiteUnknown;
  export type k_EProtoExecutionSiteSteamClient = typeof EProtoExecutionSite.k_EProtoExecutionSiteSteamClient;
  export type UNRECOGNIZED = typeof EProtoExecutionSite.UNRECOGNIZED;
}

export function eProtoExecutionSiteFromJSON(object: any): EProtoExecutionSite {
  switch (object) {
    case 0:
    case "k_EProtoExecutionSiteUnknown":
      return EProtoExecutionSite.k_EProtoExecutionSiteUnknown;
    case 3:
    case "k_EProtoExecutionSiteSteamClient":
      return EProtoExecutionSite.k_EProtoExecutionSiteSteamClient;
    case -1:
    case "UNRECOGNIZED":
    default:
      return EProtoExecutionSite.UNRECOGNIZED;
  }
}

export function eProtoExecutionSiteToJSON(object: EProtoExecutionSite): string {
  switch (object) {
    case EProtoExecutionSite.k_EProtoExecutionSiteUnknown:
      return "k_EProtoExecutionSiteUnknown";
    case EProtoExecutionSite.k_EProtoExecutionSiteSteamClient:
      return "k_EProtoExecutionSiteSteamClient";
    case EProtoExecutionSite.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}
