// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.1
// source: steamnetworkingsockets_messages_udp.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  CMsgSteamDatagramConnectionQuality,
  CMsgSteamDatagramSessionCryptInfoSigned,
} from "./steamnetworkingsockets_messages.js";
import {
  CMsgSteamDatagramCertificateSigned,
  CMsgSteamNetworkingIdentityLegacyBinary,
} from "./steamnetworkingsockets_messages_certs.js";

export const protobufPackage = "";

export const ESteamNetworkingUDPMsgID = {
  k_ESteamNetworkingUDPMsg_ChallengeRequest: 32,
  k_ESteamNetworkingUDPMsg_ChallengeReply: 33,
  k_ESteamNetworkingUDPMsg_ConnectRequest: 34,
  k_ESteamNetworkingUDPMsg_ConnectOK: 35,
  k_ESteamNetworkingUDPMsg_ConnectionClosed: 36,
  k_ESteamNetworkingUDPMsg_NoConnection: 37,
  UNRECOGNIZED: -1,
} as const;

export type ESteamNetworkingUDPMsgID = typeof ESteamNetworkingUDPMsgID[keyof typeof ESteamNetworkingUDPMsgID];

export namespace ESteamNetworkingUDPMsgID {
  export type k_ESteamNetworkingUDPMsg_ChallengeRequest =
    typeof ESteamNetworkingUDPMsgID.k_ESteamNetworkingUDPMsg_ChallengeRequest;
  export type k_ESteamNetworkingUDPMsg_ChallengeReply =
    typeof ESteamNetworkingUDPMsgID.k_ESteamNetworkingUDPMsg_ChallengeReply;
  export type k_ESteamNetworkingUDPMsg_ConnectRequest =
    typeof ESteamNetworkingUDPMsgID.k_ESteamNetworkingUDPMsg_ConnectRequest;
  export type k_ESteamNetworkingUDPMsg_ConnectOK = typeof ESteamNetworkingUDPMsgID.k_ESteamNetworkingUDPMsg_ConnectOK;
  export type k_ESteamNetworkingUDPMsg_ConnectionClosed =
    typeof ESteamNetworkingUDPMsgID.k_ESteamNetworkingUDPMsg_ConnectionClosed;
  export type k_ESteamNetworkingUDPMsg_NoConnection =
    typeof ESteamNetworkingUDPMsgID.k_ESteamNetworkingUDPMsg_NoConnection;
  export type UNRECOGNIZED = typeof ESteamNetworkingUDPMsgID.UNRECOGNIZED;
}

export function eSteamNetworkingUDPMsgIDFromJSON(object: any): ESteamNetworkingUDPMsgID {
  switch (object) {
    case 32:
    case "k_ESteamNetworkingUDPMsg_ChallengeRequest":
      return ESteamNetworkingUDPMsgID.k_ESteamNetworkingUDPMsg_ChallengeRequest;
    case 33:
    case "k_ESteamNetworkingUDPMsg_ChallengeReply":
      return ESteamNetworkingUDPMsgID.k_ESteamNetworkingUDPMsg_ChallengeReply;
    case 34:
    case "k_ESteamNetworkingUDPMsg_ConnectRequest":
      return ESteamNetworkingUDPMsgID.k_ESteamNetworkingUDPMsg_ConnectRequest;
    case 35:
    case "k_ESteamNetworkingUDPMsg_ConnectOK":
      return ESteamNetworkingUDPMsgID.k_ESteamNetworkingUDPMsg_ConnectOK;
    case 36:
    case "k_ESteamNetworkingUDPMsg_ConnectionClosed":
      return ESteamNetworkingUDPMsgID.k_ESteamNetworkingUDPMsg_ConnectionClosed;
    case 37:
    case "k_ESteamNetworkingUDPMsg_NoConnection":
      return ESteamNetworkingUDPMsgID.k_ESteamNetworkingUDPMsg_NoConnection;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ESteamNetworkingUDPMsgID.UNRECOGNIZED;
  }
}

export function eSteamNetworkingUDPMsgIDToJSON(object: ESteamNetworkingUDPMsgID): string {
  switch (object) {
    case ESteamNetworkingUDPMsgID.k_ESteamNetworkingUDPMsg_ChallengeRequest:
      return "k_ESteamNetworkingUDPMsg_ChallengeRequest";
    case ESteamNetworkingUDPMsgID.k_ESteamNetworkingUDPMsg_ChallengeReply:
      return "k_ESteamNetworkingUDPMsg_ChallengeReply";
    case ESteamNetworkingUDPMsgID.k_ESteamNetworkingUDPMsg_ConnectRequest:
      return "k_ESteamNetworkingUDPMsg_ConnectRequest";
    case ESteamNetworkingUDPMsgID.k_ESteamNetworkingUDPMsg_ConnectOK:
      return "k_ESteamNetworkingUDPMsg_ConnectOK";
    case ESteamNetworkingUDPMsgID.k_ESteamNetworkingUDPMsg_ConnectionClosed:
      return "k_ESteamNetworkingUDPMsg_ConnectionClosed";
    case ESteamNetworkingUDPMsgID.k_ESteamNetworkingUDPMsg_NoConnection:
      return "k_ESteamNetworkingUDPMsg_NoConnection";
    case ESteamNetworkingUDPMsgID.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface CMsgSteamSockets_UDP_ChallengeRequest {
  connection_id?: number | undefined;
  my_timestamp?: string | undefined;
  protocol_version?: number | undefined;
}

export interface CMsgSteamSockets_UDP_ChallengeReply {
  connection_id?: number | undefined;
  challenge?: string | undefined;
  your_timestamp?: string | undefined;
  protocol_version?: number | undefined;
}

export interface CMsgSteamSockets_UDP_ConnectRequest {
  client_connection_id?: number | undefined;
  challenge?: string | undefined;
  my_timestamp?: string | undefined;
  ping_est_ms?: number | undefined;
  crypt?: CMsgSteamDatagramSessionCryptInfoSigned | undefined;
  cert?: CMsgSteamDatagramCertificateSigned | undefined;
  legacy_protocol_version?: number | undefined;
  identity_string?: string | undefined;
  legacy_client_steam_id?: string | undefined;
  legacy_identity_binary?: CMsgSteamNetworkingIdentityLegacyBinary | undefined;
}

export interface CMsgSteamSockets_UDP_ConnectOK {
  client_connection_id?: number | undefined;
  server_connection_id?: number | undefined;
  your_timestamp?: string | undefined;
  delay_time_usec?: number | undefined;
  crypt?: CMsgSteamDatagramSessionCryptInfoSigned | undefined;
  cert?: CMsgSteamDatagramCertificateSigned | undefined;
  identity_string?: string | undefined;
  legacy_server_steam_id?: string | undefined;
  legacy_identity_binary?: CMsgSteamNetworkingIdentityLegacyBinary | undefined;
}

export interface CMsgSteamSockets_UDP_ConnectionClosed {
  to_connection_id?: number | undefined;
  from_connection_id?: number | undefined;
  debug?: string | undefined;
  reason_code?: number | undefined;
}

export interface CMsgSteamSockets_UDP_NoConnection {
  from_connection_id?: number | undefined;
  to_connection_id?: number | undefined;
}

export interface CMsgSteamSockets_UDP_Stats {
  stats?: CMsgSteamDatagramConnectionQuality | undefined;
  flags?: number | undefined;
}

export const CMsgSteamSockets_UDP_Stats_Flags = {
  ACK_REQUEST_E2E: 2,
  ACK_REQUEST_IMMEDIATE: 4,
  NOT_PRIMARY_TRANSPORT_E2E: 16,
  UNRECOGNIZED: -1,
} as const;

export type CMsgSteamSockets_UDP_Stats_Flags =
  typeof CMsgSteamSockets_UDP_Stats_Flags[keyof typeof CMsgSteamSockets_UDP_Stats_Flags];

export namespace CMsgSteamSockets_UDP_Stats_Flags {
  export type ACK_REQUEST_E2E = typeof CMsgSteamSockets_UDP_Stats_Flags.ACK_REQUEST_E2E;
  export type ACK_REQUEST_IMMEDIATE = typeof CMsgSteamSockets_UDP_Stats_Flags.ACK_REQUEST_IMMEDIATE;
  export type NOT_PRIMARY_TRANSPORT_E2E = typeof CMsgSteamSockets_UDP_Stats_Flags.NOT_PRIMARY_TRANSPORT_E2E;
  export type UNRECOGNIZED = typeof CMsgSteamSockets_UDP_Stats_Flags.UNRECOGNIZED;
}

export function cMsgSteamSockets_UDP_Stats_FlagsFromJSON(object: any): CMsgSteamSockets_UDP_Stats_Flags {
  switch (object) {
    case 2:
    case "ACK_REQUEST_E2E":
      return CMsgSteamSockets_UDP_Stats_Flags.ACK_REQUEST_E2E;
    case 4:
    case "ACK_REQUEST_IMMEDIATE":
      return CMsgSteamSockets_UDP_Stats_Flags.ACK_REQUEST_IMMEDIATE;
    case 16:
    case "NOT_PRIMARY_TRANSPORT_E2E":
      return CMsgSteamSockets_UDP_Stats_Flags.NOT_PRIMARY_TRANSPORT_E2E;
    case -1:
    case "UNRECOGNIZED":
    default:
      return CMsgSteamSockets_UDP_Stats_Flags.UNRECOGNIZED;
  }
}

export function cMsgSteamSockets_UDP_Stats_FlagsToJSON(object: CMsgSteamSockets_UDP_Stats_Flags): string {
  switch (object) {
    case CMsgSteamSockets_UDP_Stats_Flags.ACK_REQUEST_E2E:
      return "ACK_REQUEST_E2E";
    case CMsgSteamSockets_UDP_Stats_Flags.ACK_REQUEST_IMMEDIATE:
      return "ACK_REQUEST_IMMEDIATE";
    case CMsgSteamSockets_UDP_Stats_Flags.NOT_PRIMARY_TRANSPORT_E2E:
      return "NOT_PRIMARY_TRANSPORT_E2E";
    case CMsgSteamSockets_UDP_Stats_Flags.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

function createBaseCMsgSteamSockets_UDP_ChallengeRequest(): CMsgSteamSockets_UDP_ChallengeRequest {
  return { connection_id: undefined, my_timestamp: undefined, protocol_version: undefined };
}

export const CMsgSteamSockets_UDP_ChallengeRequest: MessageFns<CMsgSteamSockets_UDP_ChallengeRequest> = {
  encode(message: CMsgSteamSockets_UDP_ChallengeRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.connection_id !== undefined) {
      writer.uint32(13).fixed32(message.connection_id);
    }
    if (message.my_timestamp !== undefined) {
      writer.uint32(25).fixed64(message.my_timestamp);
    }
    if (message.protocol_version !== undefined) {
      writer.uint32(32).uint32(message.protocol_version);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CMsgSteamSockets_UDP_ChallengeRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamSockets_UDP_ChallengeRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 13) {
            break;
          }

          message.connection_id = reader.fixed32();
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.my_timestamp = reader.fixed64().toString();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.protocol_version = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CMsgSteamSockets_UDP_ChallengeRequest {
    return {
      connection_id: isSet(object.connectionId)
        ? globalThis.Number(object.connectionId)
        : isSet(object.connection_id)
        ? globalThis.Number(object.connection_id)
        : undefined,
      my_timestamp: isSet(object.myTimestamp)
        ? globalThis.String(object.myTimestamp)
        : isSet(object.my_timestamp)
        ? globalThis.String(object.my_timestamp)
        : undefined,
      protocol_version: isSet(object.protocolVersion)
        ? globalThis.Number(object.protocolVersion)
        : isSet(object.protocol_version)
        ? globalThis.Number(object.protocol_version)
        : undefined,
    };
  },

  toJSON(message: CMsgSteamSockets_UDP_ChallengeRequest): unknown {
    const obj: any = {};
    if (message.connection_id !== undefined) {
      obj.connectionId = Math.round(message.connection_id);
    }
    if (message.my_timestamp !== undefined) {
      obj.myTimestamp = message.my_timestamp;
    }
    if (message.protocol_version !== undefined) {
      obj.protocolVersion = Math.round(message.protocol_version);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CMsgSteamSockets_UDP_ChallengeRequest>, I>>(
    base?: I,
  ): CMsgSteamSockets_UDP_ChallengeRequest {
    return CMsgSteamSockets_UDP_ChallengeRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CMsgSteamSockets_UDP_ChallengeRequest>, I>>(
    object: I,
  ): CMsgSteamSockets_UDP_ChallengeRequest {
    const message = createBaseCMsgSteamSockets_UDP_ChallengeRequest();
    message.connection_id = object.connection_id ?? undefined;
    message.my_timestamp = object.my_timestamp ?? undefined;
    message.protocol_version = object.protocol_version ?? undefined;
    return message;
  },
};

function createBaseCMsgSteamSockets_UDP_ChallengeReply(): CMsgSteamSockets_UDP_ChallengeReply {
  return { connection_id: undefined, challenge: undefined, your_timestamp: undefined, protocol_version: undefined };
}

export const CMsgSteamSockets_UDP_ChallengeReply: MessageFns<CMsgSteamSockets_UDP_ChallengeReply> = {
  encode(message: CMsgSteamSockets_UDP_ChallengeReply, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.connection_id !== undefined) {
      writer.uint32(13).fixed32(message.connection_id);
    }
    if (message.challenge !== undefined) {
      writer.uint32(17).fixed64(message.challenge);
    }
    if (message.your_timestamp !== undefined) {
      writer.uint32(25).fixed64(message.your_timestamp);
    }
    if (message.protocol_version !== undefined) {
      writer.uint32(32).uint32(message.protocol_version);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CMsgSteamSockets_UDP_ChallengeReply {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamSockets_UDP_ChallengeReply();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 13) {
            break;
          }

          message.connection_id = reader.fixed32();
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.challenge = reader.fixed64().toString();
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.your_timestamp = reader.fixed64().toString();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.protocol_version = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CMsgSteamSockets_UDP_ChallengeReply {
    return {
      connection_id: isSet(object.connectionId)
        ? globalThis.Number(object.connectionId)
        : isSet(object.connection_id)
        ? globalThis.Number(object.connection_id)
        : undefined,
      challenge: isSet(object.challenge) ? globalThis.String(object.challenge) : undefined,
      your_timestamp: isSet(object.yourTimestamp)
        ? globalThis.String(object.yourTimestamp)
        : isSet(object.your_timestamp)
        ? globalThis.String(object.your_timestamp)
        : undefined,
      protocol_version: isSet(object.protocolVersion)
        ? globalThis.Number(object.protocolVersion)
        : isSet(object.protocol_version)
        ? globalThis.Number(object.protocol_version)
        : undefined,
    };
  },

  toJSON(message: CMsgSteamSockets_UDP_ChallengeReply): unknown {
    const obj: any = {};
    if (message.connection_id !== undefined) {
      obj.connectionId = Math.round(message.connection_id);
    }
    if (message.challenge !== undefined) {
      obj.challenge = message.challenge;
    }
    if (message.your_timestamp !== undefined) {
      obj.yourTimestamp = message.your_timestamp;
    }
    if (message.protocol_version !== undefined) {
      obj.protocolVersion = Math.round(message.protocol_version);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CMsgSteamSockets_UDP_ChallengeReply>, I>>(
    base?: I,
  ): CMsgSteamSockets_UDP_ChallengeReply {
    return CMsgSteamSockets_UDP_ChallengeReply.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CMsgSteamSockets_UDP_ChallengeReply>, I>>(
    object: I,
  ): CMsgSteamSockets_UDP_ChallengeReply {
    const message = createBaseCMsgSteamSockets_UDP_ChallengeReply();
    message.connection_id = object.connection_id ?? undefined;
    message.challenge = object.challenge ?? undefined;
    message.your_timestamp = object.your_timestamp ?? undefined;
    message.protocol_version = object.protocol_version ?? undefined;
    return message;
  },
};

function createBaseCMsgSteamSockets_UDP_ConnectRequest(): CMsgSteamSockets_UDP_ConnectRequest {
  return {
    client_connection_id: undefined,
    challenge: undefined,
    my_timestamp: undefined,
    ping_est_ms: undefined,
    crypt: undefined,
    cert: undefined,
    legacy_protocol_version: undefined,
    identity_string: undefined,
    legacy_client_steam_id: undefined,
    legacy_identity_binary: undefined,
  };
}

export const CMsgSteamSockets_UDP_ConnectRequest: MessageFns<CMsgSteamSockets_UDP_ConnectRequest> = {
  encode(message: CMsgSteamSockets_UDP_ConnectRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.client_connection_id !== undefined) {
      writer.uint32(13).fixed32(message.client_connection_id);
    }
    if (message.challenge !== undefined) {
      writer.uint32(17).fixed64(message.challenge);
    }
    if (message.my_timestamp !== undefined) {
      writer.uint32(41).fixed64(message.my_timestamp);
    }
    if (message.ping_est_ms !== undefined) {
      writer.uint32(48).uint32(message.ping_est_ms);
    }
    if (message.crypt !== undefined) {
      CMsgSteamDatagramSessionCryptInfoSigned.encode(message.crypt, writer.uint32(58).fork()).join();
    }
    if (message.cert !== undefined) {
      CMsgSteamDatagramCertificateSigned.encode(message.cert, writer.uint32(34).fork()).join();
    }
    if (message.legacy_protocol_version !== undefined) {
      writer.uint32(64).uint32(message.legacy_protocol_version);
    }
    if (message.identity_string !== undefined) {
      writer.uint32(82).string(message.identity_string);
    }
    if (message.legacy_client_steam_id !== undefined) {
      writer.uint32(25).fixed64(message.legacy_client_steam_id);
    }
    if (message.legacy_identity_binary !== undefined) {
      CMsgSteamNetworkingIdentityLegacyBinary.encode(message.legacy_identity_binary, writer.uint32(74).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CMsgSteamSockets_UDP_ConnectRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamSockets_UDP_ConnectRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 13) {
            break;
          }

          message.client_connection_id = reader.fixed32();
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.challenge = reader.fixed64().toString();
          continue;
        }
        case 5: {
          if (tag !== 41) {
            break;
          }

          message.my_timestamp = reader.fixed64().toString();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.ping_est_ms = reader.uint32();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.crypt = CMsgSteamDatagramSessionCryptInfoSigned.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.cert = CMsgSteamDatagramCertificateSigned.decode(reader, reader.uint32());
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.legacy_protocol_version = reader.uint32();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.identity_string = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.legacy_client_steam_id = reader.fixed64().toString();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.legacy_identity_binary = CMsgSteamNetworkingIdentityLegacyBinary.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CMsgSteamSockets_UDP_ConnectRequest {
    return {
      client_connection_id: isSet(object.clientConnectionId)
        ? globalThis.Number(object.clientConnectionId)
        : isSet(object.client_connection_id)
        ? globalThis.Number(object.client_connection_id)
        : undefined,
      challenge: isSet(object.challenge) ? globalThis.String(object.challenge) : undefined,
      my_timestamp: isSet(object.myTimestamp)
        ? globalThis.String(object.myTimestamp)
        : isSet(object.my_timestamp)
        ? globalThis.String(object.my_timestamp)
        : undefined,
      ping_est_ms: isSet(object.pingEstMs)
        ? globalThis.Number(object.pingEstMs)
        : isSet(object.ping_est_ms)
        ? globalThis.Number(object.ping_est_ms)
        : undefined,
      crypt: isSet(object.crypt) ? CMsgSteamDatagramSessionCryptInfoSigned.fromJSON(object.crypt) : undefined,
      cert: isSet(object.cert) ? CMsgSteamDatagramCertificateSigned.fromJSON(object.cert) : undefined,
      legacy_protocol_version: isSet(object.legacyProtocolVersion)
        ? globalThis.Number(object.legacyProtocolVersion)
        : isSet(object.legacy_protocol_version)
        ? globalThis.Number(object.legacy_protocol_version)
        : undefined,
      identity_string: isSet(object.identityString)
        ? globalThis.String(object.identityString)
        : isSet(object.identity_string)
        ? globalThis.String(object.identity_string)
        : undefined,
      legacy_client_steam_id: isSet(object.legacyClientSteamId)
        ? globalThis.String(object.legacyClientSteamId)
        : isSet(object.legacy_client_steam_id)
        ? globalThis.String(object.legacy_client_steam_id)
        : undefined,
      legacy_identity_binary: isSet(object.legacyIdentityBinary)
        ? CMsgSteamNetworkingIdentityLegacyBinary.fromJSON(object.legacyIdentityBinary)
        : isSet(object.legacy_identity_binary)
        ? CMsgSteamNetworkingIdentityLegacyBinary.fromJSON(object.legacy_identity_binary)
        : undefined,
    };
  },

  toJSON(message: CMsgSteamSockets_UDP_ConnectRequest): unknown {
    const obj: any = {};
    if (message.client_connection_id !== undefined) {
      obj.clientConnectionId = Math.round(message.client_connection_id);
    }
    if (message.challenge !== undefined) {
      obj.challenge = message.challenge;
    }
    if (message.my_timestamp !== undefined) {
      obj.myTimestamp = message.my_timestamp;
    }
    if (message.ping_est_ms !== undefined) {
      obj.pingEstMs = Math.round(message.ping_est_ms);
    }
    if (message.crypt !== undefined) {
      obj.crypt = CMsgSteamDatagramSessionCryptInfoSigned.toJSON(message.crypt);
    }
    if (message.cert !== undefined) {
      obj.cert = CMsgSteamDatagramCertificateSigned.toJSON(message.cert);
    }
    if (message.legacy_protocol_version !== undefined) {
      obj.legacyProtocolVersion = Math.round(message.legacy_protocol_version);
    }
    if (message.identity_string !== undefined) {
      obj.identityString = message.identity_string;
    }
    if (message.legacy_client_steam_id !== undefined) {
      obj.legacyClientSteamId = message.legacy_client_steam_id;
    }
    if (message.legacy_identity_binary !== undefined) {
      obj.legacyIdentityBinary = CMsgSteamNetworkingIdentityLegacyBinary.toJSON(message.legacy_identity_binary);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CMsgSteamSockets_UDP_ConnectRequest>, I>>(
    base?: I,
  ): CMsgSteamSockets_UDP_ConnectRequest {
    return CMsgSteamSockets_UDP_ConnectRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CMsgSteamSockets_UDP_ConnectRequest>, I>>(
    object: I,
  ): CMsgSteamSockets_UDP_ConnectRequest {
    const message = createBaseCMsgSteamSockets_UDP_ConnectRequest();
    message.client_connection_id = object.client_connection_id ?? undefined;
    message.challenge = object.challenge ?? undefined;
    message.my_timestamp = object.my_timestamp ?? undefined;
    message.ping_est_ms = object.ping_est_ms ?? undefined;
    message.crypt = (object.crypt !== undefined && object.crypt !== null)
      ? CMsgSteamDatagramSessionCryptInfoSigned.fromPartial(object.crypt)
      : undefined;
    message.cert = (object.cert !== undefined && object.cert !== null)
      ? CMsgSteamDatagramCertificateSigned.fromPartial(object.cert)
      : undefined;
    message.legacy_protocol_version = object.legacy_protocol_version ?? undefined;
    message.identity_string = object.identity_string ?? undefined;
    message.legacy_client_steam_id = object.legacy_client_steam_id ?? undefined;
    message.legacy_identity_binary =
      (object.legacy_identity_binary !== undefined && object.legacy_identity_binary !== null)
        ? CMsgSteamNetworkingIdentityLegacyBinary.fromPartial(object.legacy_identity_binary)
        : undefined;
    return message;
  },
};

function createBaseCMsgSteamSockets_UDP_ConnectOK(): CMsgSteamSockets_UDP_ConnectOK {
  return {
    client_connection_id: undefined,
    server_connection_id: undefined,
    your_timestamp: undefined,
    delay_time_usec: undefined,
    crypt: undefined,
    cert: undefined,
    identity_string: undefined,
    legacy_server_steam_id: undefined,
    legacy_identity_binary: undefined,
  };
}

export const CMsgSteamSockets_UDP_ConnectOK: MessageFns<CMsgSteamSockets_UDP_ConnectOK> = {
  encode(message: CMsgSteamSockets_UDP_ConnectOK, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.client_connection_id !== undefined) {
      writer.uint32(13).fixed32(message.client_connection_id);
    }
    if (message.server_connection_id !== undefined) {
      writer.uint32(45).fixed32(message.server_connection_id);
    }
    if (message.your_timestamp !== undefined) {
      writer.uint32(25).fixed64(message.your_timestamp);
    }
    if (message.delay_time_usec !== undefined) {
      writer.uint32(32).uint32(message.delay_time_usec);
    }
    if (message.crypt !== undefined) {
      CMsgSteamDatagramSessionCryptInfoSigned.encode(message.crypt, writer.uint32(58).fork()).join();
    }
    if (message.cert !== undefined) {
      CMsgSteamDatagramCertificateSigned.encode(message.cert, writer.uint32(66).fork()).join();
    }
    if (message.identity_string !== undefined) {
      writer.uint32(90).string(message.identity_string);
    }
    if (message.legacy_server_steam_id !== undefined) {
      writer.uint32(17).fixed64(message.legacy_server_steam_id);
    }
    if (message.legacy_identity_binary !== undefined) {
      CMsgSteamNetworkingIdentityLegacyBinary.encode(message.legacy_identity_binary, writer.uint32(82).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CMsgSteamSockets_UDP_ConnectOK {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamSockets_UDP_ConnectOK();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 13) {
            break;
          }

          message.client_connection_id = reader.fixed32();
          continue;
        }
        case 5: {
          if (tag !== 45) {
            break;
          }

          message.server_connection_id = reader.fixed32();
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.your_timestamp = reader.fixed64().toString();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.delay_time_usec = reader.uint32();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.crypt = CMsgSteamDatagramSessionCryptInfoSigned.decode(reader, reader.uint32());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.cert = CMsgSteamDatagramCertificateSigned.decode(reader, reader.uint32());
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.identity_string = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.legacy_server_steam_id = reader.fixed64().toString();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.legacy_identity_binary = CMsgSteamNetworkingIdentityLegacyBinary.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CMsgSteamSockets_UDP_ConnectOK {
    return {
      client_connection_id: isSet(object.clientConnectionId)
        ? globalThis.Number(object.clientConnectionId)
        : isSet(object.client_connection_id)
        ? globalThis.Number(object.client_connection_id)
        : undefined,
      server_connection_id: isSet(object.serverConnectionId)
        ? globalThis.Number(object.serverConnectionId)
        : isSet(object.server_connection_id)
        ? globalThis.Number(object.server_connection_id)
        : undefined,
      your_timestamp: isSet(object.yourTimestamp)
        ? globalThis.String(object.yourTimestamp)
        : isSet(object.your_timestamp)
        ? globalThis.String(object.your_timestamp)
        : undefined,
      delay_time_usec: isSet(object.delayTimeUsec)
        ? globalThis.Number(object.delayTimeUsec)
        : isSet(object.delay_time_usec)
        ? globalThis.Number(object.delay_time_usec)
        : undefined,
      crypt: isSet(object.crypt) ? CMsgSteamDatagramSessionCryptInfoSigned.fromJSON(object.crypt) : undefined,
      cert: isSet(object.cert) ? CMsgSteamDatagramCertificateSigned.fromJSON(object.cert) : undefined,
      identity_string: isSet(object.identityString)
        ? globalThis.String(object.identityString)
        : isSet(object.identity_string)
        ? globalThis.String(object.identity_string)
        : undefined,
      legacy_server_steam_id: isSet(object.legacyServerSteamId)
        ? globalThis.String(object.legacyServerSteamId)
        : isSet(object.legacy_server_steam_id)
        ? globalThis.String(object.legacy_server_steam_id)
        : undefined,
      legacy_identity_binary: isSet(object.legacyIdentityBinary)
        ? CMsgSteamNetworkingIdentityLegacyBinary.fromJSON(object.legacyIdentityBinary)
        : isSet(object.legacy_identity_binary)
        ? CMsgSteamNetworkingIdentityLegacyBinary.fromJSON(object.legacy_identity_binary)
        : undefined,
    };
  },

  toJSON(message: CMsgSteamSockets_UDP_ConnectOK): unknown {
    const obj: any = {};
    if (message.client_connection_id !== undefined) {
      obj.clientConnectionId = Math.round(message.client_connection_id);
    }
    if (message.server_connection_id !== undefined) {
      obj.serverConnectionId = Math.round(message.server_connection_id);
    }
    if (message.your_timestamp !== undefined) {
      obj.yourTimestamp = message.your_timestamp;
    }
    if (message.delay_time_usec !== undefined) {
      obj.delayTimeUsec = Math.round(message.delay_time_usec);
    }
    if (message.crypt !== undefined) {
      obj.crypt = CMsgSteamDatagramSessionCryptInfoSigned.toJSON(message.crypt);
    }
    if (message.cert !== undefined) {
      obj.cert = CMsgSteamDatagramCertificateSigned.toJSON(message.cert);
    }
    if (message.identity_string !== undefined) {
      obj.identityString = message.identity_string;
    }
    if (message.legacy_server_steam_id !== undefined) {
      obj.legacyServerSteamId = message.legacy_server_steam_id;
    }
    if (message.legacy_identity_binary !== undefined) {
      obj.legacyIdentityBinary = CMsgSteamNetworkingIdentityLegacyBinary.toJSON(message.legacy_identity_binary);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CMsgSteamSockets_UDP_ConnectOK>, I>>(base?: I): CMsgSteamSockets_UDP_ConnectOK {
    return CMsgSteamSockets_UDP_ConnectOK.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CMsgSteamSockets_UDP_ConnectOK>, I>>(
    object: I,
  ): CMsgSteamSockets_UDP_ConnectOK {
    const message = createBaseCMsgSteamSockets_UDP_ConnectOK();
    message.client_connection_id = object.client_connection_id ?? undefined;
    message.server_connection_id = object.server_connection_id ?? undefined;
    message.your_timestamp = object.your_timestamp ?? undefined;
    message.delay_time_usec = object.delay_time_usec ?? undefined;
    message.crypt = (object.crypt !== undefined && object.crypt !== null)
      ? CMsgSteamDatagramSessionCryptInfoSigned.fromPartial(object.crypt)
      : undefined;
    message.cert = (object.cert !== undefined && object.cert !== null)
      ? CMsgSteamDatagramCertificateSigned.fromPartial(object.cert)
      : undefined;
    message.identity_string = object.identity_string ?? undefined;
    message.legacy_server_steam_id = object.legacy_server_steam_id ?? undefined;
    message.legacy_identity_binary =
      (object.legacy_identity_binary !== undefined && object.legacy_identity_binary !== null)
        ? CMsgSteamNetworkingIdentityLegacyBinary.fromPartial(object.legacy_identity_binary)
        : undefined;
    return message;
  },
};

function createBaseCMsgSteamSockets_UDP_ConnectionClosed(): CMsgSteamSockets_UDP_ConnectionClosed {
  return { to_connection_id: undefined, from_connection_id: undefined, debug: undefined, reason_code: undefined };
}

export const CMsgSteamSockets_UDP_ConnectionClosed: MessageFns<CMsgSteamSockets_UDP_ConnectionClosed> = {
  encode(message: CMsgSteamSockets_UDP_ConnectionClosed, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.to_connection_id !== undefined) {
      writer.uint32(37).fixed32(message.to_connection_id);
    }
    if (message.from_connection_id !== undefined) {
      writer.uint32(45).fixed32(message.from_connection_id);
    }
    if (message.debug !== undefined) {
      writer.uint32(18).string(message.debug);
    }
    if (message.reason_code !== undefined) {
      writer.uint32(24).uint32(message.reason_code);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CMsgSteamSockets_UDP_ConnectionClosed {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamSockets_UDP_ConnectionClosed();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 4: {
          if (tag !== 37) {
            break;
          }

          message.to_connection_id = reader.fixed32();
          continue;
        }
        case 5: {
          if (tag !== 45) {
            break;
          }

          message.from_connection_id = reader.fixed32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.debug = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.reason_code = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CMsgSteamSockets_UDP_ConnectionClosed {
    return {
      to_connection_id: isSet(object.toConnectionId)
        ? globalThis.Number(object.toConnectionId)
        : isSet(object.to_connection_id)
        ? globalThis.Number(object.to_connection_id)
        : undefined,
      from_connection_id: isSet(object.fromConnectionId)
        ? globalThis.Number(object.fromConnectionId)
        : isSet(object.from_connection_id)
        ? globalThis.Number(object.from_connection_id)
        : undefined,
      debug: isSet(object.debug) ? globalThis.String(object.debug) : undefined,
      reason_code: isSet(object.reasonCode)
        ? globalThis.Number(object.reasonCode)
        : isSet(object.reason_code)
        ? globalThis.Number(object.reason_code)
        : undefined,
    };
  },

  toJSON(message: CMsgSteamSockets_UDP_ConnectionClosed): unknown {
    const obj: any = {};
    if (message.to_connection_id !== undefined) {
      obj.toConnectionId = Math.round(message.to_connection_id);
    }
    if (message.from_connection_id !== undefined) {
      obj.fromConnectionId = Math.round(message.from_connection_id);
    }
    if (message.debug !== undefined) {
      obj.debug = message.debug;
    }
    if (message.reason_code !== undefined) {
      obj.reasonCode = Math.round(message.reason_code);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CMsgSteamSockets_UDP_ConnectionClosed>, I>>(
    base?: I,
  ): CMsgSteamSockets_UDP_ConnectionClosed {
    return CMsgSteamSockets_UDP_ConnectionClosed.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CMsgSteamSockets_UDP_ConnectionClosed>, I>>(
    object: I,
  ): CMsgSteamSockets_UDP_ConnectionClosed {
    const message = createBaseCMsgSteamSockets_UDP_ConnectionClosed();
    message.to_connection_id = object.to_connection_id ?? undefined;
    message.from_connection_id = object.from_connection_id ?? undefined;
    message.debug = object.debug ?? undefined;
    message.reason_code = object.reason_code ?? undefined;
    return message;
  },
};

function createBaseCMsgSteamSockets_UDP_NoConnection(): CMsgSteamSockets_UDP_NoConnection {
  return { from_connection_id: undefined, to_connection_id: undefined };
}

export const CMsgSteamSockets_UDP_NoConnection: MessageFns<CMsgSteamSockets_UDP_NoConnection> = {
  encode(message: CMsgSteamSockets_UDP_NoConnection, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.from_connection_id !== undefined) {
      writer.uint32(21).fixed32(message.from_connection_id);
    }
    if (message.to_connection_id !== undefined) {
      writer.uint32(29).fixed32(message.to_connection_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CMsgSteamSockets_UDP_NoConnection {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamSockets_UDP_NoConnection();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2: {
          if (tag !== 21) {
            break;
          }

          message.from_connection_id = reader.fixed32();
          continue;
        }
        case 3: {
          if (tag !== 29) {
            break;
          }

          message.to_connection_id = reader.fixed32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CMsgSteamSockets_UDP_NoConnection {
    return {
      from_connection_id: isSet(object.fromConnectionId)
        ? globalThis.Number(object.fromConnectionId)
        : isSet(object.from_connection_id)
        ? globalThis.Number(object.from_connection_id)
        : undefined,
      to_connection_id: isSet(object.toConnectionId)
        ? globalThis.Number(object.toConnectionId)
        : isSet(object.to_connection_id)
        ? globalThis.Number(object.to_connection_id)
        : undefined,
    };
  },

  toJSON(message: CMsgSteamSockets_UDP_NoConnection): unknown {
    const obj: any = {};
    if (message.from_connection_id !== undefined) {
      obj.fromConnectionId = Math.round(message.from_connection_id);
    }
    if (message.to_connection_id !== undefined) {
      obj.toConnectionId = Math.round(message.to_connection_id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CMsgSteamSockets_UDP_NoConnection>, I>>(
    base?: I,
  ): CMsgSteamSockets_UDP_NoConnection {
    return CMsgSteamSockets_UDP_NoConnection.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CMsgSteamSockets_UDP_NoConnection>, I>>(
    object: I,
  ): CMsgSteamSockets_UDP_NoConnection {
    const message = createBaseCMsgSteamSockets_UDP_NoConnection();
    message.from_connection_id = object.from_connection_id ?? undefined;
    message.to_connection_id = object.to_connection_id ?? undefined;
    return message;
  },
};

function createBaseCMsgSteamSockets_UDP_Stats(): CMsgSteamSockets_UDP_Stats {
  return { stats: undefined, flags: undefined };
}

export const CMsgSteamSockets_UDP_Stats: MessageFns<CMsgSteamSockets_UDP_Stats> = {
  encode(message: CMsgSteamSockets_UDP_Stats, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.stats !== undefined) {
      CMsgSteamDatagramConnectionQuality.encode(message.stats, writer.uint32(10).fork()).join();
    }
    if (message.flags !== undefined) {
      writer.uint32(24).uint32(message.flags);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CMsgSteamSockets_UDP_Stats {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamSockets_UDP_Stats();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.stats = CMsgSteamDatagramConnectionQuality.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.flags = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CMsgSteamSockets_UDP_Stats {
    return {
      stats: isSet(object.stats) ? CMsgSteamDatagramConnectionQuality.fromJSON(object.stats) : undefined,
      flags: isSet(object.flags) ? globalThis.Number(object.flags) : undefined,
    };
  },

  toJSON(message: CMsgSteamSockets_UDP_Stats): unknown {
    const obj: any = {};
    if (message.stats !== undefined) {
      obj.stats = CMsgSteamDatagramConnectionQuality.toJSON(message.stats);
    }
    if (message.flags !== undefined) {
      obj.flags = Math.round(message.flags);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CMsgSteamSockets_UDP_Stats>, I>>(base?: I): CMsgSteamSockets_UDP_Stats {
    return CMsgSteamSockets_UDP_Stats.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CMsgSteamSockets_UDP_Stats>, I>>(object: I): CMsgSteamSockets_UDP_Stats {
    const message = createBaseCMsgSteamSockets_UDP_Stats();
    message.stats = (object.stats !== undefined && object.stats !== null)
      ? CMsgSteamDatagramConnectionQuality.fromPartial(object.stats)
      : undefined;
    message.flags = object.flags ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
