// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.1
// source: steammessages.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "";

export const GCProtoBufMsgSrc = {
  GCProtoBufMsgSrc_Unspecified: 0,
  GCProtoBufMsgSrc_FromSystem: 1,
  GCProtoBufMsgSrc_FromSteamID: 2,
  GCProtoBufMsgSrc_FromGC: 3,
  GCProtoBufMsgSrc_ReplySystem: 4,
  UNRECOGNIZED: -1,
} as const;

export type GCProtoBufMsgSrc = typeof GCProtoBufMsgSrc[keyof typeof GCProtoBufMsgSrc];

export namespace GCProtoBufMsgSrc {
  export type GCProtoBufMsgSrc_Unspecified = typeof GCProtoBufMsgSrc.GCProtoBufMsgSrc_Unspecified;
  export type GCProtoBufMsgSrc_FromSystem = typeof GCProtoBufMsgSrc.GCProtoBufMsgSrc_FromSystem;
  export type GCProtoBufMsgSrc_FromSteamID = typeof GCProtoBufMsgSrc.GCProtoBufMsgSrc_FromSteamID;
  export type GCProtoBufMsgSrc_FromGC = typeof GCProtoBufMsgSrc.GCProtoBufMsgSrc_FromGC;
  export type GCProtoBufMsgSrc_ReplySystem = typeof GCProtoBufMsgSrc.GCProtoBufMsgSrc_ReplySystem;
  export type UNRECOGNIZED = typeof GCProtoBufMsgSrc.UNRECOGNIZED;
}

export function gCProtoBufMsgSrcFromJSON(object: any): GCProtoBufMsgSrc {
  switch (object) {
    case 0:
    case "GCProtoBufMsgSrc_Unspecified":
      return GCProtoBufMsgSrc.GCProtoBufMsgSrc_Unspecified;
    case 1:
    case "GCProtoBufMsgSrc_FromSystem":
      return GCProtoBufMsgSrc.GCProtoBufMsgSrc_FromSystem;
    case 2:
    case "GCProtoBufMsgSrc_FromSteamID":
      return GCProtoBufMsgSrc.GCProtoBufMsgSrc_FromSteamID;
    case 3:
    case "GCProtoBufMsgSrc_FromGC":
      return GCProtoBufMsgSrc.GCProtoBufMsgSrc_FromGC;
    case 4:
    case "GCProtoBufMsgSrc_ReplySystem":
      return GCProtoBufMsgSrc.GCProtoBufMsgSrc_ReplySystem;
    case -1:
    case "UNRECOGNIZED":
    default:
      return GCProtoBufMsgSrc.UNRECOGNIZED;
  }
}

export function gCProtoBufMsgSrcToJSON(object: GCProtoBufMsgSrc): string {
  switch (object) {
    case GCProtoBufMsgSrc.GCProtoBufMsgSrc_Unspecified:
      return "GCProtoBufMsgSrc_Unspecified";
    case GCProtoBufMsgSrc.GCProtoBufMsgSrc_FromSystem:
      return "GCProtoBufMsgSrc_FromSystem";
    case GCProtoBufMsgSrc.GCProtoBufMsgSrc_FromSteamID:
      return "GCProtoBufMsgSrc_FromSteamID";
    case GCProtoBufMsgSrc.GCProtoBufMsgSrc_FromGC:
      return "GCProtoBufMsgSrc_FromGC";
    case GCProtoBufMsgSrc.GCProtoBufMsgSrc_ReplySystem:
      return "GCProtoBufMsgSrc_ReplySystem";
    case GCProtoBufMsgSrc.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface CMsgProtoBufHeader {
  client_steam_id?: string | undefined;
  client_session_id?: number | undefined;
  source_app_id?: number | undefined;
  job_id_source?: string | undefined;
  job_id_target?: string | undefined;
  target_job_name?: string | undefined;
  eresult?: number | undefined;
  error_message?: string | undefined;
  ip?: number | undefined;
  gc_msg_src?: GCProtoBufMsgSrc | undefined;
  gc_dir_index_source?: number | undefined;
}

export interface CChinaAgreementSessions_StartAgreementSessionInGame_Request {
  appid?: number | undefined;
  steamid?: string | undefined;
  client_ipaddress?: string | undefined;
}

export interface CChinaAgreementSessions_StartAgreementSessionInGame_Response {
  agreement_url?: string | undefined;
}

function createBaseCMsgProtoBufHeader(): CMsgProtoBufHeader {
  return {
    client_steam_id: undefined,
    client_session_id: undefined,
    source_app_id: undefined,
    job_id_source: undefined,
    job_id_target: undefined,
    target_job_name: undefined,
    eresult: undefined,
    error_message: undefined,
    ip: undefined,
    gc_msg_src: undefined,
    gc_dir_index_source: undefined,
  };
}

export const CMsgProtoBufHeader: MessageFns<CMsgProtoBufHeader> = {
  encode(message: CMsgProtoBufHeader, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.client_steam_id !== undefined) {
      writer.uint32(9).fixed64(message.client_steam_id);
    }
    if (message.client_session_id !== undefined) {
      writer.uint32(16).int32(message.client_session_id);
    }
    if (message.source_app_id !== undefined) {
      writer.uint32(24).uint32(message.source_app_id);
    }
    if (message.job_id_source !== undefined) {
      writer.uint32(81).fixed64(message.job_id_source);
    }
    if (message.job_id_target !== undefined) {
      writer.uint32(89).fixed64(message.job_id_target);
    }
    if (message.target_job_name !== undefined) {
      writer.uint32(98).string(message.target_job_name);
    }
    if (message.eresult !== undefined) {
      writer.uint32(104).int32(message.eresult);
    }
    if (message.error_message !== undefined) {
      writer.uint32(114).string(message.error_message);
    }
    if (message.ip !== undefined) {
      writer.uint32(120).uint32(message.ip);
    }
    if (message.gc_msg_src !== undefined) {
      writer.uint32(1600).int32(message.gc_msg_src);
    }
    if (message.gc_dir_index_source !== undefined) {
      writer.uint32(1608).uint32(message.gc_dir_index_source);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CMsgProtoBufHeader {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgProtoBufHeader();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 9) {
            break;
          }

          message.client_steam_id = reader.fixed64().toString();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.client_session_id = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.source_app_id = reader.uint32();
          continue;
        }
        case 10: {
          if (tag !== 81) {
            break;
          }

          message.job_id_source = reader.fixed64().toString();
          continue;
        }
        case 11: {
          if (tag !== 89) {
            break;
          }

          message.job_id_target = reader.fixed64().toString();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.target_job_name = reader.string();
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.eresult = reader.int32();
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.error_message = reader.string();
          continue;
        }
        case 15: {
          if (tag !== 120) {
            break;
          }

          message.ip = reader.uint32();
          continue;
        }
        case 200: {
          if (tag !== 1600) {
            break;
          }

          message.gc_msg_src = reader.int32() as any;
          continue;
        }
        case 201: {
          if (tag !== 1608) {
            break;
          }

          message.gc_dir_index_source = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CMsgProtoBufHeader {
    return {
      client_steam_id: isSet(object.clientSteamId)
        ? globalThis.String(object.clientSteamId)
        : isSet(object.client_steam_id)
        ? globalThis.String(object.client_steam_id)
        : undefined,
      client_session_id: isSet(object.clientSessionId)
        ? globalThis.Number(object.clientSessionId)
        : isSet(object.client_session_id)
        ? globalThis.Number(object.client_session_id)
        : undefined,
      source_app_id: isSet(object.sourceAppId)
        ? globalThis.Number(object.sourceAppId)
        : isSet(object.source_app_id)
        ? globalThis.Number(object.source_app_id)
        : undefined,
      job_id_source: isSet(object.jobIdSource)
        ? globalThis.String(object.jobIdSource)
        : isSet(object.job_id_source)
        ? globalThis.String(object.job_id_source)
        : undefined,
      job_id_target: isSet(object.jobIdTarget)
        ? globalThis.String(object.jobIdTarget)
        : isSet(object.job_id_target)
        ? globalThis.String(object.job_id_target)
        : undefined,
      target_job_name: isSet(object.targetJobName)
        ? globalThis.String(object.targetJobName)
        : isSet(object.target_job_name)
        ? globalThis.String(object.target_job_name)
        : undefined,
      eresult: isSet(object.eresult) ? globalThis.Number(object.eresult) : undefined,
      error_message: isSet(object.errorMessage)
        ? globalThis.String(object.errorMessage)
        : isSet(object.error_message)
        ? globalThis.String(object.error_message)
        : undefined,
      ip: isSet(object.ip) ? globalThis.Number(object.ip) : undefined,
      gc_msg_src: isSet(object.gcMsgSrc)
        ? gCProtoBufMsgSrcFromJSON(object.gcMsgSrc)
        : isSet(object.gc_msg_src)
        ? gCProtoBufMsgSrcFromJSON(object.gc_msg_src)
        : undefined,
      gc_dir_index_source: isSet(object.gcDirIndexSource)
        ? globalThis.Number(object.gcDirIndexSource)
        : isSet(object.gc_dir_index_source)
        ? globalThis.Number(object.gc_dir_index_source)
        : undefined,
    };
  },

  toJSON(message: CMsgProtoBufHeader): unknown {
    const obj: any = {};
    if (message.client_steam_id !== undefined) {
      obj.clientSteamId = message.client_steam_id;
    }
    if (message.client_session_id !== undefined) {
      obj.clientSessionId = Math.round(message.client_session_id);
    }
    if (message.source_app_id !== undefined) {
      obj.sourceAppId = Math.round(message.source_app_id);
    }
    if (message.job_id_source !== undefined) {
      obj.jobIdSource = message.job_id_source;
    }
    if (message.job_id_target !== undefined) {
      obj.jobIdTarget = message.job_id_target;
    }
    if (message.target_job_name !== undefined) {
      obj.targetJobName = message.target_job_name;
    }
    if (message.eresult !== undefined) {
      obj.eresult = Math.round(message.eresult);
    }
    if (message.error_message !== undefined) {
      obj.errorMessage = message.error_message;
    }
    if (message.ip !== undefined) {
      obj.ip = Math.round(message.ip);
    }
    if (message.gc_msg_src !== undefined) {
      obj.gcMsgSrc = gCProtoBufMsgSrcToJSON(message.gc_msg_src);
    }
    if (message.gc_dir_index_source !== undefined) {
      obj.gcDirIndexSource = Math.round(message.gc_dir_index_source);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CMsgProtoBufHeader>, I>>(base?: I): CMsgProtoBufHeader {
    return CMsgProtoBufHeader.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CMsgProtoBufHeader>, I>>(object: I): CMsgProtoBufHeader {
    const message = createBaseCMsgProtoBufHeader();
    message.client_steam_id = object.client_steam_id ?? undefined;
    message.client_session_id = object.client_session_id ?? undefined;
    message.source_app_id = object.source_app_id ?? undefined;
    message.job_id_source = object.job_id_source ?? undefined;
    message.job_id_target = object.job_id_target ?? undefined;
    message.target_job_name = object.target_job_name ?? undefined;
    message.eresult = object.eresult ?? undefined;
    message.error_message = object.error_message ?? undefined;
    message.ip = object.ip ?? undefined;
    message.gc_msg_src = object.gc_msg_src ?? undefined;
    message.gc_dir_index_source = object.gc_dir_index_source ?? undefined;
    return message;
  },
};

function createBaseCChinaAgreementSessions_StartAgreementSessionInGame_Request(): CChinaAgreementSessions_StartAgreementSessionInGame_Request {
  return { appid: undefined, steamid: undefined, client_ipaddress: undefined };
}

export const CChinaAgreementSessions_StartAgreementSessionInGame_Request: MessageFns<
  CChinaAgreementSessions_StartAgreementSessionInGame_Request
> = {
  encode(
    message: CChinaAgreementSessions_StartAgreementSessionInGame_Request,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.appid !== undefined) {
      writer.uint32(8).uint32(message.appid);
    }
    if (message.steamid !== undefined) {
      writer.uint32(17).fixed64(message.steamid);
    }
    if (message.client_ipaddress !== undefined) {
      writer.uint32(26).string(message.client_ipaddress);
    }
    return writer;
  },

  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): CChinaAgreementSessions_StartAgreementSessionInGame_Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCChinaAgreementSessions_StartAgreementSessionInGame_Request();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.appid = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.steamid = reader.fixed64().toString();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.client_ipaddress = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CChinaAgreementSessions_StartAgreementSessionInGame_Request {
    return {
      appid: isSet(object.appid) ? globalThis.Number(object.appid) : undefined,
      steamid: isSet(object.steamid) ? globalThis.String(object.steamid) : undefined,
      client_ipaddress: isSet(object.clientIpaddress)
        ? globalThis.String(object.clientIpaddress)
        : isSet(object.client_ipaddress)
        ? globalThis.String(object.client_ipaddress)
        : undefined,
    };
  },

  toJSON(message: CChinaAgreementSessions_StartAgreementSessionInGame_Request): unknown {
    const obj: any = {};
    if (message.appid !== undefined) {
      obj.appid = Math.round(message.appid);
    }
    if (message.steamid !== undefined) {
      obj.steamid = message.steamid;
    }
    if (message.client_ipaddress !== undefined) {
      obj.clientIpaddress = message.client_ipaddress;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CChinaAgreementSessions_StartAgreementSessionInGame_Request>, I>>(
    base?: I,
  ): CChinaAgreementSessions_StartAgreementSessionInGame_Request {
    return CChinaAgreementSessions_StartAgreementSessionInGame_Request.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CChinaAgreementSessions_StartAgreementSessionInGame_Request>, I>>(
    object: I,
  ): CChinaAgreementSessions_StartAgreementSessionInGame_Request {
    const message = createBaseCChinaAgreementSessions_StartAgreementSessionInGame_Request();
    message.appid = object.appid ?? undefined;
    message.steamid = object.steamid ?? undefined;
    message.client_ipaddress = object.client_ipaddress ?? undefined;
    return message;
  },
};

function createBaseCChinaAgreementSessions_StartAgreementSessionInGame_Response(): CChinaAgreementSessions_StartAgreementSessionInGame_Response {
  return { agreement_url: undefined };
}

export const CChinaAgreementSessions_StartAgreementSessionInGame_Response: MessageFns<
  CChinaAgreementSessions_StartAgreementSessionInGame_Response
> = {
  encode(
    message: CChinaAgreementSessions_StartAgreementSessionInGame_Response,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.agreement_url !== undefined) {
      writer.uint32(10).string(message.agreement_url);
    }
    return writer;
  },

  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): CChinaAgreementSessions_StartAgreementSessionInGame_Response {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCChinaAgreementSessions_StartAgreementSessionInGame_Response();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.agreement_url = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CChinaAgreementSessions_StartAgreementSessionInGame_Response {
    return {
      agreement_url: isSet(object.agreementUrl)
        ? globalThis.String(object.agreementUrl)
        : isSet(object.agreement_url)
        ? globalThis.String(object.agreement_url)
        : undefined,
    };
  },

  toJSON(message: CChinaAgreementSessions_StartAgreementSessionInGame_Response): unknown {
    const obj: any = {};
    if (message.agreement_url !== undefined) {
      obj.agreementUrl = message.agreement_url;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CChinaAgreementSessions_StartAgreementSessionInGame_Response>, I>>(
    base?: I,
  ): CChinaAgreementSessions_StartAgreementSessionInGame_Response {
    return CChinaAgreementSessions_StartAgreementSessionInGame_Response.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CChinaAgreementSessions_StartAgreementSessionInGame_Response>, I>>(
    object: I,
  ): CChinaAgreementSessions_StartAgreementSessionInGame_Response {
    const message = createBaseCChinaAgreementSessions_StartAgreementSessionInGame_Response();
    message.agreement_url = object.agreement_url ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
