// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.1
// source: steammessages_oauth.steamworkssdk.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "";

export interface COAuthToken_ImplicitGrantNoPrompt_Request {
  clientid?: string | undefined;
}

export interface COAuthToken_ImplicitGrantNoPrompt_Response {
  access_token?: string | undefined;
  redirect_uri?: string | undefined;
}

function createBaseCOAuthToken_ImplicitGrantNoPrompt_Request(): COAuthToken_ImplicitGrantNoPrompt_Request {
  return { clientid: undefined };
}

export const COAuthToken_ImplicitGrantNoPrompt_Request: MessageFns<COAuthToken_ImplicitGrantNoPrompt_Request> = {
  encode(message: COAuthToken_ImplicitGrantNoPrompt_Request, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.clientid !== undefined) {
      writer.uint32(10).string(message.clientid);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): COAuthToken_ImplicitGrantNoPrompt_Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCOAuthToken_ImplicitGrantNoPrompt_Request();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.clientid = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): COAuthToken_ImplicitGrantNoPrompt_Request {
    return { clientid: isSet(object.clientid) ? globalThis.String(object.clientid) : undefined };
  },

  toJSON(message: COAuthToken_ImplicitGrantNoPrompt_Request): unknown {
    const obj: any = {};
    if (message.clientid !== undefined) {
      obj.clientid = message.clientid;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<COAuthToken_ImplicitGrantNoPrompt_Request>, I>>(
    base?: I,
  ): COAuthToken_ImplicitGrantNoPrompt_Request {
    return COAuthToken_ImplicitGrantNoPrompt_Request.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<COAuthToken_ImplicitGrantNoPrompt_Request>, I>>(
    object: I,
  ): COAuthToken_ImplicitGrantNoPrompt_Request {
    const message = createBaseCOAuthToken_ImplicitGrantNoPrompt_Request();
    message.clientid = object.clientid ?? undefined;
    return message;
  },
};

function createBaseCOAuthToken_ImplicitGrantNoPrompt_Response(): COAuthToken_ImplicitGrantNoPrompt_Response {
  return { access_token: undefined, redirect_uri: undefined };
}

export const COAuthToken_ImplicitGrantNoPrompt_Response: MessageFns<COAuthToken_ImplicitGrantNoPrompt_Response> = {
  encode(message: COAuthToken_ImplicitGrantNoPrompt_Response, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.access_token !== undefined) {
      writer.uint32(10).string(message.access_token);
    }
    if (message.redirect_uri !== undefined) {
      writer.uint32(18).string(message.redirect_uri);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): COAuthToken_ImplicitGrantNoPrompt_Response {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCOAuthToken_ImplicitGrantNoPrompt_Response();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.access_token = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.redirect_uri = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): COAuthToken_ImplicitGrantNoPrompt_Response {
    return {
      access_token: isSet(object.accessToken)
        ? globalThis.String(object.accessToken)
        : isSet(object.access_token)
        ? globalThis.String(object.access_token)
        : undefined,
      redirect_uri: isSet(object.redirectUri)
        ? globalThis.String(object.redirectUri)
        : isSet(object.redirect_uri)
        ? globalThis.String(object.redirect_uri)
        : undefined,
    };
  },

  toJSON(message: COAuthToken_ImplicitGrantNoPrompt_Response): unknown {
    const obj: any = {};
    if (message.access_token !== undefined) {
      obj.accessToken = message.access_token;
    }
    if (message.redirect_uri !== undefined) {
      obj.redirectUri = message.redirect_uri;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<COAuthToken_ImplicitGrantNoPrompt_Response>, I>>(
    base?: I,
  ): COAuthToken_ImplicitGrantNoPrompt_Response {
    return COAuthToken_ImplicitGrantNoPrompt_Response.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<COAuthToken_ImplicitGrantNoPrompt_Response>, I>>(
    object: I,
  ): COAuthToken_ImplicitGrantNoPrompt_Response {
    const message = createBaseCOAuthToken_ImplicitGrantNoPrompt_Response();
    message.access_token = object.access_token ?? undefined;
    message.redirect_uri = object.redirect_uri ?? undefined;
    return message;
  },
};

export interface OAuthToken {
  ImplicitGrantNoPrompt(
    request: COAuthToken_ImplicitGrantNoPrompt_Request,
  ): Promise<COAuthToken_ImplicitGrantNoPrompt_Response>;
}

export const OAuthTokenServiceName = "OAuthToken";
export class OAuthTokenClientImpl implements OAuthToken {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || OAuthTokenServiceName;
    this.rpc = rpc;
    this.ImplicitGrantNoPrompt = this.ImplicitGrantNoPrompt.bind(this);
  }
  ImplicitGrantNoPrompt(
    request: COAuthToken_ImplicitGrantNoPrompt_Request,
  ): Promise<COAuthToken_ImplicitGrantNoPrompt_Response> {
    const data = COAuthToken_ImplicitGrantNoPrompt_Request.encode(request).finish();
    const promise = this.rpc.request(this.service, "ImplicitGrantNoPrompt", data);
    return promise.then((data) => COAuthToken_ImplicitGrantNoPrompt_Response.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
