// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.1
// source: steammessages_cloud.steamworkssdk.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "";

export interface CCloud_GetUploadServerInfo_Request {
  appid?: number | undefined;
}

export interface CCloud_GetUploadServerInfo_Response {
  server_url?: string | undefined;
}

export interface CCloud_GetFileDetails_Request {
  ugcid?: string | undefined;
  appid?: number | undefined;
}

export interface CCloud_UserFile {
  appid?: number | undefined;
  ugcid?: string | undefined;
  filename?: string | undefined;
  timestamp?: string | undefined;
  file_size?: number | undefined;
  url?: string | undefined;
  steamid_creator?: string | undefined;
}

export interface CCloud_GetFileDetails_Response {
  details?: CCloud_UserFile | undefined;
}

export interface CCloud_EnumerateUserFiles_Request {
  appid?: number | undefined;
  extended_details?: boolean | undefined;
  count?: number | undefined;
  start_index?: number | undefined;
}

export interface CCloud_EnumerateUserFiles_Response {
  files: CCloud_UserFile[];
  total_files?: number | undefined;
}

export interface CCloud_Delete_Request {
  filename?: string | undefined;
  appid?: number | undefined;
}

export interface CCloud_Delete_Response {
}

function createBaseCCloud_GetUploadServerInfo_Request(): CCloud_GetUploadServerInfo_Request {
  return { appid: undefined };
}

export const CCloud_GetUploadServerInfo_Request: MessageFns<CCloud_GetUploadServerInfo_Request> = {
  encode(message: CCloud_GetUploadServerInfo_Request, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.appid !== undefined) {
      writer.uint32(8).uint32(message.appid);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CCloud_GetUploadServerInfo_Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCCloud_GetUploadServerInfo_Request();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.appid = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CCloud_GetUploadServerInfo_Request {
    return { appid: isSet(object.appid) ? globalThis.Number(object.appid) : undefined };
  },

  toJSON(message: CCloud_GetUploadServerInfo_Request): unknown {
    const obj: any = {};
    if (message.appid !== undefined) {
      obj.appid = Math.round(message.appid);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CCloud_GetUploadServerInfo_Request>, I>>(
    base?: I,
  ): CCloud_GetUploadServerInfo_Request {
    return CCloud_GetUploadServerInfo_Request.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CCloud_GetUploadServerInfo_Request>, I>>(
    object: I,
  ): CCloud_GetUploadServerInfo_Request {
    const message = createBaseCCloud_GetUploadServerInfo_Request();
    message.appid = object.appid ?? undefined;
    return message;
  },
};

function createBaseCCloud_GetUploadServerInfo_Response(): CCloud_GetUploadServerInfo_Response {
  return { server_url: undefined };
}

export const CCloud_GetUploadServerInfo_Response: MessageFns<CCloud_GetUploadServerInfo_Response> = {
  encode(message: CCloud_GetUploadServerInfo_Response, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.server_url !== undefined) {
      writer.uint32(10).string(message.server_url);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CCloud_GetUploadServerInfo_Response {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCCloud_GetUploadServerInfo_Response();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.server_url = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CCloud_GetUploadServerInfo_Response {
    return {
      server_url: isSet(object.serverUrl)
        ? globalThis.String(object.serverUrl)
        : isSet(object.server_url)
        ? globalThis.String(object.server_url)
        : undefined,
    };
  },

  toJSON(message: CCloud_GetUploadServerInfo_Response): unknown {
    const obj: any = {};
    if (message.server_url !== undefined) {
      obj.serverUrl = message.server_url;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CCloud_GetUploadServerInfo_Response>, I>>(
    base?: I,
  ): CCloud_GetUploadServerInfo_Response {
    return CCloud_GetUploadServerInfo_Response.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CCloud_GetUploadServerInfo_Response>, I>>(
    object: I,
  ): CCloud_GetUploadServerInfo_Response {
    const message = createBaseCCloud_GetUploadServerInfo_Response();
    message.server_url = object.server_url ?? undefined;
    return message;
  },
};

function createBaseCCloud_GetFileDetails_Request(): CCloud_GetFileDetails_Request {
  return { ugcid: undefined, appid: undefined };
}

export const CCloud_GetFileDetails_Request: MessageFns<CCloud_GetFileDetails_Request> = {
  encode(message: CCloud_GetFileDetails_Request, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ugcid !== undefined) {
      writer.uint32(8).uint64(message.ugcid);
    }
    if (message.appid !== undefined) {
      writer.uint32(16).uint32(message.appid);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CCloud_GetFileDetails_Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCCloud_GetFileDetails_Request();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.ugcid = reader.uint64().toString();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.appid = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CCloud_GetFileDetails_Request {
    return {
      ugcid: isSet(object.ugcid) ? globalThis.String(object.ugcid) : undefined,
      appid: isSet(object.appid) ? globalThis.Number(object.appid) : undefined,
    };
  },

  toJSON(message: CCloud_GetFileDetails_Request): unknown {
    const obj: any = {};
    if (message.ugcid !== undefined) {
      obj.ugcid = message.ugcid;
    }
    if (message.appid !== undefined) {
      obj.appid = Math.round(message.appid);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CCloud_GetFileDetails_Request>, I>>(base?: I): CCloud_GetFileDetails_Request {
    return CCloud_GetFileDetails_Request.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CCloud_GetFileDetails_Request>, I>>(
    object: I,
  ): CCloud_GetFileDetails_Request {
    const message = createBaseCCloud_GetFileDetails_Request();
    message.ugcid = object.ugcid ?? undefined;
    message.appid = object.appid ?? undefined;
    return message;
  },
};

function createBaseCCloud_UserFile(): CCloud_UserFile {
  return {
    appid: undefined,
    ugcid: undefined,
    filename: undefined,
    timestamp: undefined,
    file_size: undefined,
    url: undefined,
    steamid_creator: undefined,
  };
}

export const CCloud_UserFile: MessageFns<CCloud_UserFile> = {
  encode(message: CCloud_UserFile, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.appid !== undefined) {
      writer.uint32(8).uint32(message.appid);
    }
    if (message.ugcid !== undefined) {
      writer.uint32(16).uint64(message.ugcid);
    }
    if (message.filename !== undefined) {
      writer.uint32(26).string(message.filename);
    }
    if (message.timestamp !== undefined) {
      writer.uint32(32).uint64(message.timestamp);
    }
    if (message.file_size !== undefined) {
      writer.uint32(40).uint32(message.file_size);
    }
    if (message.url !== undefined) {
      writer.uint32(50).string(message.url);
    }
    if (message.steamid_creator !== undefined) {
      writer.uint32(57).fixed64(message.steamid_creator);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CCloud_UserFile {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCCloud_UserFile();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.appid = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.ugcid = reader.uint64().toString();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.filename = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.timestamp = reader.uint64().toString();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.file_size = reader.uint32();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.url = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 57) {
            break;
          }

          message.steamid_creator = reader.fixed64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CCloud_UserFile {
    return {
      appid: isSet(object.appid) ? globalThis.Number(object.appid) : undefined,
      ugcid: isSet(object.ugcid) ? globalThis.String(object.ugcid) : undefined,
      filename: isSet(object.filename) ? globalThis.String(object.filename) : undefined,
      timestamp: isSet(object.timestamp) ? globalThis.String(object.timestamp) : undefined,
      file_size: isSet(object.fileSize)
        ? globalThis.Number(object.fileSize)
        : isSet(object.file_size)
        ? globalThis.Number(object.file_size)
        : undefined,
      url: isSet(object.url) ? globalThis.String(object.url) : undefined,
      steamid_creator: isSet(object.steamidCreator)
        ? globalThis.String(object.steamidCreator)
        : isSet(object.steamid_creator)
        ? globalThis.String(object.steamid_creator)
        : undefined,
    };
  },

  toJSON(message: CCloud_UserFile): unknown {
    const obj: any = {};
    if (message.appid !== undefined) {
      obj.appid = Math.round(message.appid);
    }
    if (message.ugcid !== undefined) {
      obj.ugcid = message.ugcid;
    }
    if (message.filename !== undefined) {
      obj.filename = message.filename;
    }
    if (message.timestamp !== undefined) {
      obj.timestamp = message.timestamp;
    }
    if (message.file_size !== undefined) {
      obj.fileSize = Math.round(message.file_size);
    }
    if (message.url !== undefined) {
      obj.url = message.url;
    }
    if (message.steamid_creator !== undefined) {
      obj.steamidCreator = message.steamid_creator;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CCloud_UserFile>, I>>(base?: I): CCloud_UserFile {
    return CCloud_UserFile.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CCloud_UserFile>, I>>(object: I): CCloud_UserFile {
    const message = createBaseCCloud_UserFile();
    message.appid = object.appid ?? undefined;
    message.ugcid = object.ugcid ?? undefined;
    message.filename = object.filename ?? undefined;
    message.timestamp = object.timestamp ?? undefined;
    message.file_size = object.file_size ?? undefined;
    message.url = object.url ?? undefined;
    message.steamid_creator = object.steamid_creator ?? undefined;
    return message;
  },
};

function createBaseCCloud_GetFileDetails_Response(): CCloud_GetFileDetails_Response {
  return { details: undefined };
}

export const CCloud_GetFileDetails_Response: MessageFns<CCloud_GetFileDetails_Response> = {
  encode(message: CCloud_GetFileDetails_Response, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.details !== undefined) {
      CCloud_UserFile.encode(message.details, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CCloud_GetFileDetails_Response {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCCloud_GetFileDetails_Response();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.details = CCloud_UserFile.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CCloud_GetFileDetails_Response {
    return { details: isSet(object.details) ? CCloud_UserFile.fromJSON(object.details) : undefined };
  },

  toJSON(message: CCloud_GetFileDetails_Response): unknown {
    const obj: any = {};
    if (message.details !== undefined) {
      obj.details = CCloud_UserFile.toJSON(message.details);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CCloud_GetFileDetails_Response>, I>>(base?: I): CCloud_GetFileDetails_Response {
    return CCloud_GetFileDetails_Response.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CCloud_GetFileDetails_Response>, I>>(
    object: I,
  ): CCloud_GetFileDetails_Response {
    const message = createBaseCCloud_GetFileDetails_Response();
    message.details = (object.details !== undefined && object.details !== null)
      ? CCloud_UserFile.fromPartial(object.details)
      : undefined;
    return message;
  },
};

function createBaseCCloud_EnumerateUserFiles_Request(): CCloud_EnumerateUserFiles_Request {
  return { appid: undefined, extended_details: undefined, count: undefined, start_index: undefined };
}

export const CCloud_EnumerateUserFiles_Request: MessageFns<CCloud_EnumerateUserFiles_Request> = {
  encode(message: CCloud_EnumerateUserFiles_Request, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.appid !== undefined) {
      writer.uint32(8).uint32(message.appid);
    }
    if (message.extended_details !== undefined) {
      writer.uint32(16).bool(message.extended_details);
    }
    if (message.count !== undefined) {
      writer.uint32(24).uint32(message.count);
    }
    if (message.start_index !== undefined) {
      writer.uint32(32).uint32(message.start_index);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CCloud_EnumerateUserFiles_Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCCloud_EnumerateUserFiles_Request();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.appid = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.extended_details = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.count = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.start_index = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CCloud_EnumerateUserFiles_Request {
    return {
      appid: isSet(object.appid) ? globalThis.Number(object.appid) : undefined,
      extended_details: isSet(object.extendedDetails)
        ? globalThis.Boolean(object.extendedDetails)
        : isSet(object.extended_details)
        ? globalThis.Boolean(object.extended_details)
        : undefined,
      count: isSet(object.count) ? globalThis.Number(object.count) : undefined,
      start_index: isSet(object.startIndex)
        ? globalThis.Number(object.startIndex)
        : isSet(object.start_index)
        ? globalThis.Number(object.start_index)
        : undefined,
    };
  },

  toJSON(message: CCloud_EnumerateUserFiles_Request): unknown {
    const obj: any = {};
    if (message.appid !== undefined) {
      obj.appid = Math.round(message.appid);
    }
    if (message.extended_details !== undefined) {
      obj.extendedDetails = message.extended_details;
    }
    if (message.count !== undefined) {
      obj.count = Math.round(message.count);
    }
    if (message.start_index !== undefined) {
      obj.startIndex = Math.round(message.start_index);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CCloud_EnumerateUserFiles_Request>, I>>(
    base?: I,
  ): CCloud_EnumerateUserFiles_Request {
    return CCloud_EnumerateUserFiles_Request.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CCloud_EnumerateUserFiles_Request>, I>>(
    object: I,
  ): CCloud_EnumerateUserFiles_Request {
    const message = createBaseCCloud_EnumerateUserFiles_Request();
    message.appid = object.appid ?? undefined;
    message.extended_details = object.extended_details ?? undefined;
    message.count = object.count ?? undefined;
    message.start_index = object.start_index ?? undefined;
    return message;
  },
};

function createBaseCCloud_EnumerateUserFiles_Response(): CCloud_EnumerateUserFiles_Response {
  return { files: [], total_files: undefined };
}

export const CCloud_EnumerateUserFiles_Response: MessageFns<CCloud_EnumerateUserFiles_Response> = {
  encode(message: CCloud_EnumerateUserFiles_Response, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.files) {
      CCloud_UserFile.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.total_files !== undefined) {
      writer.uint32(16).uint32(message.total_files);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CCloud_EnumerateUserFiles_Response {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCCloud_EnumerateUserFiles_Response();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.files.push(CCloud_UserFile.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.total_files = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CCloud_EnumerateUserFiles_Response {
    return {
      files: globalThis.Array.isArray(object?.files) ? object.files.map((e: any) => CCloud_UserFile.fromJSON(e)) : [],
      total_files: isSet(object.totalFiles)
        ? globalThis.Number(object.totalFiles)
        : isSet(object.total_files)
        ? globalThis.Number(object.total_files)
        : undefined,
    };
  },

  toJSON(message: CCloud_EnumerateUserFiles_Response): unknown {
    const obj: any = {};
    if (message.files?.length) {
      obj.files = message.files.map((e) => CCloud_UserFile.toJSON(e));
    }
    if (message.total_files !== undefined) {
      obj.totalFiles = Math.round(message.total_files);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CCloud_EnumerateUserFiles_Response>, I>>(
    base?: I,
  ): CCloud_EnumerateUserFiles_Response {
    return CCloud_EnumerateUserFiles_Response.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CCloud_EnumerateUserFiles_Response>, I>>(
    object: I,
  ): CCloud_EnumerateUserFiles_Response {
    const message = createBaseCCloud_EnumerateUserFiles_Response();
    message.files = object.files?.map((e) => CCloud_UserFile.fromPartial(e)) || [];
    message.total_files = object.total_files ?? undefined;
    return message;
  },
};

function createBaseCCloud_Delete_Request(): CCloud_Delete_Request {
  return { filename: undefined, appid: undefined };
}

export const CCloud_Delete_Request: MessageFns<CCloud_Delete_Request> = {
  encode(message: CCloud_Delete_Request, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.filename !== undefined) {
      writer.uint32(10).string(message.filename);
    }
    if (message.appid !== undefined) {
      writer.uint32(16).uint32(message.appid);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CCloud_Delete_Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCCloud_Delete_Request();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.filename = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.appid = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CCloud_Delete_Request {
    return {
      filename: isSet(object.filename) ? globalThis.String(object.filename) : undefined,
      appid: isSet(object.appid) ? globalThis.Number(object.appid) : undefined,
    };
  },

  toJSON(message: CCloud_Delete_Request): unknown {
    const obj: any = {};
    if (message.filename !== undefined) {
      obj.filename = message.filename;
    }
    if (message.appid !== undefined) {
      obj.appid = Math.round(message.appid);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CCloud_Delete_Request>, I>>(base?: I): CCloud_Delete_Request {
    return CCloud_Delete_Request.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CCloud_Delete_Request>, I>>(object: I): CCloud_Delete_Request {
    const message = createBaseCCloud_Delete_Request();
    message.filename = object.filename ?? undefined;
    message.appid = object.appid ?? undefined;
    return message;
  },
};

function createBaseCCloud_Delete_Response(): CCloud_Delete_Response {
  return {};
}

export const CCloud_Delete_Response: MessageFns<CCloud_Delete_Response> = {
  encode(_: CCloud_Delete_Response, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CCloud_Delete_Response {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCCloud_Delete_Response();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): CCloud_Delete_Response {
    return {};
  },

  toJSON(_: CCloud_Delete_Response): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<CCloud_Delete_Response>, I>>(base?: I): CCloud_Delete_Response {
    return CCloud_Delete_Response.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CCloud_Delete_Response>, I>>(_: I): CCloud_Delete_Response {
    const message = createBaseCCloud_Delete_Response();
    return message;
  },
};

export interface Cloud {
  GetUploadServerInfo(request: CCloud_GetUploadServerInfo_Request): Promise<CCloud_GetUploadServerInfo_Response>;
  GetFileDetails(request: CCloud_GetFileDetails_Request): Promise<CCloud_GetFileDetails_Response>;
  EnumerateUserFiles(request: CCloud_EnumerateUserFiles_Request): Promise<CCloud_EnumerateUserFiles_Response>;
  Delete(request: CCloud_Delete_Request): Promise<CCloud_Delete_Response>;
}

export const CloudServiceName = "Cloud";
export class CloudClientImpl implements Cloud {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || CloudServiceName;
    this.rpc = rpc;
    this.GetUploadServerInfo = this.GetUploadServerInfo.bind(this);
    this.GetFileDetails = this.GetFileDetails.bind(this);
    this.EnumerateUserFiles = this.EnumerateUserFiles.bind(this);
    this.Delete = this.Delete.bind(this);
  }
  GetUploadServerInfo(request: CCloud_GetUploadServerInfo_Request): Promise<CCloud_GetUploadServerInfo_Response> {
    const data = CCloud_GetUploadServerInfo_Request.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetUploadServerInfo", data);
    return promise.then((data) => CCloud_GetUploadServerInfo_Response.decode(new BinaryReader(data)));
  }

  GetFileDetails(request: CCloud_GetFileDetails_Request): Promise<CCloud_GetFileDetails_Response> {
    const data = CCloud_GetFileDetails_Request.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetFileDetails", data);
    return promise.then((data) => CCloud_GetFileDetails_Response.decode(new BinaryReader(data)));
  }

  EnumerateUserFiles(request: CCloud_EnumerateUserFiles_Request): Promise<CCloud_EnumerateUserFiles_Response> {
    const data = CCloud_EnumerateUserFiles_Request.encode(request).finish();
    const promise = this.rpc.request(this.service, "EnumerateUserFiles", data);
    return promise.then((data) => CCloud_EnumerateUserFiles_Response.decode(new BinaryReader(data)));
  }

  Delete(request: CCloud_Delete_Request): Promise<CCloud_Delete_Response> {
    const data = CCloud_Delete_Request.encode(request).finish();
    const promise = this.rpc.request(this.service, "Delete", data);
    return promise.then((data) => CCloud_Delete_Response.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
