// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.1
//   protoc               v3.20.3
// source: steamnetworkingsockets_messages_certs.proto

/* eslint-disable */
import * as _m0 from "protobufjs/minimal";
import Long = require("long");

export const protobufPackage = "";

export interface CMsgSteamNetworkingIdentityLegacyBinary {
  steamId?: string | undefined;
  genericBytes?: Uint8Array | undefined;
  genericString?: string | undefined;
  ipv6AndPort?: Uint8Array | undefined;
}

export interface CMsgSteamDatagramCertificate {
  keyType?: CMsgSteamDatagramCertificate_EKeyType | undefined;
  keyData?: Uint8Array | undefined;
  legacySteamId?: string | undefined;
  legacyIdentityBinary?: CMsgSteamNetworkingIdentityLegacyBinary | undefined;
  identityString?: string | undefined;
  gameserverDatacenterIds: number[];
  timeCreated?: number | undefined;
  timeExpiry?: number | undefined;
  appIds: number[];
  ipAddresses: string[];
}

export enum CMsgSteamDatagramCertificate_EKeyType {
  INVALID = 0,
  ED25519 = 1,
  UNRECOGNIZED = -1,
}

export function cMsgSteamDatagramCertificate_EKeyTypeFromJSON(object: any): CMsgSteamDatagramCertificate_EKeyType {
  switch (object) {
    case 0:
    case "INVALID":
      return CMsgSteamDatagramCertificate_EKeyType.INVALID;
    case 1:
    case "ED25519":
      return CMsgSteamDatagramCertificate_EKeyType.ED25519;
    case -1:
    case "UNRECOGNIZED":
    default:
      return CMsgSteamDatagramCertificate_EKeyType.UNRECOGNIZED;
  }
}

export function cMsgSteamDatagramCertificate_EKeyTypeToJSON(object: CMsgSteamDatagramCertificate_EKeyType): string {
  switch (object) {
    case CMsgSteamDatagramCertificate_EKeyType.INVALID:
      return "INVALID";
    case CMsgSteamDatagramCertificate_EKeyType.ED25519:
      return "ED25519";
    case CMsgSteamDatagramCertificate_EKeyType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface CMsgSteamDatagramCertificateSigned {
  cert?: Uint8Array | undefined;
  caKeyId?: string | undefined;
  caSignature?: Uint8Array | undefined;
  privateKeyData?: Uint8Array | undefined;
}

export interface CMsgSteamDatagramCertificateRequest {
  cert?: CMsgSteamDatagramCertificate | undefined;
}

function createBaseCMsgSteamNetworkingIdentityLegacyBinary(): CMsgSteamNetworkingIdentityLegacyBinary {
  return { steamId: "0", genericBytes: new Uint8Array(0), genericString: "", ipv6AndPort: new Uint8Array(0) };
}

export const CMsgSteamNetworkingIdentityLegacyBinary = {
  encode(message: CMsgSteamNetworkingIdentityLegacyBinary, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.steamId !== undefined && message.steamId !== "0") {
      writer.uint32(129).fixed64(message.steamId);
    }
    if (message.genericBytes !== undefined && message.genericBytes.length !== 0) {
      writer.uint32(18).bytes(message.genericBytes);
    }
    if (message.genericString !== undefined && message.genericString !== "") {
      writer.uint32(26).string(message.genericString);
    }
    if (message.ipv6AndPort !== undefined && message.ipv6AndPort.length !== 0) {
      writer.uint32(34).bytes(message.ipv6AndPort);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CMsgSteamNetworkingIdentityLegacyBinary {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamNetworkingIdentityLegacyBinary();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 16:
          if (tag !== 129) {
            break;
          }

          message.steamId = longToString(reader.fixed64() as Long);
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.genericBytes = reader.bytes();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.genericString = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.ipv6AndPort = reader.bytes();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CMsgSteamNetworkingIdentityLegacyBinary {
    return {
      steamId: isSet(object.steamId) ? globalThis.String(object.steamId) : "0",
      genericBytes: isSet(object.genericBytes) ? bytesFromBase64(object.genericBytes) : new Uint8Array(0),
      genericString: isSet(object.genericString) ? globalThis.String(object.genericString) : "",
      ipv6AndPort: isSet(object.ipv6AndPort) ? bytesFromBase64(object.ipv6AndPort) : new Uint8Array(0),
    };
  },

  toJSON(message: CMsgSteamNetworkingIdentityLegacyBinary): unknown {
    const obj: any = {};
    if (message.steamId !== undefined && message.steamId !== "0") {
      obj.steamId = message.steamId;
    }
    if (message.genericBytes !== undefined && message.genericBytes.length !== 0) {
      obj.genericBytes = base64FromBytes(message.genericBytes);
    }
    if (message.genericString !== undefined && message.genericString !== "") {
      obj.genericString = message.genericString;
    }
    if (message.ipv6AndPort !== undefined && message.ipv6AndPort.length !== 0) {
      obj.ipv6AndPort = base64FromBytes(message.ipv6AndPort);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CMsgSteamNetworkingIdentityLegacyBinary>, I>>(
    base?: I,
  ): CMsgSteamNetworkingIdentityLegacyBinary {
    return CMsgSteamNetworkingIdentityLegacyBinary.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CMsgSteamNetworkingIdentityLegacyBinary>, I>>(
    object: I,
  ): CMsgSteamNetworkingIdentityLegacyBinary {
    const message = createBaseCMsgSteamNetworkingIdentityLegacyBinary();
    message.steamId = object.steamId ?? "0";
    message.genericBytes = object.genericBytes ?? new Uint8Array(0);
    message.genericString = object.genericString ?? "";
    message.ipv6AndPort = object.ipv6AndPort ?? new Uint8Array(0);
    return message;
  },
};

function createBaseCMsgSteamDatagramCertificate(): CMsgSteamDatagramCertificate {
  return {
    keyType: 0,
    keyData: new Uint8Array(0),
    legacySteamId: "0",
    legacyIdentityBinary: undefined,
    identityString: "",
    gameserverDatacenterIds: [],
    timeCreated: 0,
    timeExpiry: 0,
    appIds: [],
    ipAddresses: [],
  };
}

export const CMsgSteamDatagramCertificate = {
  encode(message: CMsgSteamDatagramCertificate, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.keyType !== undefined && message.keyType !== 0) {
      writer.uint32(8).int32(message.keyType);
    }
    if (message.keyData !== undefined && message.keyData.length !== 0) {
      writer.uint32(18).bytes(message.keyData);
    }
    if (message.legacySteamId !== undefined && message.legacySteamId !== "0") {
      writer.uint32(33).fixed64(message.legacySteamId);
    }
    if (message.legacyIdentityBinary !== undefined) {
      CMsgSteamNetworkingIdentityLegacyBinary.encode(message.legacyIdentityBinary, writer.uint32(90).fork()).ldelim();
    }
    if (message.identityString !== undefined && message.identityString !== "") {
      writer.uint32(98).string(message.identityString);
    }
    writer.uint32(42).fork();
    for (const v of message.gameserverDatacenterIds) {
      writer.fixed32(v);
    }
    writer.ldelim();
    if (message.timeCreated !== undefined && message.timeCreated !== 0) {
      writer.uint32(69).fixed32(message.timeCreated);
    }
    if (message.timeExpiry !== undefined && message.timeExpiry !== 0) {
      writer.uint32(77).fixed32(message.timeExpiry);
    }
    writer.uint32(82).fork();
    for (const v of message.appIds) {
      writer.uint32(v);
    }
    writer.ldelim();
    for (const v of message.ipAddresses) {
      writer.uint32(106).string(v!);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CMsgSteamDatagramCertificate {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamDatagramCertificate();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.keyType = reader.int32() as any;
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.keyData = reader.bytes();
          continue;
        case 4:
          if (tag !== 33) {
            break;
          }

          message.legacySteamId = longToString(reader.fixed64() as Long);
          continue;
        case 11:
          if (tag !== 90) {
            break;
          }

          message.legacyIdentityBinary = CMsgSteamNetworkingIdentityLegacyBinary.decode(reader, reader.uint32());
          continue;
        case 12:
          if (tag !== 98) {
            break;
          }

          message.identityString = reader.string();
          continue;
        case 5:
          if (tag === 45) {
            message.gameserverDatacenterIds.push(reader.fixed32());

            continue;
          }

          if (tag === 42) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.gameserverDatacenterIds.push(reader.fixed32());
            }

            continue;
          }

          break;
        case 8:
          if (tag !== 69) {
            break;
          }

          message.timeCreated = reader.fixed32();
          continue;
        case 9:
          if (tag !== 77) {
            break;
          }

          message.timeExpiry = reader.fixed32();
          continue;
        case 10:
          if (tag === 80) {
            message.appIds.push(reader.uint32());

            continue;
          }

          if (tag === 82) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.appIds.push(reader.uint32());
            }

            continue;
          }

          break;
        case 13:
          if (tag !== 106) {
            break;
          }

          message.ipAddresses.push(reader.string());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CMsgSteamDatagramCertificate {
    return {
      keyType: isSet(object.keyType) ? cMsgSteamDatagramCertificate_EKeyTypeFromJSON(object.keyType) : 0,
      keyData: isSet(object.keyData) ? bytesFromBase64(object.keyData) : new Uint8Array(0),
      legacySteamId: isSet(object.legacySteamId) ? globalThis.String(object.legacySteamId) : "0",
      legacyIdentityBinary: isSet(object.legacyIdentityBinary)
        ? CMsgSteamNetworkingIdentityLegacyBinary.fromJSON(object.legacyIdentityBinary)
        : undefined,
      identityString: isSet(object.identityString) ? globalThis.String(object.identityString) : "",
      gameserverDatacenterIds: globalThis.Array.isArray(object?.gameserverDatacenterIds)
        ? object.gameserverDatacenterIds.map((e: any) => globalThis.Number(e))
        : [],
      timeCreated: isSet(object.timeCreated) ? globalThis.Number(object.timeCreated) : 0,
      timeExpiry: isSet(object.timeExpiry) ? globalThis.Number(object.timeExpiry) : 0,
      appIds: globalThis.Array.isArray(object?.appIds) ? object.appIds.map((e: any) => globalThis.Number(e)) : [],
      ipAddresses: globalThis.Array.isArray(object?.ipAddresses)
        ? object.ipAddresses.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: CMsgSteamDatagramCertificate): unknown {
    const obj: any = {};
    if (message.keyType !== undefined && message.keyType !== 0) {
      obj.keyType = cMsgSteamDatagramCertificate_EKeyTypeToJSON(message.keyType);
    }
    if (message.keyData !== undefined && message.keyData.length !== 0) {
      obj.keyData = base64FromBytes(message.keyData);
    }
    if (message.legacySteamId !== undefined && message.legacySteamId !== "0") {
      obj.legacySteamId = message.legacySteamId;
    }
    if (message.legacyIdentityBinary !== undefined) {
      obj.legacyIdentityBinary = CMsgSteamNetworkingIdentityLegacyBinary.toJSON(message.legacyIdentityBinary);
    }
    if (message.identityString !== undefined && message.identityString !== "") {
      obj.identityString = message.identityString;
    }
    if (message.gameserverDatacenterIds?.length) {
      obj.gameserverDatacenterIds = message.gameserverDatacenterIds.map((e) => Math.round(e));
    }
    if (message.timeCreated !== undefined && message.timeCreated !== 0) {
      obj.timeCreated = Math.round(message.timeCreated);
    }
    if (message.timeExpiry !== undefined && message.timeExpiry !== 0) {
      obj.timeExpiry = Math.round(message.timeExpiry);
    }
    if (message.appIds?.length) {
      obj.appIds = message.appIds.map((e) => Math.round(e));
    }
    if (message.ipAddresses?.length) {
      obj.ipAddresses = message.ipAddresses;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CMsgSteamDatagramCertificate>, I>>(base?: I): CMsgSteamDatagramCertificate {
    return CMsgSteamDatagramCertificate.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CMsgSteamDatagramCertificate>, I>>(object: I): CMsgSteamDatagramCertificate {
    const message = createBaseCMsgSteamDatagramCertificate();
    message.keyType = object.keyType ?? 0;
    message.keyData = object.keyData ?? new Uint8Array(0);
    message.legacySteamId = object.legacySteamId ?? "0";
    message.legacyIdentityBinary = (object.legacyIdentityBinary !== undefined && object.legacyIdentityBinary !== null)
      ? CMsgSteamNetworkingIdentityLegacyBinary.fromPartial(object.legacyIdentityBinary)
      : undefined;
    message.identityString = object.identityString ?? "";
    message.gameserverDatacenterIds = object.gameserverDatacenterIds?.map((e) => e) || [];
    message.timeCreated = object.timeCreated ?? 0;
    message.timeExpiry = object.timeExpiry ?? 0;
    message.appIds = object.appIds?.map((e) => e) || [];
    message.ipAddresses = object.ipAddresses?.map((e) => e) || [];
    return message;
  },
};

function createBaseCMsgSteamDatagramCertificateSigned(): CMsgSteamDatagramCertificateSigned {
  return { cert: new Uint8Array(0), caKeyId: "0", caSignature: new Uint8Array(0), privateKeyData: new Uint8Array(0) };
}

export const CMsgSteamDatagramCertificateSigned = {
  encode(message: CMsgSteamDatagramCertificateSigned, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.cert !== undefined && message.cert.length !== 0) {
      writer.uint32(34).bytes(message.cert);
    }
    if (message.caKeyId !== undefined && message.caKeyId !== "0") {
      writer.uint32(41).fixed64(message.caKeyId);
    }
    if (message.caSignature !== undefined && message.caSignature.length !== 0) {
      writer.uint32(50).bytes(message.caSignature);
    }
    if (message.privateKeyData !== undefined && message.privateKeyData.length !== 0) {
      writer.uint32(10).bytes(message.privateKeyData);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CMsgSteamDatagramCertificateSigned {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamDatagramCertificateSigned();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 4:
          if (tag !== 34) {
            break;
          }

          message.cert = reader.bytes();
          continue;
        case 5:
          if (tag !== 41) {
            break;
          }

          message.caKeyId = longToString(reader.fixed64() as Long);
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.caSignature = reader.bytes();
          continue;
        case 1:
          if (tag !== 10) {
            break;
          }

          message.privateKeyData = reader.bytes();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CMsgSteamDatagramCertificateSigned {
    return {
      cert: isSet(object.cert) ? bytesFromBase64(object.cert) : new Uint8Array(0),
      caKeyId: isSet(object.caKeyId) ? globalThis.String(object.caKeyId) : "0",
      caSignature: isSet(object.caSignature) ? bytesFromBase64(object.caSignature) : new Uint8Array(0),
      privateKeyData: isSet(object.privateKeyData) ? bytesFromBase64(object.privateKeyData) : new Uint8Array(0),
    };
  },

  toJSON(message: CMsgSteamDatagramCertificateSigned): unknown {
    const obj: any = {};
    if (message.cert !== undefined && message.cert.length !== 0) {
      obj.cert = base64FromBytes(message.cert);
    }
    if (message.caKeyId !== undefined && message.caKeyId !== "0") {
      obj.caKeyId = message.caKeyId;
    }
    if (message.caSignature !== undefined && message.caSignature.length !== 0) {
      obj.caSignature = base64FromBytes(message.caSignature);
    }
    if (message.privateKeyData !== undefined && message.privateKeyData.length !== 0) {
      obj.privateKeyData = base64FromBytes(message.privateKeyData);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CMsgSteamDatagramCertificateSigned>, I>>(
    base?: I,
  ): CMsgSteamDatagramCertificateSigned {
    return CMsgSteamDatagramCertificateSigned.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CMsgSteamDatagramCertificateSigned>, I>>(
    object: I,
  ): CMsgSteamDatagramCertificateSigned {
    const message = createBaseCMsgSteamDatagramCertificateSigned();
    message.cert = object.cert ?? new Uint8Array(0);
    message.caKeyId = object.caKeyId ?? "0";
    message.caSignature = object.caSignature ?? new Uint8Array(0);
    message.privateKeyData = object.privateKeyData ?? new Uint8Array(0);
    return message;
  },
};

function createBaseCMsgSteamDatagramCertificateRequest(): CMsgSteamDatagramCertificateRequest {
  return { cert: undefined };
}

export const CMsgSteamDatagramCertificateRequest = {
  encode(message: CMsgSteamDatagramCertificateRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.cert !== undefined) {
      CMsgSteamDatagramCertificate.encode(message.cert, writer.uint32(10).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CMsgSteamDatagramCertificateRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgSteamDatagramCertificateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.cert = CMsgSteamDatagramCertificate.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CMsgSteamDatagramCertificateRequest {
    return { cert: isSet(object.cert) ? CMsgSteamDatagramCertificate.fromJSON(object.cert) : undefined };
  },

  toJSON(message: CMsgSteamDatagramCertificateRequest): unknown {
    const obj: any = {};
    if (message.cert !== undefined) {
      obj.cert = CMsgSteamDatagramCertificate.toJSON(message.cert);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CMsgSteamDatagramCertificateRequest>, I>>(
    base?: I,
  ): CMsgSteamDatagramCertificateRequest {
    return CMsgSteamDatagramCertificateRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CMsgSteamDatagramCertificateRequest>, I>>(
    object: I,
  ): CMsgSteamDatagramCertificateRequest {
    const message = createBaseCMsgSteamDatagramCertificateRequest();
    message.cert = (object.cert !== undefined && object.cert !== null)
      ? CMsgSteamDatagramCertificate.fromPartial(object.cert)
      : undefined;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToString(long: Long) {
  return long.toString();
}

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
