// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.1
//   protoc               v3.20.3
// source: uifontfile_format.proto

/* eslint-disable */
import * as _m0 from "protobufjs/minimal";

export const protobufPackage = "";

export interface CUIFontFilePB {
  fontFileName?: string | undefined;
  opentypeFontData?: Uint8Array | undefined;
}

export interface CUIFontFilePackagePB {
  packageVersion: number;
  encryptedFontFiles: CUIFontFilePackagePB_CUIEncryptedFontFilePB[];
}

export interface CUIFontFilePackagePB_CUIEncryptedFontFilePB {
  encryptedContents?: Uint8Array | undefined;
}

function createBaseCUIFontFilePB(): CUIFontFilePB {
  return { fontFileName: "", opentypeFontData: new Uint8Array(0) };
}

export const CUIFontFilePB = {
  encode(message: CUIFontFilePB, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.fontFileName !== undefined && message.fontFileName !== "") {
      writer.uint32(10).string(message.fontFileName);
    }
    if (message.opentypeFontData !== undefined && message.opentypeFontData.length !== 0) {
      writer.uint32(18).bytes(message.opentypeFontData);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CUIFontFilePB {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCUIFontFilePB();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.fontFileName = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.opentypeFontData = reader.bytes();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CUIFontFilePB {
    return {
      fontFileName: isSet(object.fontFileName) ? globalThis.String(object.fontFileName) : "",
      opentypeFontData: isSet(object.opentypeFontData) ? bytesFromBase64(object.opentypeFontData) : new Uint8Array(0),
    };
  },

  toJSON(message: CUIFontFilePB): unknown {
    const obj: any = {};
    if (message.fontFileName !== undefined && message.fontFileName !== "") {
      obj.fontFileName = message.fontFileName;
    }
    if (message.opentypeFontData !== undefined && message.opentypeFontData.length !== 0) {
      obj.opentypeFontData = base64FromBytes(message.opentypeFontData);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CUIFontFilePB>, I>>(base?: I): CUIFontFilePB {
    return CUIFontFilePB.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CUIFontFilePB>, I>>(object: I): CUIFontFilePB {
    const message = createBaseCUIFontFilePB();
    message.fontFileName = object.fontFileName ?? "";
    message.opentypeFontData = object.opentypeFontData ?? new Uint8Array(0);
    return message;
  },
};

function createBaseCUIFontFilePackagePB(): CUIFontFilePackagePB {
  return { packageVersion: 0, encryptedFontFiles: [] };
}

export const CUIFontFilePackagePB = {
  encode(message: CUIFontFilePackagePB, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.packageVersion !== 0) {
      writer.uint32(8).uint32(message.packageVersion);
    }
    for (const v of message.encryptedFontFiles) {
      CUIFontFilePackagePB_CUIEncryptedFontFilePB.encode(v!, writer.uint32(18).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CUIFontFilePackagePB {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCUIFontFilePackagePB();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.packageVersion = reader.uint32();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.encryptedFontFiles.push(CUIFontFilePackagePB_CUIEncryptedFontFilePB.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CUIFontFilePackagePB {
    return {
      packageVersion: isSet(object.packageVersion) ? globalThis.Number(object.packageVersion) : 0,
      encryptedFontFiles: globalThis.Array.isArray(object?.encryptedFontFiles)
        ? object.encryptedFontFiles.map((e: any) => CUIFontFilePackagePB_CUIEncryptedFontFilePB.fromJSON(e))
        : [],
    };
  },

  toJSON(message: CUIFontFilePackagePB): unknown {
    const obj: any = {};
    if (message.packageVersion !== 0) {
      obj.packageVersion = Math.round(message.packageVersion);
    }
    if (message.encryptedFontFiles?.length) {
      obj.encryptedFontFiles = message.encryptedFontFiles.map((e) =>
        CUIFontFilePackagePB_CUIEncryptedFontFilePB.toJSON(e)
      );
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CUIFontFilePackagePB>, I>>(base?: I): CUIFontFilePackagePB {
    return CUIFontFilePackagePB.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CUIFontFilePackagePB>, I>>(object: I): CUIFontFilePackagePB {
    const message = createBaseCUIFontFilePackagePB();
    message.packageVersion = object.packageVersion ?? 0;
    message.encryptedFontFiles =
      object.encryptedFontFiles?.map((e) => CUIFontFilePackagePB_CUIEncryptedFontFilePB.fromPartial(e)) || [];
    return message;
  },
};

function createBaseCUIFontFilePackagePB_CUIEncryptedFontFilePB(): CUIFontFilePackagePB_CUIEncryptedFontFilePB {
  return { encryptedContents: new Uint8Array(0) };
}

export const CUIFontFilePackagePB_CUIEncryptedFontFilePB = {
  encode(message: CUIFontFilePackagePB_CUIEncryptedFontFilePB, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.encryptedContents !== undefined && message.encryptedContents.length !== 0) {
      writer.uint32(10).bytes(message.encryptedContents);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CUIFontFilePackagePB_CUIEncryptedFontFilePB {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCUIFontFilePackagePB_CUIEncryptedFontFilePB();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.encryptedContents = reader.bytes();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CUIFontFilePackagePB_CUIEncryptedFontFilePB {
    return {
      encryptedContents: isSet(object.encryptedContents)
        ? bytesFromBase64(object.encryptedContents)
        : new Uint8Array(0),
    };
  },

  toJSON(message: CUIFontFilePackagePB_CUIEncryptedFontFilePB): unknown {
    const obj: any = {};
    if (message.encryptedContents !== undefined && message.encryptedContents.length !== 0) {
      obj.encryptedContents = base64FromBytes(message.encryptedContents);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CUIFontFilePackagePB_CUIEncryptedFontFilePB>, I>>(
    base?: I,
  ): CUIFontFilePackagePB_CUIEncryptedFontFilePB {
    return CUIFontFilePackagePB_CUIEncryptedFontFilePB.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CUIFontFilePackagePB_CUIEncryptedFontFilePB>, I>>(
    object: I,
  ): CUIFontFilePackagePB_CUIEncryptedFontFilePB {
    const message = createBaseCUIFontFilePackagePB_CUIEncryptedFontFilePB();
    message.encryptedContents = object.encryptedContents ?? new Uint8Array(0);
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
