// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.1
// source: usercmd.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { CMsgQAngle } from "./networkbasetypes.js";

export const protobufPackage = "";

export interface CInButtonStatePB {
  buttonstate1?: string | undefined;
  buttonstate2?: string | undefined;
  buttonstate3?: string | undefined;
}

export interface CSubtickMoveStep {
  button?: string | undefined;
  pressed?: boolean | undefined;
  when?: number | undefined;
  analog_forward_delta?: number | undefined;
  analog_left_delta?: number | undefined;
  pitch_delta?: number | undefined;
  yaw_delta?: number | undefined;
}

export interface CBaseUserCmdExecutionNotes {
  ignored_reason?: string | undefined;
}

export interface CBaseUserCmdPB {
  legacy_command_number?: number | undefined;
  client_tick?: number | undefined;
  prediction_offset_ticks_x256?: number | undefined;
  buttons_pb?: CInButtonStatePB | undefined;
  viewangles?: CMsgQAngle | undefined;
  forwardmove?: number | undefined;
  leftmove?: number | undefined;
  upmove?: number | undefined;
  impulse?: number | undefined;
  weaponselect?: number | undefined;
  random_seed?: number | undefined;
  mousedx?: number | undefined;
  mousedy?: number | undefined;
  pawn_entity_handle?: number | undefined;
  subtick_moves: CSubtickMoveStep[];
  move_crc?: Uint8Array | undefined;
  consumed_server_angle_changes?: number | undefined;
  cmd_flags?: number | undefined;
  execution_notes?: CBaseUserCmdExecutionNotes | undefined;
}

export interface CUserCmdBasePB {
  base?: CBaseUserCmdPB | undefined;
}

function createBaseCInButtonStatePB(): CInButtonStatePB {
  return { buttonstate1: undefined, buttonstate2: undefined, buttonstate3: undefined };
}

export const CInButtonStatePB: MessageFns<CInButtonStatePB> = {
  encode(message: CInButtonStatePB, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.buttonstate1 !== undefined) {
      writer.uint32(8).uint64(message.buttonstate1);
    }
    if (message.buttonstate2 !== undefined) {
      writer.uint32(16).uint64(message.buttonstate2);
    }
    if (message.buttonstate3 !== undefined) {
      writer.uint32(24).uint64(message.buttonstate3);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CInButtonStatePB {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCInButtonStatePB();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.buttonstate1 = reader.uint64().toString();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.buttonstate2 = reader.uint64().toString();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.buttonstate3 = reader.uint64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CInButtonStatePB {
    return {
      buttonstate1: isSet(object.buttonstate1) ? globalThis.String(object.buttonstate1) : undefined,
      buttonstate2: isSet(object.buttonstate2) ? globalThis.String(object.buttonstate2) : undefined,
      buttonstate3: isSet(object.buttonstate3) ? globalThis.String(object.buttonstate3) : undefined,
    };
  },

  toJSON(message: CInButtonStatePB): unknown {
    const obj: any = {};
    if (message.buttonstate1 !== undefined) {
      obj.buttonstate1 = message.buttonstate1;
    }
    if (message.buttonstate2 !== undefined) {
      obj.buttonstate2 = message.buttonstate2;
    }
    if (message.buttonstate3 !== undefined) {
      obj.buttonstate3 = message.buttonstate3;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CInButtonStatePB>, I>>(base?: I): CInButtonStatePB {
    return CInButtonStatePB.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CInButtonStatePB>, I>>(object: I): CInButtonStatePB {
    const message = createBaseCInButtonStatePB();
    message.buttonstate1 = object.buttonstate1 ?? undefined;
    message.buttonstate2 = object.buttonstate2 ?? undefined;
    message.buttonstate3 = object.buttonstate3 ?? undefined;
    return message;
  },
};

function createBaseCSubtickMoveStep(): CSubtickMoveStep {
  return {
    button: undefined,
    pressed: undefined,
    when: undefined,
    analog_forward_delta: undefined,
    analog_left_delta: undefined,
    pitch_delta: undefined,
    yaw_delta: undefined,
  };
}

export const CSubtickMoveStep: MessageFns<CSubtickMoveStep> = {
  encode(message: CSubtickMoveStep, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.button !== undefined) {
      writer.uint32(8).uint64(message.button);
    }
    if (message.pressed !== undefined) {
      writer.uint32(16).bool(message.pressed);
    }
    if (message.when !== undefined) {
      writer.uint32(29).float(message.when);
    }
    if (message.analog_forward_delta !== undefined) {
      writer.uint32(37).float(message.analog_forward_delta);
    }
    if (message.analog_left_delta !== undefined) {
      writer.uint32(45).float(message.analog_left_delta);
    }
    if (message.pitch_delta !== undefined) {
      writer.uint32(69).float(message.pitch_delta);
    }
    if (message.yaw_delta !== undefined) {
      writer.uint32(77).float(message.yaw_delta);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CSubtickMoveStep {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCSubtickMoveStep();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.button = reader.uint64().toString();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.pressed = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 29) {
            break;
          }

          message.when = reader.float();
          continue;
        }
        case 4: {
          if (tag !== 37) {
            break;
          }

          message.analog_forward_delta = reader.float();
          continue;
        }
        case 5: {
          if (tag !== 45) {
            break;
          }

          message.analog_left_delta = reader.float();
          continue;
        }
        case 8: {
          if (tag !== 69) {
            break;
          }

          message.pitch_delta = reader.float();
          continue;
        }
        case 9: {
          if (tag !== 77) {
            break;
          }

          message.yaw_delta = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CSubtickMoveStep {
    return {
      button: isSet(object.button) ? globalThis.String(object.button) : undefined,
      pressed: isSet(object.pressed) ? globalThis.Boolean(object.pressed) : undefined,
      when: isSet(object.when) ? globalThis.Number(object.when) : undefined,
      analog_forward_delta: isSet(object.analogForwardDelta)
        ? globalThis.Number(object.analogForwardDelta)
        : isSet(object.analog_forward_delta)
        ? globalThis.Number(object.analog_forward_delta)
        : undefined,
      analog_left_delta: isSet(object.analogLeftDelta)
        ? globalThis.Number(object.analogLeftDelta)
        : isSet(object.analog_left_delta)
        ? globalThis.Number(object.analog_left_delta)
        : undefined,
      pitch_delta: isSet(object.pitchDelta)
        ? globalThis.Number(object.pitchDelta)
        : isSet(object.pitch_delta)
        ? globalThis.Number(object.pitch_delta)
        : undefined,
      yaw_delta: isSet(object.yawDelta)
        ? globalThis.Number(object.yawDelta)
        : isSet(object.yaw_delta)
        ? globalThis.Number(object.yaw_delta)
        : undefined,
    };
  },

  toJSON(message: CSubtickMoveStep): unknown {
    const obj: any = {};
    if (message.button !== undefined) {
      obj.button = message.button;
    }
    if (message.pressed !== undefined) {
      obj.pressed = message.pressed;
    }
    if (message.when !== undefined) {
      obj.when = message.when;
    }
    if (message.analog_forward_delta !== undefined) {
      obj.analogForwardDelta = message.analog_forward_delta;
    }
    if (message.analog_left_delta !== undefined) {
      obj.analogLeftDelta = message.analog_left_delta;
    }
    if (message.pitch_delta !== undefined) {
      obj.pitchDelta = message.pitch_delta;
    }
    if (message.yaw_delta !== undefined) {
      obj.yawDelta = message.yaw_delta;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CSubtickMoveStep>, I>>(base?: I): CSubtickMoveStep {
    return CSubtickMoveStep.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CSubtickMoveStep>, I>>(object: I): CSubtickMoveStep {
    const message = createBaseCSubtickMoveStep();
    message.button = object.button ?? undefined;
    message.pressed = object.pressed ?? undefined;
    message.when = object.when ?? undefined;
    message.analog_forward_delta = object.analog_forward_delta ?? undefined;
    message.analog_left_delta = object.analog_left_delta ?? undefined;
    message.pitch_delta = object.pitch_delta ?? undefined;
    message.yaw_delta = object.yaw_delta ?? undefined;
    return message;
  },
};

function createBaseCBaseUserCmdExecutionNotes(): CBaseUserCmdExecutionNotes {
  return { ignored_reason: undefined };
}

export const CBaseUserCmdExecutionNotes: MessageFns<CBaseUserCmdExecutionNotes> = {
  encode(message: CBaseUserCmdExecutionNotes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ignored_reason !== undefined) {
      writer.uint32(10).string(message.ignored_reason);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CBaseUserCmdExecutionNotes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCBaseUserCmdExecutionNotes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.ignored_reason = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CBaseUserCmdExecutionNotes {
    return {
      ignored_reason: isSet(object.ignoredReason)
        ? globalThis.String(object.ignoredReason)
        : isSet(object.ignored_reason)
        ? globalThis.String(object.ignored_reason)
        : undefined,
    };
  },

  toJSON(message: CBaseUserCmdExecutionNotes): unknown {
    const obj: any = {};
    if (message.ignored_reason !== undefined) {
      obj.ignoredReason = message.ignored_reason;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CBaseUserCmdExecutionNotes>, I>>(base?: I): CBaseUserCmdExecutionNotes {
    return CBaseUserCmdExecutionNotes.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CBaseUserCmdExecutionNotes>, I>>(object: I): CBaseUserCmdExecutionNotes {
    const message = createBaseCBaseUserCmdExecutionNotes();
    message.ignored_reason = object.ignored_reason ?? undefined;
    return message;
  },
};

function createBaseCBaseUserCmdPB(): CBaseUserCmdPB {
  return {
    legacy_command_number: undefined,
    client_tick: undefined,
    prediction_offset_ticks_x256: undefined,
    buttons_pb: undefined,
    viewangles: undefined,
    forwardmove: undefined,
    leftmove: undefined,
    upmove: undefined,
    impulse: undefined,
    weaponselect: undefined,
    random_seed: undefined,
    mousedx: undefined,
    mousedy: undefined,
    pawn_entity_handle: undefined,
    subtick_moves: [],
    move_crc: undefined,
    consumed_server_angle_changes: undefined,
    cmd_flags: undefined,
    execution_notes: undefined,
  };
}

export const CBaseUserCmdPB: MessageFns<CBaseUserCmdPB> = {
  encode(message: CBaseUserCmdPB, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.legacy_command_number !== undefined) {
      writer.uint32(8).int32(message.legacy_command_number);
    }
    if (message.client_tick !== undefined) {
      writer.uint32(16).int32(message.client_tick);
    }
    if (message.prediction_offset_ticks_x256 !== undefined) {
      writer.uint32(136).uint32(message.prediction_offset_ticks_x256);
    }
    if (message.buttons_pb !== undefined) {
      CInButtonStatePB.encode(message.buttons_pb, writer.uint32(26).fork()).join();
    }
    if (message.viewangles !== undefined) {
      CMsgQAngle.encode(message.viewangles, writer.uint32(34).fork()).join();
    }
    if (message.forwardmove !== undefined) {
      writer.uint32(45).float(message.forwardmove);
    }
    if (message.leftmove !== undefined) {
      writer.uint32(53).float(message.leftmove);
    }
    if (message.upmove !== undefined) {
      writer.uint32(61).float(message.upmove);
    }
    if (message.impulse !== undefined) {
      writer.uint32(64).int32(message.impulse);
    }
    if (message.weaponselect !== undefined) {
      writer.uint32(72).int32(message.weaponselect);
    }
    if (message.random_seed !== undefined) {
      writer.uint32(80).int32(message.random_seed);
    }
    if (message.mousedx !== undefined) {
      writer.uint32(88).int32(message.mousedx);
    }
    if (message.mousedy !== undefined) {
      writer.uint32(96).int32(message.mousedy);
    }
    if (message.pawn_entity_handle !== undefined) {
      writer.uint32(112).uint32(message.pawn_entity_handle);
    }
    for (const v of message.subtick_moves) {
      CSubtickMoveStep.encode(v!, writer.uint32(146).fork()).join();
    }
    if (message.move_crc !== undefined) {
      writer.uint32(154).bytes(message.move_crc);
    }
    if (message.consumed_server_angle_changes !== undefined) {
      writer.uint32(160).uint32(message.consumed_server_angle_changes);
    }
    if (message.cmd_flags !== undefined) {
      writer.uint32(168).int32(message.cmd_flags);
    }
    if (message.execution_notes !== undefined) {
      CBaseUserCmdExecutionNotes.encode(message.execution_notes, writer.uint32(178).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CBaseUserCmdPB {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCBaseUserCmdPB();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.legacy_command_number = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.client_tick = reader.int32();
          continue;
        }
        case 17: {
          if (tag !== 136) {
            break;
          }

          message.prediction_offset_ticks_x256 = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.buttons_pb = CInButtonStatePB.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.viewangles = CMsgQAngle.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 45) {
            break;
          }

          message.forwardmove = reader.float();
          continue;
        }
        case 6: {
          if (tag !== 53) {
            break;
          }

          message.leftmove = reader.float();
          continue;
        }
        case 7: {
          if (tag !== 61) {
            break;
          }

          message.upmove = reader.float();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.impulse = reader.int32();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.weaponselect = reader.int32();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.random_seed = reader.int32();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.mousedx = reader.int32();
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.mousedy = reader.int32();
          continue;
        }
        case 14: {
          if (tag !== 112) {
            break;
          }

          message.pawn_entity_handle = reader.uint32();
          continue;
        }
        case 18: {
          if (tag !== 146) {
            break;
          }

          message.subtick_moves.push(CSubtickMoveStep.decode(reader, reader.uint32()));
          continue;
        }
        case 19: {
          if (tag !== 154) {
            break;
          }

          message.move_crc = reader.bytes();
          continue;
        }
        case 20: {
          if (tag !== 160) {
            break;
          }

          message.consumed_server_angle_changes = reader.uint32();
          continue;
        }
        case 21: {
          if (tag !== 168) {
            break;
          }

          message.cmd_flags = reader.int32();
          continue;
        }
        case 22: {
          if (tag !== 178) {
            break;
          }

          message.execution_notes = CBaseUserCmdExecutionNotes.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CBaseUserCmdPB {
    return {
      legacy_command_number: isSet(object.legacyCommandNumber)
        ? globalThis.Number(object.legacyCommandNumber)
        : isSet(object.legacy_command_number)
        ? globalThis.Number(object.legacy_command_number)
        : undefined,
      client_tick: isSet(object.clientTick)
        ? globalThis.Number(object.clientTick)
        : isSet(object.client_tick)
        ? globalThis.Number(object.client_tick)
        : undefined,
      prediction_offset_ticks_x256: isSet(object.predictionOffsetTicksX256)
        ? globalThis.Number(object.predictionOffsetTicksX256)
        : isSet(object.prediction_offset_ticks_x256)
        ? globalThis.Number(object.prediction_offset_ticks_x256)
        : undefined,
      buttons_pb: isSet(object.buttonsPb)
        ? CInButtonStatePB.fromJSON(object.buttonsPb)
        : isSet(object.buttons_pb)
        ? CInButtonStatePB.fromJSON(object.buttons_pb)
        : undefined,
      viewangles: isSet(object.viewangles) ? CMsgQAngle.fromJSON(object.viewangles) : undefined,
      forwardmove: isSet(object.forwardmove) ? globalThis.Number(object.forwardmove) : undefined,
      leftmove: isSet(object.leftmove) ? globalThis.Number(object.leftmove) : undefined,
      upmove: isSet(object.upmove) ? globalThis.Number(object.upmove) : undefined,
      impulse: isSet(object.impulse) ? globalThis.Number(object.impulse) : undefined,
      weaponselect: isSet(object.weaponselect) ? globalThis.Number(object.weaponselect) : undefined,
      random_seed: isSet(object.randomSeed)
        ? globalThis.Number(object.randomSeed)
        : isSet(object.random_seed)
        ? globalThis.Number(object.random_seed)
        : undefined,
      mousedx: isSet(object.mousedx) ? globalThis.Number(object.mousedx) : undefined,
      mousedy: isSet(object.mousedy) ? globalThis.Number(object.mousedy) : undefined,
      pawn_entity_handle: isSet(object.pawnEntityHandle)
        ? globalThis.Number(object.pawnEntityHandle)
        : isSet(object.pawn_entity_handle)
        ? globalThis.Number(object.pawn_entity_handle)
        : undefined,
      subtick_moves: globalThis.Array.isArray(object?.subtickMoves)
        ? object.subtickMoves.map((e: any) => CSubtickMoveStep.fromJSON(e))
        : globalThis.Array.isArray(object?.subtick_moves)
        ? object.subtick_moves.map((e: any) => CSubtickMoveStep.fromJSON(e))
        : [],
      move_crc: isSet(object.moveCrc)
        ? bytesFromBase64(object.moveCrc)
        : isSet(object.move_crc)
        ? bytesFromBase64(object.move_crc)
        : undefined,
      consumed_server_angle_changes: isSet(object.consumedServerAngleChanges)
        ? globalThis.Number(object.consumedServerAngleChanges)
        : isSet(object.consumed_server_angle_changes)
        ? globalThis.Number(object.consumed_server_angle_changes)
        : undefined,
      cmd_flags: isSet(object.cmdFlags)
        ? globalThis.Number(object.cmdFlags)
        : isSet(object.cmd_flags)
        ? globalThis.Number(object.cmd_flags)
        : undefined,
      execution_notes: isSet(object.executionNotes)
        ? CBaseUserCmdExecutionNotes.fromJSON(object.executionNotes)
        : isSet(object.execution_notes)
        ? CBaseUserCmdExecutionNotes.fromJSON(object.execution_notes)
        : undefined,
    };
  },

  toJSON(message: CBaseUserCmdPB): unknown {
    const obj: any = {};
    if (message.legacy_command_number !== undefined) {
      obj.legacyCommandNumber = Math.round(message.legacy_command_number);
    }
    if (message.client_tick !== undefined) {
      obj.clientTick = Math.round(message.client_tick);
    }
    if (message.prediction_offset_ticks_x256 !== undefined) {
      obj.predictionOffsetTicksX256 = Math.round(message.prediction_offset_ticks_x256);
    }
    if (message.buttons_pb !== undefined) {
      obj.buttonsPb = CInButtonStatePB.toJSON(message.buttons_pb);
    }
    if (message.viewangles !== undefined) {
      obj.viewangles = CMsgQAngle.toJSON(message.viewangles);
    }
    if (message.forwardmove !== undefined) {
      obj.forwardmove = message.forwardmove;
    }
    if (message.leftmove !== undefined) {
      obj.leftmove = message.leftmove;
    }
    if (message.upmove !== undefined) {
      obj.upmove = message.upmove;
    }
    if (message.impulse !== undefined) {
      obj.impulse = Math.round(message.impulse);
    }
    if (message.weaponselect !== undefined) {
      obj.weaponselect = Math.round(message.weaponselect);
    }
    if (message.random_seed !== undefined) {
      obj.randomSeed = Math.round(message.random_seed);
    }
    if (message.mousedx !== undefined) {
      obj.mousedx = Math.round(message.mousedx);
    }
    if (message.mousedy !== undefined) {
      obj.mousedy = Math.round(message.mousedy);
    }
    if (message.pawn_entity_handle !== undefined) {
      obj.pawnEntityHandle = Math.round(message.pawn_entity_handle);
    }
    if (message.subtick_moves?.length) {
      obj.subtickMoves = message.subtick_moves.map((e) => CSubtickMoveStep.toJSON(e));
    }
    if (message.move_crc !== undefined) {
      obj.moveCrc = base64FromBytes(message.move_crc);
    }
    if (message.consumed_server_angle_changes !== undefined) {
      obj.consumedServerAngleChanges = Math.round(message.consumed_server_angle_changes);
    }
    if (message.cmd_flags !== undefined) {
      obj.cmdFlags = Math.round(message.cmd_flags);
    }
    if (message.execution_notes !== undefined) {
      obj.executionNotes = CBaseUserCmdExecutionNotes.toJSON(message.execution_notes);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CBaseUserCmdPB>, I>>(base?: I): CBaseUserCmdPB {
    return CBaseUserCmdPB.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CBaseUserCmdPB>, I>>(object: I): CBaseUserCmdPB {
    const message = createBaseCBaseUserCmdPB();
    message.legacy_command_number = object.legacy_command_number ?? undefined;
    message.client_tick = object.client_tick ?? undefined;
    message.prediction_offset_ticks_x256 = object.prediction_offset_ticks_x256 ?? undefined;
    message.buttons_pb = (object.buttons_pb !== undefined && object.buttons_pb !== null)
      ? CInButtonStatePB.fromPartial(object.buttons_pb)
      : undefined;
    message.viewangles = (object.viewangles !== undefined && object.viewangles !== null)
      ? CMsgQAngle.fromPartial(object.viewangles)
      : undefined;
    message.forwardmove = object.forwardmove ?? undefined;
    message.leftmove = object.leftmove ?? undefined;
    message.upmove = object.upmove ?? undefined;
    message.impulse = object.impulse ?? undefined;
    message.weaponselect = object.weaponselect ?? undefined;
    message.random_seed = object.random_seed ?? undefined;
    message.mousedx = object.mousedx ?? undefined;
    message.mousedy = object.mousedy ?? undefined;
    message.pawn_entity_handle = object.pawn_entity_handle ?? undefined;
    message.subtick_moves = object.subtick_moves?.map((e) => CSubtickMoveStep.fromPartial(e)) || [];
    message.move_crc = object.move_crc ?? undefined;
    message.consumed_server_angle_changes = object.consumed_server_angle_changes ?? undefined;
    message.cmd_flags = object.cmd_flags ?? undefined;
    message.execution_notes = (object.execution_notes !== undefined && object.execution_notes !== null)
      ? CBaseUserCmdExecutionNotes.fromPartial(object.execution_notes)
      : undefined;
    return message;
  },
};

function createBaseCUserCmdBasePB(): CUserCmdBasePB {
  return { base: undefined };
}

export const CUserCmdBasePB: MessageFns<CUserCmdBasePB> = {
  encode(message: CUserCmdBasePB, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.base !== undefined) {
      CBaseUserCmdPB.encode(message.base, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CUserCmdBasePB {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCUserCmdBasePB();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.base = CBaseUserCmdPB.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CUserCmdBasePB {
    return { base: isSet(object.base) ? CBaseUserCmdPB.fromJSON(object.base) : undefined };
  },

  toJSON(message: CUserCmdBasePB): unknown {
    const obj: any = {};
    if (message.base !== undefined) {
      obj.base = CBaseUserCmdPB.toJSON(message.base);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CUserCmdBasePB>, I>>(base?: I): CUserCmdBasePB {
    return CUserCmdBasePB.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CUserCmdBasePB>, I>>(object: I): CUserCmdBasePB {
    const message = createBaseCUserCmdBasePB();
    message.base = (object.base !== undefined && object.base !== null)
      ? CBaseUserCmdPB.fromPartial(object.base)
      : undefined;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from((globalThis as any).Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return (globalThis as any).Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
